enable_private_room: true
enable_bullet_msg_all_room: true
auto_kill_live:
  # 啟用此機制開關
  enabled: true
  # 設置達多少分鐘需關播的條件 (分鐘)
  empty_room_check_mins: 28
  # 設置被關播後，限制的開播時間 (分鐘)
  cool_down_time_mins: 5
