# Slack bot (deployment) config
#
# Author: CM Chung
# this file is deployment (alfred) for lit project
# Every service belongs to a type (go, nodejs, webapp, or spinnaker)
# Every type has its own settings like Jenkins endpoints which base on environments
type:
  lit:           "go"
  lit-worker:    "go"
  lit-web:       "webapp"
  lit-dashboard: "webapp"
groups:
  backend:
    lit:           "go"
    lit-worker:    "go"
  frontend:
    lit-web:       "webapp"
    lit-dashboard: "webapp"
settings:
  go:
    k8sprod:
      endpoint: 'Lit/job/prod-backend-deploy/buildWithParameters?token=gz6E0latrZOse6awWP1ynWmQ6y9ug27yh2T98Nyi'
    k8ssta:
      endpoint: 'Lit/job/stag-backend-deploy/buildWithParameters?token=nKnqqUm2y0JlW8wek4Ae0HD1xUpUBD04T15AjmwT'
  webapp:
    prod:
      endpoint: 'Lit/job/prod-web-deploy/buildWithParameters?token=tHhPGFznbWbLcpeQZioZzewJnUPT42UmNRnDRUyh'
