platform:
  ios:
    default:
      enable: true
      features:
        - id: 17skin
          enable: true
          min: 0
          max: 1
          default: 0
          adjustMode: toggle
          displayName: streamer_beautify_homemade
          iconUrl: https://assets-17app.akamaized.net/7038316c-9c8c-4df7-b71a-488a713235d2.png
          type: 17
        - id: skinSoften #磨皮
          enable: true
          min: 0
          max: 100
          default: 55
          adjustMode: slider
          displayName: streamer_beautify_scrub
          iconUrl: https://assets-17app.akamaized.net/c58a63c4-7f80-4042-a948-76b23bee0ed3.png
          type: 360
        - id: skinWhitening #白皙
          enable: true
          min: 0
          max: 1
          default: 0.55
          adjustMode: slider
          displayName: streamer_beautify_whitening
          iconUrl: https://assets-17app.akamaized.net/55fe437f-a129-4211-ae41-6407a85e2624.png
          type: 360
        - id: skinPinking
          enable: true
          min: 0
          max: 1
          default: 0.5
          adjustMode: slider
          displayName: streamer_beautify_soft
          iconUrl: https://assets-17app.akamaized.net/eb7124a0-d659-4774-8b74-77582ca4e2da.png
          type: 360
        - id: skinRedden
          enable: true
          min: 0
          max: 1
          default: 0.55
          adjustMode: slider
          displayName: streamer_beautify_rosy
          iconUrl: https://assets-17app.akamaized.net/3022e1b2-6cbf-4d09-a5db-49f1068fa254.png
          type: 360
        - id: bigEye
          enable: true
          min: 0
          max: 50
          default: 5
          adjustMode: slider
          displayName: streamer_beautify_bigeyes
          iconUrl: https://assets-17app.akamaized.net/0b412bdd-61fd-4aaf-bc54-07465d813d5c.png
          type: 360
        - id: thinFace
          enable: true
          min: 0
          max: 50
          default: 5
          adjustMode: slider
          displayName: streamer_beautify_slimface
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 360
#    iPhone5,3:
  android:
    default:
      enable: true
      features:
        - id: 17skin
          enable: true
          min: 0
          max: 1
          default: 0
          adjustMode: toggle
          displayName: streamer_beautify_homemade
          iconUrl: https://assets-17app.akamaized.net/7038316c-9c8c-4df7-b71a-488a713235d2.png
          type: 17
        - id: skinSoften #磨皮
          enable: true
          min: 0
          max: 100
          default: 55
          adjustMode: slider
          displayName: streamer_beautify_scrub
          iconUrl: https://assets-17app.akamaized.net/c58a63c4-7f80-4042-a948-76b23bee0ed3.png
          type: 360
        - id: skinWhitening #白皙
          enable: true
          min: 0
          max: 1
          default: 0.55
          adjustMode: slider
          displayName: streamer_beautify_whitening
          iconUrl: https://assets-17app.akamaized.net/55fe437f-a129-4211-ae41-6407a85e2624.png
          type: 360
        - id: skinPinking
          enable: true
          min: 0
          max: 1
          default: 0.5
          adjustMode: slider
          displayName: streamer_beautify_soft
          iconUrl: https://assets-17app.akamaized.net/eb7124a0-d659-4774-8b74-77582ca4e2da.png
          type: 360
        - id: skinRedden
          enable: true
          min: 0
          max: 1
          default: 0.55
          adjustMode: slider
          displayName: streamer_beautify_rosy
          iconUrl: https://assets-17app.akamaized.net/3022e1b2-6cbf-4d09-a5db-49f1068fa254.png
          type: 360
        - id: bigEye
          enable: true
          min: 0
          max: 50
          default: 5
          adjustMode: slider
          displayName: streamer_beautify_bigeyes
          iconUrl: https://assets-17app.akamaized.net/0b412bdd-61fd-4aaf-bc54-07465d813d5c.png
          type: 360
        - id: thinFace
          enable: true
          min: 0
          max: 50
          default: 5
          adjustMode: slider
          displayName: streamer_beautify_slimface
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 360
#    Pixel 2:
