iconInfos:
  - startTime: "2021-10-14 00:13:00 (GMT-0700)"
    endTime: "2021-10-31 00:21:00 (GMT-0700)"
    liveIcon:
      activeImg: https://cdn.17app.co/55be4713-417b-416d-b772-e1f2cf25ddfa.png
      disabledImg: https://cdn.17app.co/00d8f3ef-539d-4448-bc46-a7cb55ff075e.png
    exploreIcon:
      activeImg: https://cdn.17app.co/bc810d29-f2a8-48a4-9313-413fccbc879b.png
      disabledImg: https://cdn.17app.co/46b1a77f-c899-4f57-8338-aeef177935e2.png
    feedIcon:
      activeImg: https://cdn.17app.co/d51cae0d-0df8-4fc9-9aa9-eaed9aeae777.png
      disabledImg: https://cdn.17app.co/e0f7ee62-2fd2-44eb-8a0c-165154b0e278.png
    profileIcon:
      activeImg: https://cdn.17app.co/065f2fc2-4177-4093-bdda-6912cfb8f6ab.png
      disabledImg: https://cdn.17app.co/e0788697-53d2-412d-8531-9c94af60aa44.png
    notificationsIconImg: https://cdn.17app.co/dae58671-5ed0-4631-9a4a-a204427041d3.png
    leaderboardIconImg: https://cdn.17app.co/ab80814d-df69-4f54-b54c-33439af745e7.png
