max: 2	# 0 means disable feature
check_interval: 5m00s
big_brother_prefix: "give_me_five"
nian_prefix: "nian"
ccu: 0
streamDuration: 0h00m00s
animations: ["yeti"]
monsters:
- id: monster_1
  hit_consume: 10
  duration: 30s
  stream_alive_threshold: 1m00s
  animation: "yeti"
  appear_durations:
  - start_time: 00h00m00s
    end_time: 01h00m00s
  - start_time: 23h00m00s
    end_time: 24h00m00s
  type: 0
  share_ratio: 50 # percentage
  profit_ratio: 35 # percentage
  bonus: 200
  infoPageiconURL: https://assets-17app.akamaized.net/d1d67cab-3f7b-439f-86d8-aed1cf327fdb.png
  winnerPageiconURL: https://assets-17app.akamaized.net/9b0cf5bc-8289-4af0-b7d4-41869506db6a.png
  hintToken: {key: monster_battle_hint,fontAttribute: {textColor: "#FFFFFF"}}
  rule1Token: {key: monster_battle_rule1,fontAttribute: {textColor: "#FFFFFF"}}
  rule2Token: {key: monster_battle_rule2,fontAttribute: {textColor: "#FFFFFF"}}
  rule3Token: {key: monster_battle_rule3,fontAttribute: {textColor: "#FFFFFF"}} 
  rule4Token: {key: monster_battle_rule4,fontAttribute: {textColor: "#FFFFFF"}}
  countdownToken: {key: monster_battle_countdown,fontAttribute: {textColor: "#FFFFFF"}}
  failureToken: {key: monster_battle_failure,fontAttribute: {textColor: "#FFFFFF"}}


- id: monster_3
  animation: "give_me_five"
  hit_consume: 10
  duration: 30s
  stream_alive_threshold: 1m00s
  appear_durations:
  - start_time: 00h00m00s
    end_time: 10h00m00s
  type: 0
  share_ratio: 50 # percentage
  profit_ratio: 35 # percentage
  bonus: 400
  infoPageiconURL: https://assets-17app.akamaized.net/0e302f14-4bc4-4031-8f10-1623bd311c00.png
  winnerPageiconURL: https://assets-17app.akamaized.net/724adf04-816f-484d-bd8b-ddb0346e8513.png
  hintToken: {key: monster_battle_hint_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  rule1Token: {key: monster_battle_rule1_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  rule2Token: {key: monster_battle_rule2_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  rule3Token: {key: monster_battle_rule3_bbro,fontAttribute: {textColor: "#FFFFFF"}} 
  rule4Token: {key: monster_battle_rule4_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  countdownToken: {key: monster_battle_countdown_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  failureToken: {key: monster_battle_failure_bbro,fontAttribute: {textColor: "#FFFFFF"}}

- id: summon_monster_1
  hit_consume: 10
  duration: 60s
  stream_alive_threshold: 1m00s
  animation: nian
  appear_durations:
  - start_time: 00h00m00s
    end_time: 24h00m00s
  type: 1
  summonGifts:
  - giftID: "gift_lightstick_r"
    probability: 1000 # n / 10000 * 100%
  - giftID: "gift_lightstick_g"
    probability: 100 # n / 10000 * 100%
  share_ratio: 50 # percentage
  profit_ratio: 35 # percentage
  bonus: 336
  infoPageiconURL: https://assets-17app.akamaized.net/d976d5f7-d0f4-4637-a808-93a7fdbaa03c.png
  winnerPageiconURL: https://assets-17app.akamaized.net/80740d0d-ffb7-40ae-94d9-2eaa4e2dda9d.png
  hintToken: {key: monster_battle_summon_hint_nian,fontAttribute: {textColor: "#FFFFFF"}}
  rule1Token: {key: monster_battle_summon_rule1_nian,fontAttribute: {textColor: "#FFFFFF"}}
  rule2Token: {key: monster_battle_summon_rule2_nian,fontAttribute: {textColor: "#FFFFFF"}}
  rule3Token: {key: monster_battle_summon_rule3_nian,fontAttribute: {textColor: "#FFFFFF"}}
  rule4Token: {key: monster_battle_summon_rule4_nian,fontAttribute: {textColor: "#FFFFFF"}}
  countdownToken: {key: monster_battle_summon_countdown_nian,fontAttribute: {textColor: "#FFFFFF"}}
  failureToken: {key: monster_battle_summon_failure_nian,fontAttribute: {textColor: "#FFFFFF"}}

- id: summon_monster_2
  hit_consume: 10
  duration: 60s
  stream_alive_threshold: 1m00s
  animation: blue
  appear_durations:
  - start_time: 00h00m00s
    end_time: 24h00m00s
  type: 1
  summonGifts:
  - giftID: "gift_lightstick_b"
    probability: 5000 # n / 10000 * 100%
  share_ratio: 50 # percentage
  profit_ratio: 35 # percentage
  bonus: 336
  infoPageiconURL: https://assets-17app.akamaized.net/d976d5f7-d0f4-4637-a808-93a7fdbaa03c.png
  winnerPageiconURL: https://assets-17app.akamaized.net/80740d0d-ffb7-40ae-94d9-2eaa4e2dda9d.png
  hintToken: {key: monster_battle_summon_hint_nian,fontAttribute: {textColor: "#FFFFFF"}}
  rule1Token: {key: monster_battle_summon_rule1_nian,fontAttribute: {textColor: "#FFFFFF"}}
  rule2Token: {key: monster_battle_summon_rule2_nian,fontAttribute: {textColor: "#FFFFFF"}}
  rule3Token: {key: monster_battle_summon_rule3_nian,fontAttribute: {textColor: "#FFFFFF"}}
  rule4Token: {key: monster_battle_summon_rule4_nian,fontAttribute: {textColor: "#FFFFFF"}}
  countdownToken: {key: monster_battle_summon_countdown_nian,fontAttribute: {textColor: "#FFFFFF"}}
  failureToken: {key: monster_battle_summon_failure_nian,fontAttribute: {textColor: "#FFFFFF"}}

animationLoader:
- url: https://assets-17app.akamaized.net/98b26445-2625-49a5-a541-ddf6a0256c00.zip
  webpUrl: https://assets-17app.akamaized.net/d679eb31-e6d9-456c-a32e-9551fed77bf6-q90-s1.webp
  animationID: yeti_attack
  MD5: cade4fda7b8df5df5f68c5de4a54cb6d
  webpMD5: 7de51dc2b2863ae56820a9daa54e2521
- url: https://assets-17app.akamaized.net/7da4c8ee-92fe-4401-a40a-8f8d3b83a468.zip
  webpUrl: https://assets-17app.akamaized.net/31539154-3931-496f-9c3a-9b14b00c9084-q90-s1.webp
  animationID: yeti_enter
  MD5: 21e55806c1a3f90f0da8ce6b1c842020    
  webpMD5: 0436df384fc36d9160ed091bebff916e 
- url: https://assets-17app.akamaized.net/186f2462-5b2c-44b2-b8d3-8afd9205ef5a.zip
  webpUrl: https://assets-17app.akamaized.net/6e9f5adb-51f7-4616-977d-19b24f948a9d-q90-s1.webp
  animationID: yeti_failure
  MD5: d16766e3e7a869fe233b044875d0e5dc 
  webpMD5: 4ad8a1028c624cc1246b369c239953e7 
- url: https://assets-17app.akamaized.net/74af23df-c996-40b3-8413-f3c4f739c0e2.zip
  webpUrl: https://assets-17app.akamaized.net/27048f58-09fc-44ea-af46-e3444002663b-q90-s1.webp
  animationID: yeti_idle
  MD5: f09681eef41fe05ffd2f9b1c6c27e480
  webpMD5: 88b5ea9f2f0eba52d53be1c93da7955a
- url: https://assets-17app.akamaized.net/b17614de-2b49-418b-920e-e2008e66030e.zip
  webpUrl: https://assets-17app.akamaized.net/7a56b6eb-13f6-4f90-afcb-591c63da47b2-q90-s1.webp
  animationID: yeti_success
  MD5: cfecdf2c6b523f9138c48ec480a1925f
  webpMD5: 7e8bc69aab41d3949f4bb9560d5000eb 
- url: https://assets-17app.akamaized.net/22460b27-5d8d-4ace-af44-dd48d135ff35.zip
  webpUrl: https://assets-17app.akamaized.net/a0ec4825-3dc7-4b38-b6aa-5d82b11f84be-q90-s1.webp
  animationID: give_me_five_attack
  MD5: 611201b0b1e4b7863862761d07fef0f0
  webpMD5: 7c4fb9832e0fd34c450d56f662028413
- url: https://assets-17app.akamaized.net/376da960-74f9-436a-9f06-96748528eddb.zip
  webpUrl: https://assets-17app.akamaized.net/5703f137-429b-4e3c-bc2f-6ad5e39783fc-q90-s1.webp
  animationID: give_me_five_enter
  MD5: c39347f9af80456e403f1399704737fd  
  webpMD5: 9ba611705f77f0516b0874b50b1eecc9   
- url: https://assets-17app.akamaized.net/02121681-3b61-4d43-80e2-3632ac35ff1b.zip
  webpUrl: https://assets-17app.akamaized.net/f0d8f499-ba91-4c99-aabb-e422739613f4-q90-s1.webp
  animationID: give_me_five_failure
  MD5: 485d777577ed27fc37d5d4acaa8559d7
  webpMD5: 506b47738a306d62ef04ad7cccb3596d 
- url: https://assets-17app.akamaized.net/d6161092-713c-4203-a4cf-0fc9b8feb628.zip
  webpUrl: https://assets-17app.akamaized.net/3d9afdbb-03e2-4976-a79d-1d2bd0a6678d-q90-s1.webp
  animationID: give_me_five_idle
  MD5: 00980a791d534ebbc2e200fbde4961e2
  webpMD5: 834794e2707bdac50c7fd1ab611b3743
- url: https://assets-17app.akamaized.net/59cb8f09-65e7-4938-b6c8-5449891bf13c.zip
  webpUrl: https://assets-17app.akamaized.net/8ff8927d-8ffa-4841-9658-ce0a9b4103ff-q90-s1.webp
  animationID: give_me_five_success
  MD5: c764112e6bf9c109200bf5f712963ddb     
  webpMD5: fd3ab7d2aa10dde39e118a4e9c724f7a
- url: https://assets-17app.akamaized.net/cca95ba8-52b4-4f86-8f1c-49ef8f41e9b0.zip
  webpUrl: https://assets-17app.akamaized.net/a613ead9-f33f-4347-952d-a9d69aa62c19-q90-s1.webp
  animationID: nian_attack
  MD5: ad5c9627a72a60b716376db908359758
  webpMD5: 8c4e4812e81ca582e0dc246f3369aa65
- url: https://assets-17app.akamaized.net/c0393b9e-05ab-4cff-8f77-cff7ab2058ca.zip
  webpUrl: https://assets-17app.akamaized.net/96f19fd3-98e1-4b35-80d5-565b7ee93d13-q90-s1.webp
  animationID: nian_enter
  MD5: 22a9b6f92d85036e68cc2c78b5dda958
  webpMD5: 771d108124663d2c304585bd63854980
- url: https://assets-17app.akamaized.net/fbbbd7d3-ccb7-46e1-b9c4-18e4fc553347.zip
  webpUrl: https://assets-17app.akamaized.net/beea5e92-1ee4-4296-8c4a-5922e07537e3-q90-s1.webp
  animationID: nian_failure
  MD5: 84bae019a4dca2dd37ba0e994468d133
  webpMD5: 83d67ab2c05c62930726f128f82ea836
- url: https://assets-17app.akamaized.net/a51b9e7d-60c4-44d8-9f01-329d22cdabcc.zip
  webpUrl: https://assets-17app.akamaized.net/d63f1052-822e-4bc6-8fee-bc10dc4a1690-q90-s1.webp
  animationID: nian_idle
  MD5: 192022a474100dc9169a4c3b6d159b25
  webpMD5: c48cf9912b0c857901498cc7b85123f1
- url: https://assets-17app.akamaized.net/5d103ca5-0d08-4995-9d63-6d3bc02884bf.zip
  webpUrl: https://assets-17app.akamaized.net/469e38b2-7f88-4ce4-8fa5-32ddfccc744b-q90-s1.webp
  animationID: nian_success
  MD5: eaefbb6da04f9400e1ab24bb887144e8
  webpMD5: 6c2d367ae929eace2dab9d7611f21bfc
- url: https://assets-17app.akamaized.net/5819fa91-6378-4a77-9186-8a43c14a60f9.zip 
  webpUrl: https://assets-17app.akamaized.net/f2866174-d86d-4cec-b4eb-38ee559f81b9-q90-s1.webp
  animationID: blue_attack
  MD5: 4823296c65a01e6fde08f684cd12c8cf
  webpMD5: 8f095544720d0f3c1edcf214226c9599
- url: https://assets-17app.akamaized.net/3b503ac8-8fd7-4cfb-957e-7f0a755cff23.zip
  webpUrl: https://assets-17app.akamaized.net/6f22fa15-f9a1-43d9-8e9e-3720f865439c-q90-s1.webp
  animationID: blue_enter
  MD5: 0999af412ac68545518a696f0adf2153
  webpMD5: d064e8e5655048416fc3fb8aa6c8e947
- url: https://assets-17app.akamaized.net/755182a7-86ad-4ea1-901a-4f046afcfd66.zip
  webpUrl: https://assets-17app.akamaized.net/e5397d7a-d75d-45b7-b14b-5df3253048ea-q90-s1.webp
  animationID: blue_failure
  MD5: ab655fb1f831dbedfa34baf0aaced482
  webpMD5: 83d67ab2c05c62930726f128f82ea836
- url: https://assets-17app.akamaized.net/c7860229-6bbb-4155-bf12-eab3c22f3dd0.zip
  webpUrl: https://assets-17app.akamaized.net/9e8d6bd1-5913-4fd2-8ae7-fc0f5a186185-q90-s1.webp
  animationID: blue_idle
  MD5: 853f513583c81eccbd32f7dfdb12e5b3
  webpMD5: ad32e91f2e06ed3d6b43b10d8058875b
- url: https://assets-17app.akamaized.net/e7bfc8c5-2305-4801-a72a-8bbc2a729deb.zip
  webpUrl: https://assets-17app.akamaized.net/c6fc50ec-0d04-4d94-a7e5-876c73f31fd8-q90-s1.webp
  animationID: blue_success
  MD5: eb35ba648be4ee73bf8b39581bdecbb8
  webpMD5: e664c92236ab15c6d3391aca8aee785a
