max: 30	# 0 means disable feature
check_interval: 1m00s
big_brother_prefix: "give_me_five"
nian_prefix: "nian"
ccu: 0
streamDuration: 0h00m00s
alertMembers: ["angus"]
alertChannels: ["testformonsteralert"]
animations: ["yeti"]


monsters:

- id: skeleton # ハロウィン
  type: 1  # 0: 一般怪獸, 1: 招喚怪獸
  hit_consume: 1
  duration: 60s
  stream_alive_threshold: 1m00s
  animation: "skeleton"
  available_dates: # 一般怪獸才會看時間
    - start_date: "2022-10-17T12:25:00+08:00"
      end_date: "2022-10-30T23:59:59+08:00"
  appear_durations: # 一般怪獸才會看時間
    - start_time: 00h00m00s
      end_time: 23h59m59s

  share_ratio: 50 # percentage
  profit_ratio: 35 # percentage
  bonus: 100
  weight: 1
  infoPageiconURL: https://cdn.17app.co/66f2728b-d25f-4c72-b9fc-6a070081a3a0.png
  winnerPageiconURL: https://cdn.17app.co/66f2728b-d25f-4c72-b9fc-6a070081a3a0.png
  hintToken:
    {
      key: monster_battle_hint_skeleton,
      fontAttribute: { textColor: "#FFFFFF" },
    }
  rule1Token:
    {
      key: monster_battle_rule1_skeleton,
      fontAttribute: { textColor: "#FFFFFF" },
    }
  rule2Token:
    {
      key: monster_battle_rule2_skeleton_jp,
      fontAttribute: { textColor: "#FFFFFF" },
    }
  rule3Token:
    {
      key: monster_battle_rule3_skeleton,
      fontAttribute: { textColor: "#FFFFFF" },
    }
  rule4Token:
    {
      key: monster_battle_rule4_skeleton,
      fontAttribute: { textColor: "#FFFFFF" },
    }
  countdownToken:
    {
      key: monster_battle_countdown_skeleton,
      fontAttribute: { textColor: "#FFFFFF" },
    }
  failureToken:
    {
      key: monster_battle_failure_skeleton,
      fontAttribute: { textColor: "#FFFFFF" },
    }
  successToken:
    {
      key: monster_battle_success_skeleton_coin,
      fontAttribute: { textColor: "#FFFFFF" },
    }
  marqueeToken: { key: monster_battle_marquee_skeleton }
  summonGifts: # 招喚怪獸才需要填
    - giftID: 2210_jphalloween_trigger
      probability: 5000

animationLoader:

- animationID: skeleton_attack
  url: http://cdn.17app.co/22537d9b-709c-4690-9490-0f460021ee58.zip
  MD5: d1c50f66a0aa8e2dc3868382b0c0c306
  webpUrl: https://cdn.17app.co/80f9581a-bb10-4570-bb2e-db908031bcf1-q90-s1.webp
  webpMD5: a81a433a18195a2cdece203ed87d8048
- animationID: skeleton_enter
  url: http://cdn.17app.co/104bddf7-32ab-4eb9-9352-62543daf9a3c.zip
  MD5: b453d0023e8bf17bc86ce9f1bd1f5c72
  webpUrl: https://cdn.17app.co/0890014e-c49f-4c38-ad85-655a50ec717b-q90-s1.webp
  webpMD5: 6851d8b6093d3fb874e4eb7228bfdf39
- animationID: skeleton_failure
  url: http://cdn.17app.co/965736fc-b3ed-468b-8f39-db50392eba76.zip
  MD5: 7c857ce9700b65cdc47368b475d4f41b
  webpUrl: https://cdn.17app.co/b006083a-fc79-4b72-80b5-62c4bba03b6b-q90-s1.webp
  webpMD5: a7edb062cbfe7f9a4d5a8b18b8d93e45
- animationID: skeleton_idle
  url: http://cdn.17app.co/33addb21-16c3-450d-a4db-fb3569ecd5f1.zip
  MD5: 0594db0fccbb380b1c4f055a8f721517
  webpUrl: https://cdn.17app.co/acdeadcf-eb2b-4517-ae62-0485f5d0f168-q90-s1.webp
  webpMD5: 9d4cdc51c5be522052405748b0e15b6e
- animationID: skeleton_success
  url: http://cdn.17app.co/9fd5c066-b34d-431a-8f42-071224000dbd.zip
  MD5: fd290657d603f1184d43d277f81f23ea
  webpUrl: https://cdn.17app.co/1e434c16-b113-46c5-9f1a-7021a89dbfea-q90-s1.webp
  webpMD5: 80ff64ab8c2a03fc98716bfbad2868ec