max: 1000 # 0 means disable feature
check_interval: 1m00s
big_brother_prefix: "give_me_five"
nian_prefix: "nian"
ccu: 0
streamDuration: 0h00m00s
alertMembers: ["angus"]
alertChannels: ["testformonsteralert"]
animations: ["yeti"]

monsters:
  - id: skeleton # 南瓜骷髏
    type: 1  # 0: 一般怪獸, 1: 招喚怪獸
    hit_consume: 5
    duration: 60s
    stream_alive_threshold: 1m00s
    animation: "skeleton"
    available_dates: # 一般怪獸才會看時間
      - start_date: "2022-10-12T13:00:00+08:00"
        end_date: "2022-10-30T23:59:59+08:00"
    appear_durations: # 一般怪獸才會看時間
      - start_time: 00h00m00s
        end_time: 23h59m59s

    share_ratio: 50 # percentage
    profit_ratio: 35 # percentage
    bonus: 132
    weight: 1
    infoPageiconURL: https://cdn.17app.co/66f2728b-d25f-4c72-b9fc-6a070081a3a0.png
    winnerPageiconURL: https://cdn.17app.co/66f2728b-d25f-4c72-b9fc-6a070081a3a0.png
    hintToken:
      {
        key: monster_battle_hint_skeleton,
        fontAttribute: { textColor: "#FFFFFF" },
      }
    rule1Token:
      {
        key: monster_battle_rule1_skeleton,
        fontAttribute: { textColor: "#FFFFFF" },
      }
    rule2Token:
      {
        key: monster_battle_rule2_skeleton,
        fontAttribute: { textColor: "#FFFFFF" },
      }
    rule3Token:
      {
        key: monster_battle_rule3_skeleton,
        fontAttribute: { textColor: "#FFFFFF" },
      }
    rule4Token:
      {
        key: monster_battle_rule4_skeleton,
        fontAttribute: { textColor: "#FFFFFF" },
      }
    countdownToken:
      {
        key: monster_battle_countdown_skeleton,
        fontAttribute: { textColor: "#FFFFFF" },
      }
    failureToken:
      {
        key: monster_battle_failure_skeleton,
        fontAttribute: { textColor: "#FFFFFF" },
      }
    successToken:
      {
        key: monster_battle_success_skeleton_coin,
        fontAttribute: { textColor: "#FFFFFF" },
      }
    marqueeToken: { key: monster_battle_marquee_skeleton }
    summonGifts: # 招喚怪獸才需要填
      - giftID: 2210_ops_halloween_ghosts
        probability: 8000

animationLoader:
  # 南瓜骷髏
  - animationID: skeleton_attack
    url: http://cdn.17app.co/65f9dd7a-9f5a-4b78-ac08-3cbde77d3577.zip
    MD5: f90a28a282f780747d68feb3d9eed828
    webpUrl: https://cdn.17app.co/5624c739-aa96-48e6-9cda-d87ca1a97b2d-q90-s1.webp
    webpMD5: a81a433a18195a2cdece203ed87d8048
  - animationID: skeleton_enter
    url: http://cdn.17app.co/1e154634-3e45-453f-a807-806c0ea9ef0c.zip
    MD5: 0c099d096344b017df3da0ea2e131cb7
    webpUrl: https://cdn.17app.co/e89415b9-c4ea-4a8e-85c1-f16c8d5966f7-q90-s1.webp
    webpMD5: 6851d8b6093d3fb874e4eb7228bfdf39
  - animationID: skeleton_failure
    url: http://cdn.17app.co/3071c2ba-942f-42f3-857f-620afd26bb9a.zip
    MD5: cb1351a662e12c09db4fa8037771f576
    webpUrl: https://cdn.17app.co/4ee8cfb1-1fdc-42d1-899e-9eb0cec75a4e-q90-s1.webp
    webpMD5: a7edb062cbfe7f9a4d5a8b18b8d93e45
  - animationID: skeleton_idle
    url: http://cdn.17app.co/4eabde8b-a43c-4594-bfa1-573a8c3c4cf9.zip
    MD5: 7209e42527adba6d2f5e9159ab8700f7
    webpUrl: https://cdn.17app.co/7d75baa5-373a-4b6e-9d44-ff93cb905a2e-q90-s1.webp
    webpMD5: 9d4cdc51c5be522052405748b0e15b6e
  - animationID: skeleton_success
    url: http://cdn.17app.co/9d4e34b1-b9c0-4300-a50f-62282a6eaf8b.zip
    MD5: 93e66922f2a825d5aa22c0b95607a744
    webpUrl: https://cdn.17app.co/7b14918c-4fdc-499c-b504-0f76cf371f4f-q90-s1.webp
    webpMD5: 80ff64ab8c2a03fc98716bfbad2868ec
