iOSATTPermission:
  TW:
    prompt: false
  JP:
    prompt: false
  HK:
    prompt: false
  ID:
    prompt: false
  SG:
    prompt: false
  MO:
    prompt: false
  MY:
    prompt: false
  US:
    prompt: false
  MENA:
    prompt: false
  IN:
    prompt: false
  OTHERS:
    prompt: false

# TODO: remove it after migrate completed
myFollowPage:
  TW:
    showPromotionBanner: true
    showPushNotificationBanner: true
  JP:
    showPromotionBanner: true
    showPushNotificationBanner: true
  HK:
    showPromotionBanner: true
    showPushNotificationBanner: true
  US:
    showPromotionBanner: true
    showPushNotificationBanner: true
  MY:
    showPromotionBanner: true
    showPushNotificationBanner: true
  SG:
    showPromotionBanner: true
    showPushNotificationBanner: true
  MO:
    showPromotionBanner: true
    showPushNotificationBanner: true
  ID:
    showPromotionBanner: true
    showPushNotificationBanner: true
  MENA:
    showPromotionBanner: true
    showPushNotificationBanner: true
  PH:
    showPromotionBanner: true
    showPushNotificationBanner: true
  TH:
    showPromotionBanner: true
    showPushNotificationBanner: true
  VN:
    showPromotionBanner: true
    showPushNotificationBanner: true
  MM:
    showPromotionBanner: true
    showPushNotificationBanner: true
  IN:
    showPromotionBanner: true
    showPushNotificationBanner: true
