iconInfos:
#  - startTime: "2021-10-15 18:00:00 (GMT+0800)"
#    endTime: "2021-11-02 23:59:59 (GMT+0800)"
#    liveIcon:
#      activeImg: https://cdn.17app.co/82808495-e028-47d1-89a3-ddbec391673f.png
#      disabledImg: https://cdn.17app.co/ce8ad03f-5e5a-4b1a-ae55-ab6a4b2e89fe.png
#    exploreIcon:
#      activeImg: https://cdn.17app.co/6e05a4fe-0f78-493d-9fc6-e3221d177b5b.png
#      disabledImg: https://cdn.17app.co/644a1fbb-b12a-42ec-8a91-1184f2029c75.png
#    feedIcon:
#      activeImg: https://cdn.17app.co/e9097fac-3801-44ce-a0f8-a83b3c8fa89f.png
#      disabledImg: https://cdn.17app.co/3834027b-07f9-48a4-98b9-8817a3787d6b.png
#    profileIcon:
#      activeImg: https://cdn.17app.co/9aaca562-ff0e-4c5a-9d4d-c18a3742f0d3.png
#      disabledImg: https://cdn.17app.co/371dc9a5-0cbc-4c9f-9831-17339fb9bd16.png
#    notificationsIconImg: https://cdn.17app.co/7426cf4f-52a5-450e-9132-4553b570f041.png
#    leaderboardIconImg: https://cdn.17app.co/96ef5091-d8f4-4b4d-b7c1-cb183ead5f4f.png

  - startTime: 2022-01-30 10:00:00 (GMT+0800)
    endTime: 2022-02-06 23:59:59 (GMT+0800)
    liveIcon:
      activeImg: https://cdn.17app.co/a30e2638-e2a3-41c3-b7cb-7da2705ab67e.png
      disabledImg: https://cdn.17app.co/02b32d47-7409-4e74-bd23-b36ab8bed6dd.png
    exploreIcon:      
      activeImg: https://cdn.17app.co/79adeeb6-9ba8-46a0-81c8-70dfd01792b4.png      
      disabledImg: https://cdn.17app.co/c313f980-1d7a-42cc-9843-b70cf42cf37d.png
    followIcon:
      activeImg:
      disabledImg:
    videoIcon:
      activeImg:
      disabledImg:
    feedIcon:
      activeImg: https://cdn.17app.co/78be5206-f9dc-4025-9d2b-071cebb2cead.png
      disabledImg: https://cdn.17app.co/fb8a3c89-835d-49e1-ae56-70b454540be7.png
    profileIcon:      
      activeImg: https://cdn.17app.co/b63134ed-d29b-4e74-8511-8c7cf8468340.png
      disabledImg: https://cdn.17app.co/8c71f00c-d52b-46a6-a94e-b34193fb7e33.png
    navigationBarBackgroundImg:
    notificationsIconImg: https://cdn.17app.co/05a6d7f2-ed38-442b-be28-797e2e70741d.png
    leaderboardIconImg: https://cdn.17app.co/fb58a447-d5ce-4ad5-b6a5-e1cd396d00c2.png