iconInfos:
  - startTime: "2023-07-01 00:00:00 (GMT-0700)" #4th of July
    endTime: "2023-07-10 00:00:00 (GMT-0700)"
    liveIcon:
      activeImg: https://cdn.17app.co/19a264f7-671a-4285-ac40-ff882ba8b88c.png
      disabledImg: https://cdn.17app.co/f96f0854-b62f-4c71-b622-7d4814052015.png
    exploreIcon:
      activeImg: https://cdn.17app.co/2796f478-846d-4354-baaf-e5ccb5b7a61b.png
      disabledImg: https://cdn.17app.co/63a975ac-99c8-4bfa-8bbf-d2f6bcd280ad.png
    feedIcon:
      activeImg: https://cdn.17app.co/8b3619f9-42b6-4bc4-92d0-59f6b5f40473.png
      disabledImg: https://cdn.17app.co/89f0433f-8290-4de9-95fe-7e6e31159a73.png
    profileIcon:
      activeImg: https://cdn.17app.co/0c01d313-b930-41ca-b11e-e490073e903a.png
      disabledImg: https://cdn.17app.co/e2047f72-9674-4f48-be92-9999552a6861.png
    notificationsIconImg: https://cdn.17app.co/d638ea16-f8d2-4c7b-97ef-ae6ce6bb1bc7.png
    leaderboardIconImg: https://cdn.17app.co/4d44e366-e46c-4580-829b-95dc27f9e861.png

  - startTime: "2023-06-05 00:00:00 (GMT-0700)" #2023 Bestia II
    endTime: "2023-06-20 00:00:00 (GMT-0700)"
    liveIcon:
      activeImg: https://cdn.17app.co/1cc6d6d8-981e-48a9-aff3-6f6c652d1d6f.png
      disabledImg: https://cdn.17app.co/701028be-45ad-4001-9b83-af57adbec24b.png
    exploreIcon:
      activeImg: https://cdn.17app.co/c43f709f-0baa-4161-b10a-335d91aeab7d.png
      disabledImg: https://cdn.17app.co/bc507b1f-765c-4116-ab11-45bf8589cb4f.png
    feedIcon:
      activeImg: https://cdn.17app.co/a4148be5-3843-43ff-95e3-09757774b58f.png
      disabledImg: https://cdn.17app.co/37cc1d40-c474-4f44-8a4c-efef711506a1.png
    profileIcon:
      activeImg: https://cdn.17app.co/bd4eef9d-69ee-410a-b4da-35d1a91fff49.png
      disabledImg: https://cdn.17app.co/cae05ba5-55af-4411-aaba-3db421d2e9fa.png
    notificationsIconImg: https://cdn.17app.co/c31ba622-8dee-4e6f-b16a-698b6aa9233e.png
    leaderboardIconImg: https://cdn.17app.co/60b74637-9efc-476c-840a-7145848e3bfa.png

  - startTime: "2023-05-10 00:00:00 (GMT-0700)" #2023 Winning Bestia Dorothea
    endTime: "2023-05-27 00:00:00 (GMT-0700)"
    liveIcon:
      activeImg: https://cdn.17app.co/f468efd6-3523-49b7-8989-911ee23b249f.png
      disabledImg: https://cdn.17app.co/679f9f7e-87d7-43ca-ae69-3bb403cd0262.png
    exploreIcon:
      activeImg: https://cdn.17app.co/8f79ac5c-c478-4fcc-858b-59b7479df517.png
      disabledImg: https://cdn.17app.co/94caa2fe-be3f-4e18-8a7e-05040934f0a5.png
    feedIcon:
      activeImg: https://cdn.17app.co/40b445ef-acc8-43ba-ad37-2af74635b89b.png
      disabledImg: https://cdn.17app.co/c6fd21cf-6796-487c-82e1-fec58af19bee.png
    profileIcon:
      activeImg: https://cdn.17app.co/a1e6af91-955f-4902-9a41-38eb51716296.png
      disabledImg: https://cdn.17app.co/8a836e59-3c1f-4f52-a4bb-2c80deec26a9.png
    notificationsIconImg: https://cdn.17app.co/1a213b82-dcdc-4274-94fc-92efe9dec900.png
    leaderboardIconImg: https://cdn.17app.co/8736248b-e2af-4974-9f7d-c61a5e844383.png

  - startTime: "2023-04-03 00:00:00 (GMT-0700)" #2023 Easter
    endTime: "2023-04-11 00:00:00 (GMT-0700)"
    liveIcon:
      activeImg: https://cdn.17app.co/b773f8d9-52dc-4248-ba86-b9aa95b9bd0f.png
      disabledImg: https://cdn.17app.co/8b5fea59-6c1a-4ee0-948c-2d86fdbe4ee7.png
    exploreIcon:
      activeImg: https://cdn.17app.co/95db0edb-8de1-44c5-ae68-a5210cbcd0d0.png
      disabledImg: https://cdn.17app.co/c3346f47-4887-4bc5-87da-8f9cdff18671.png
    feedIcon:
      activeImg: https://cdn.17app.co/0937bc7c-4294-49a6-adb4-45cb2028c1bc.png
      disabledImg: https://cdn.17app.co/fad4db73-0d1c-466b-97d5-b30e1ab1c840.png
    profileIcon:
      activeImg: https://cdn.17app.co/9911822c-b6c3-4aea-b2a5-a9e005ec0639.png
      disabledImg: https://cdn.17app.co/ca74f090-e069-4cce-891a-4aba7d219de5.png
    notificationsIconImg: https://cdn.17app.co/48382a55-081d-48f3-87a6-d8fe103bf225.png
    leaderboardIconImg: https://cdn.17app.co/c97e3c3d-492e-405b-9fa4-41df90db8bee.png

  - startTime: "2023-04-11 00:00:00 (GMT-0700)" #Bestia 4/11 - 4/30
    endTime: "2023-05-01 00:00:00 (GMT-0700)"
    liveIcon:
      activeImg: https://cdn.17app.co/2c7f6a09-1f45-429b-807d-5e5c8c35ac46.png
      disabledImg: https://cdn.17app.co/a2c88a98-b51f-4878-b7eb-8f070d7a699b.png
    exploreIcon:
      activeImg: https://cdn.17app.co/d3ecbcee-8b57-4a89-9e5c-fa5811d73f9f.png
      disabledImg: https://cdn.17app.co/e65155e9-5f55-4255-9bce-fbaf8a83a1fd.png
    feedIcon:
      activeImg: https://cdn.17app.co/4af5dcae-54dd-4935-804e-2dbc5e0d7817.png
      disabledImg: https://cdn.17app.co/8cc59b1a-5222-4032-847f-949c5bd9d472.png
    profileIcon:
      activeImg: https://cdn.17app.co/ee840f21-b51c-4658-b5c3-615b10fee64c.png
      disabledImg: https://cdn.17app.co/d9247a89-a65a-4f56-8120-fb5c5a3c16f9.png
    notificationsIconImg: https://cdn.17app.co/ec974599-82ba-48af-a06f-c0af35e33def.png
    leaderboardIconImg: https://cdn.17app.co/c287dcba-60b7-45fd-9bf8-e2e1c665bf67.png