enable: false
leaderboardCount: 31 # index bug in superstar
settleThreshold: 01m30s
hourLeaderboardDurations:
- start_time: 21h05m00s
  end_time: 24h00m00s
  startTime: 21h05m00s
  endTime: 24h00m00s
- start_time: 00h00m00s
  end_time: 20h05m00s
  startTime: 00h00m00s
  endTime: 20h05m00s
hotSetting: # Position is 1 based indexing
  maxRankInHot: 10 # Indicate how many top x stars should be put on hot
  newStarsHotPos: [3]
  superStarsHotPos: [1, 4]
systemRedenvelopeID: "redenvelope_no_superstar_HK"
pkStarRedenvelopeID: "redenvelope_no_superstar"
enableFilterHotStreamForNewStar: false
new_stars:
- id: 0
  redenvelopeReward: 10
- id: 1
  redenvelopeReward: 5
- id: 2
  redenvelopeReward: 5
- id: 3
  redenvelopeReward: 5
- id: 4
  redenvelopeReward: 5
super_stars:
- id: 0
  redenvelopeReward: 10
- id: 1
  redenvelopeReward: 5
- id: 2
  redenvelopeReward: 5
- id: 3
  redenvelopeReward: 5
- id: 4
  redenvelopeReward: 5

pk_stars:
- id: 0
  redenvelopeReward: 10
- id: 1
  redenvelopeReward: 6
- id: 2
  redenvelopeReward: 6
- id: 3
  redenvelopeReward: 6
- id: 4
  redenvelopeReward: 6
- id: 5
  redenvelopeReward: 6
- id: 6
  redenvelopeReward: 6
- id: 7
  redenvelopeReward: 6
- id: 8
  redenvelopeReward: 6
- id: 9
  redenvelopeReward: 6
