# region_mode are defined as following
# - 1: ALL
# - 2: INCLUDE
# - 3: EXCLUDE
# theme are defined as following
# - 1: normal
# - 2: chinese new year 2018
# - 3: system reward
# type are definded as following
# - 1: normal
# - 2: custom
# - 3: system
# - 4: recommend
region_mode: 3
regions: ['US']
countdown_time: 60 # deprecated
event_time: 10 # for display in notice only
creation_by_streamer: false
custom_min_point: 1000
custom_max_point: 99999999
customized_ios_support_version: 2.38
customized_android_support_version: 2.2.95
recommend_ios_support_version: 3.0.0
recommend_android_support_version: 2.3.10
customized_dirty_name: I LOVE 17
whiteListUserIDs:
 - "e3c4c804-8a9c-4b7c-8026-0a8ed602b42c"
redenvelopes:
- id: redenvelope_no_superstar
  img_URL: http://cdn.17app.co/a30cf4a7-9867-4a4c-9acc-a808ed14f3c5.png
  name_token: redenvelope_system_bonus
  point: 666
  min_point: 666
  max_point: 666
  announceable: false
  announce_threshold: -171717
  countdown_time: 150
  event_time: 10
  fee: 350
  theme: 3
  type: 3
  is_offline: false
  region_mode: 2
  regions: ["TW"]
  package_list:
    - amount: 1
      point: 89
    - amount: 1
      point: 44
    - amount: 1
      point: 33
    - amount: 3
      point: 5
    - amount: 5
      point: 3
    - amount: 120
      point: 1
- id: redenvelope_no_superstar_HK
  img_URL: http://cdn.17app.co/a30cf4a7-9867-4a4c-9acc-a808ed14f3c5.png
  name_token: redenvelope_system_bonus
  point: 288
  min_point: 288
  max_point: 288
  announceable: false
  announce_threshold: -171717
  countdown_time: 150
  event_time: 10
  fee: 0
  theme: 3
  type: 3
  is_offline: false
  region_mode: 2
  regions: ["HK"]
  package_list:
    - amount: 1
      point: 89
    - amount: 1
      point: 16
    - amount: 1
      point: 10
    - amount: 2
      point: 8
    - amount: 3
      point: 7
    - amount: 5
      point: 6
    - amount: 8
      point: 4
    - amount: 15
      point: 2
    - amount: 44
      point: 1
- id: redenvelope_no_recommend
  img_URL: http://cdn.17app.co/8d27f90a-3419-4bc4-af6a-3b6a462e5aad.png
  name_token: red_envelope_promote_name
  point: 5000
  announceable: false
  announce_threshold: -171717
  countdown_time: 30
  event_time: 10
  fee: 250
  theme: 1
  type: 4
  is_offline: false
  region_mode: 2
  regions: ["TW"]
  package_list:
    - amount: 1
      point: 500
    - amount: 1
      point: 325
    - amount: 1
      point: 250
    - amount: 2
      point: 175
    - amount: 3
      point: 125
    - amount: 5
      point: 100
    - amount: 8
      point: 75
    - amount: 15
      point: 50
    - amount: 44
      point: 25
- id: redenvelope_no_custom
  img_URL: http://cdn.17app.co/203fb9b5-9d97-4b15-bcdf-2dcb2cc76b1a.png
  name_token: redenvelope_customize_name
  point: 0 # unchangeable
  min_point: 1000
  max_point: 9999999
  announceable: true
  announce_threshold: 88888
  countdown_time: 60
  event_time: 10
  fee: 50 # workaround, it is percentage * 10
  theme: 1
  type: 2
  is_offline: false
  region_mode: 2
  regions: ['TW']
  package_list:
    - amount: 1
      point: 100 # workaround, it is percentage * 10
    - amount: 1
      point: 65
    - amount: 1
      point: 50
    - amount: 2
      point: 35
    - amount: 3
      point: 25
    - amount: 5
      point: 20
    - amount: 8
      point: 15
    - amount: 15
      point: 10
    - amount: 44
      point: 5
- id: cny_redenvelope_no_1
  img_URL: http://cdn.17app.co/adcebea8-85ce-4e70-ac5e-7539e3da43cc.png
  name_token: cny_redenvelope_no_1
  point: 1888888
  announceable: true
  announce_threshold: -171717
  countdown_time: 60
  event_time: 10
  fee: 94444
  theme: 2
  type: 1
  is_offline: false
  region_mode: 2
  regions: ["TW", "HK", "SG", "MY"]
  package_list:
    - amount: 1
      point: 18888
    - amount: 1
      point: 12000
    - amount: 1
      point: 7473
    - amount: 146
      point: 5373
    - amount: 199
      point: 3375
    - amount: 200
      point: 1500
- id: cny_redenvelope_no_2
  img_URL: http://cdn.17app.co/6d431729-c43c-4ba4-963f-ccab88cd0b78.png
  name_token: cny_redenvelope_no_2
  point: 188888
  announceable: true
  announce_threshold: -171717
  countdown_time: 30
  event_time: 10
  fee: 9444
  theme: 2
  type: 1
  is_offline: false
  region_mode: 2
  regions: ["TW", "HK", "SG", "MY"]
  package_list:
    - amount: 1
      point: 2020
    - amount: 1
      point: 1486
    - amount: 1
      point: 1218
    - amount: 130
      point: 650
    - amount: 170
      point: 400
    - amount: 101
      point: 220
- id: cny_redenvelope_no_3
  img_URL: http://cdn.17app.co/2d8b4063-0ef1-4bb8-b663-474e82b64789.png
  name_token: cny_redenvelope_no_3
  point: 18888
  announceable: false
  announce_threshold: -171717
  countdown_time: 30
  event_time: 10
  fee: 944
  theme: 2
  type: 1
  is_offline: false
  region_mode: 2
  regions: ["TW", "HK", "SG", "MY"]
  package_list:
    - amount: 1
      point: 500
    - amount: 1
      point: 304
    - amount: 1
      point: 188
    - amount: 32
      point: 136
    - amount: 126
      point: 100
- id: cny_redenvelope_no_4
  img_URL: http://cdn.17app.co/5e43b968-713e-44ff-ad8d-90e31f6000e6.png
  name_token: cny_redenvelope_no_4
  point: 1888
  announceable: false
  announce_threshold: -171717
  countdown_time: 30
  event_time: 10
  fee: 94
  theme: 2
  type: 1
  is_offline: false
  region_mode: 2
  regions: ["TW", "HK", "SG", "MY"]
  package_list:
    - amount: 1
      point: 199
    - amount: 1
      point: 158
    - amount: 1
      point: 137
    - amount: 13
      point: 100
- id: redenvelope_no_1
  img_URL: http://cdn.17app.co/fb3bd824-1f79-4e9d-bc7d-9fcc7c3dc4f1.png
  name_token: redenvelope_name_no_1
  point: 888888
  announceable: true
  announce_threshold: -171717
  countdown_time: 60
  event_time: 10
  fee: 44444
  theme: 1
  type: 1
  is_offline: false
  region_mode: 3
  regions: ['US']
  package_list:
    - amount: 1
      point: 8888
    - amount: 1
      point: 6000
    - amount: 1
      point: 3932
    - amount: 145
      point: 2688
    - amount: 153
      point: 1688
    - amount: 200
      point: 888
- id: redenvelope_no_2
  img_URL: http://cdn.17app.co/970fe736-1bb5-4bd2-9041-a0f14e057278.png
  name_token: redenvelope_name_no_2
  point: 88888
  announceable: true
  announce_threshold: -171717
  countdown_time: 30
  event_time: 10
  fee: 4444
  theme: 1
  type: 1
  is_offline: false
  region_mode: 3
  regions: ['US']
  package_list:
    - amount: 1
      point: 1010
    - amount: 1
      point: 743
    - amount: 1
      point: 616
    - amount: 151
      point: 325
    - amount: 165
      point: 200
- id: redenvelope_no_3
  img_URL: http://cdn.17app.co/7d0fd036-3869-42a7-9168-057388f9e232.png
  name_token: redenvelope_name_no_3
  point: 8888
  announceable: false
  announce_threshold: -171717
  countdown_time: 30
  event_time: 10
  fee: 444
  theme: 1
  type: 1
  is_offline: false
  region_mode: 3
  regions: ['US']
  package_list:
    - amount: 1
      point: 241
    - amount: 1
      point: 140
    - amount: 1
      point: 99
    - amount: 32
      point: 77
    - amount: 110
      point: 50
- id: redenvelope_no_4
  img_URL: http://cdn.17app.co/a30cf4a7-9867-4a4c-9acc-a808ed14f3c5.png
  name_token: redenvelope_name_no_4
  point: 888
  announceable: false
  announce_threshold: -171717
  countdown_time: 30
  event_time: 10
  fee: 44
  theme: 1
  type: 1
  is_offline: false
  region_mode: 3
  regions: ['US']
  package_list:
    - amount: 1
      point: 102
    - amount: 1
      point: 74
    - amount: 1
      point: 68
    - amount: 12
      point: 50
