# # example
#
# tag_streamer_recommendation_settings:
#   - id: chat
#     recommend_ids_for_male:
#       - 4ccb789d-4059-41cf-9505-b820579c2b48 # èŒƒå°å§
#       - ac021f94-9501-47eb-a7ba-1f626736ec96 # Sandyyyyyyyy
#     recommend_ids_for_female:
#       - cb46a35f-0ae6-487c-aad3-ea3ff5b8c838 # å¾®ç¬‘æ™´å¤©
#       - 6443a434-4e3c-47c9-b59a-6f408a51e144 # æ´›Â·å…‹

tag_streamer_recommendation_settings:
  - id: chat
    recommend_ids_for_male:
    - 5bd69b10-a6b2-4241-b175-0782596fd706 # ç¨€éŸ³
    - b5ec2f6b-cfd0-4305-bdc8-6f7f171a1672 # 08isbear
    - 26c7a01e-08b9-4656-9b44-37c1b559180a # Reneeâ€ ///è‰¾ç³
    - 5684f18a-ca11-4511-a8c7-8fbd411e2ba8 # åªæœƒå”±æ­Œçš„ç¾Šå’©
    - 440f242e-320b-4d65-93df-c2fec7d51da3 # è‹¥æœ‰å¤¢
    - dd83f2ba-c373-4ddb-94a3-529cd6219c1f # 3am.la
    - 767f272b-ac4c-49c8-9eb8-1ceda7836b2e # ç±³è²å©­.KemythiağŸŒ¹
    - 6fe47d40-4397-4480-8536-1b556f19edf6 # RaynağŸ¹ğŸ¤
    - 82bc16e7-ff6a-47a5-9c50-ede1d1c4bf00 # Jasmineä¸¹ä¸¹
    - a6290fe5-3c37-4185-8d63-b66e8647732a # å­Ÿå›NATSUME
    - 72a9058c-6385-4456-863f-a7913fea909e # ç†Šç†ŠğŸ§¸
    - d3c44590-8c9a-4ee1-b005-eb011806c588 # *Universe*
    - d736c541-fefb-4328-908f-4a05310c785e # éœéœğŸ’‹
    - 9e42c09b-6eaa-4713-8928-2de4546de274 # è‰æLiLee
    - 57f9189d-4193-4ed7-872d-95b8983cea62 # æ˜•å¯¶å¨˜å¨˜ğŸ¦ŠğŸ‘‘
    - 6d447b67-563a-44c8-bde2-9bd5809f88b9 # å§œå§œAphroditeğŸ’«
    - a6445265-4580-4751-b86e-cc1c017a78df # é˜¿ç·¹
    - c1cd69a1-0d61-42d8-b8ca-9c8e15633b4f # XiNaâ†»
    - 4ccb789d-4059-41cf-9505-b820579c2b48 # èŒƒå°å§
    - e1795b61-1cea-4fa0-8015-f029a93b6319 # Amberlyn
    - e159354e-ae76-4481-8171-73dd9d06d335 # Kerryé§èŠ®ğŸ’«
    - 4b3866a0-ca9c-484c-9515-d07897f10af0 # å°ç« é­šå…’
    - 9ff1d605-edf2-49a9-b34f-e77f73245e72 # å“‡å¡å¡
    - 70af911e-f54f-4a64-ad88-e5dbf392f592 # åƒå¿«ä¸€é»
    - 30b6a32b-33df-471f-be42-eaecf9fa487f # æ²æ²ç‘¤
    - 2a9b0ff1-581d-4cec-a24a-178a6cb1c665 # å°æ¬£cindy
    - 7160c5eb-6343-4696-834a-33bae98bf91e # ç±³å®£
    - 5e3af964-9129-42c5-a8ed-90e363c8b39e # æå¤©å¤©
    - fa0ff7fd-10d1-4a3c-897e-32d36c6ccb28 # è‰¾ç‘ªEmmağŸ’«
    - de588428-b08b-4bdb-a9e1-c4486e37e60d # â˜€ï¸æš–æš–ğŸŒ™ğŸ¤
    - 9ccc045f-2b42-44a3-9000-6ddc060280f7 # èœè€å¸«ğŸµ
    - 4f9420ad-2bdc-4228-93bd-7e02ee039758 # å¯§å¯§ğŸ­ğŸ’•
    - a056d951-4628-49e2-bb58-30323421d217 # æ°´æœå§å§
    - 7734d06e-36c7-4a15-9ec0-f2c4f992f8d3 # æ…ˆæ…ˆğŸ¥„â¤ï¸ğŸ¶
    - eecc1148-e267-4eb4-a7e2-7e8cb6bb0670 # å°è­·å£«â˜ï¸
    - 19f77cbc-7609-448d-919d-6849d4b3981b # åš•åš•*
    - fc6af966-6e1c-43bd-aceb-eb84a61037f6 # ğŸ†ƒğŸ…²å°å¤¢å¤¢â¤ï¸
    - aabf4dcd-2f2e-4e5c-9308-91b967977cad # ğŸ†ƒğŸ…²ğŸ’™ç¶­å¨œ
    - 65531ba9-d10c-40c4-b802-ee4e42a3ead7 # ç‹ç‹¸è²
    - 3112db4a-8a1c-42fe-affa-00e0dd1e513b # Jasmine.*ä½³æ€æ˜ğŸ¯
    - 63988abe-8570-40cc-974c-c3a0d0244e40 # å°å­«ğ“¢ğ“¾ğ“·ğŸ¤
    - 08e16280-9c47-456a-bb1c-b3b5f0ae06b3 # VivianğŸŒŸæ¶µæ¶µ
    - 7bbb697f-70aa-4bd1-9c95-5c2d6fa4f01a # å”±æ­Œçš„å›æ†¶
    - 216cec86-dd27-48af-b8c7-7ba57c18a667 # Claireæ©é›ªğŸ’•

    recommend_ids_for_female:
    - 5150cc3c-baa5-48a3-86b4-f3494b9a414e # BANJI
    - 69c26d00-79b3-4ce6-9d8a-81df95e292a2 # á´¡ÊœÉªá´›á´‡æ‡·ç‰¹
    - 5265b2c9-5046-4950-8b31-69969ae0c230 # ğ“¡Â·ä¸¸
    - f2111e29-1151-45d9-848e-197b341f1add # ç©å…·à² _à² 
    - f3821b6b-a8ff-49f9-860f-4328179a7d32 # luwa
    - 48b5437d-7613-4b01-a284-036e1a6c3d1b # Oleç ´
    - 6443a434-4e3c-47c9-b59a-6f408a51e144 # æ´›Â·å…‹
    - 8a1190db-9fc4-42d6-a8b9-6ac82212410e # á´€sÊœá´‡é˜¿å°„
    - 955ae13c-be83-4e0a-9b9f-4f47c2c1ae66 # ä¸ƒæ˜Ÿè¶…æ·¡_
    - 95145564-d524-4b48-a94f-f649ff099b60 # æªæªæ¡‘å‰äººä¹Ÿ
    - 16953a02-fde7-4f3b-bce2-d252723e2557 # å–œæ­¡å”±æ­Œçš„å°é£›
    - f09db2f9-a13b-45c1-881f-d4150b132b1c # ä¸‹ç­çš„æ™®é€šä¸Šç­æ—Jams
    - cb46a35f-0ae6-487c-aad3-ea3ff5b8c838 # å¾®ç¬‘æ™´å¤©
    - 96949ac0-62ca-469d-b7cf-a40206952060 # å¾·å¾·RyderğŸ·
    - 7a14c76f-576c-4002-befb-8cad59fcb057 # å°å¯†ç¾ŠğŸğŸ¤âœ¨
    - d758ad2c-c302-4fb6-b535-d9e7ab7810f1 # Darren(é”å€«)
    - f810513a-39af-49fe-885e-169b3b41eb83 # ç‘é–€
    - 7d0b5796-93c3-4447-a34e-f28901eed2e7 # VvnğŸ‘»
    - a6265e99-3a0d-467b-8f7b-3dfbabef2054 # å°è¨€â™£ï¸
    - f1e7d3bc-00ad-40fd-bcbc-fd1c00d480ef # å°æŸ’_
    - c67ea0d3-4852-4958-9d26-d91f88c812d7 # å‚¾è½æ¨ºèª
    - b5784c30-0e78-43c5-8bcc-149967db7910 # ğŸ†ƒğŸ…²é…¥é…¥ğŸª
    - adc2a5f4-a97c-4369-af14-568dfad535a5 # ğŸ†ƒğŸ…²è‰¾å€«ğŸ§»
    - 7537eccc-62a3-4bd0-8e8e-d4bada1fa2b4 # ğŸ†ƒğŸ…²èŠ±æ·š
    - 019950e7-f4e0-45e5-87f1-0b3e600aab09 # ğŸ†ƒğŸ…²å°é½Š
    - 35f0b0c2-6e79-4d95-8d78-2ba352e1d506 # ğŸ†ƒğŸ…²ç‚­çƒ¤å¹¸ç¦é˜¿æ°‘
    - 2eaecad7-1fb9-41a3-9460-e43a1dedcc82 # ğŸ†ƒğŸ…²å°çŒ´ğŸŒ¿
    - 11f4a2df-c804-4edd-a5b7-e4af5c5c298e # é™³æ–¯æ©

  - id: singing
    recommend_ids_for_male:
    - d5e6d458-1853-464d-abd6-eff9604a8fb7 # æ­è‰OrliğŸ”†
    - d045f83a-13bf-4fcc-8e92-8b1c6d414c5f # Lana.CCğŸ°ğŸ“
    - f2832bcf-10fa-402d-a971-4f7250876ff5 # æœˆç’ƒğŸŒ¹
    - 992548da-705d-49f0-be12-7b7c06c1f3fc # æŸšå¸ŒYoshiğŸ’•
    - 1c16ba16-a5e3-45e5-9dc3-bfb80bb12b4b # æ™¨æ™¨
    - 67912a65-6ddd-42a9-9643-c33b370c3ccf # è‚‰çµ²RoseğŸŒ¹
    - b3d55407-2cd7-4bfe-b479-dd3c9742e625 # å‡±å¸ŒğŸ¿ï¸
    - 43e3a52d-e2b4-40a8-bc29-0526676b000f # momoå°å­ŸğŸ±
    - c96b5482-25a3-4a54-96f6-5e08c25a64c5 # CCğŸ‹å¯§èŒ
    - cbba63e7-05eb-46f4-81c6-de3ebcef3556 # æ©‹ä¸Šæœ‰ä¸€éš»æœ«æœ«ğŸ
    - 8e1a23d3-6f30-4e78-8564-8ce966647a62 # é€™è£¡æ˜¯æ˜•æ˜•
    - ac021f94-9501-47eb-a7ba-1f626736ec96 # Sandyyyyyyyy
    - 8524faee-b204-4dac-a663-a16c5cbf4726 # hebeç”œ
    - 623188a3-3d65-4221-925d-f2fda7a7f4c9 # ğŸŒºå±±èŒ¶ğŸŒº
    - 021b2d01-c02b-4f70-971e-b33a5601f3eb # èŠ±å¨˜ğ“¯ğ“µğ“¸ğ”€ğ“®ğ“»
    recommend_ids_for_female:

  - id: daily
    recommend_ids_for_male:
    recommend_ids_for_female:
