# # example
#
# tag_streamer_recommendation_settings:
#   - id: chat
#     recommend_ids_for_male:
#       - 4ccb789d-4059-41cf-9505-b820579c2b48 # èŒƒå°å§
#       - ac021f94-9501-47eb-a7ba-1f626736ec96 # Sandyyyyyyyy
#     recommend_ids_for_female:
#       - cb46a35f-0ae6-487c-aad3-ea3ff5b8c838 # å¾®ç¬‘æ™´å¤©
#       - 6443a434-4e3c-47c9-b59a-6f408a51e144 # æ´›Â·å…‹

tag_streamer_recommendation_settings:
  - id: singing
    recommend_ids_for_male:
    - 5bd69b10-a6b2-4241-b175-0782596fd706 # ç¨€éŸ³
    - b5ec2f6b-cfd0-4305-bdc8-6f7f171a1672 # 08isbear
    - 26c7a01e-08b9-4656-9b44-37c1b559180a # Reneeâ€ ///è‰¾ç³
    - 767f272b-ac4c-49c8-9eb8-1ceda7836b2e # ç±³è²å©­.KemythiağŸŒ¹
    - 9e42c09b-6eaa-4713-8928-2de4546de274 # è‰æLiLee
    - 4ccb789d-4059-41cf-9505-b820579c2b48 # èŒƒå°å§
    - 9ff1d605-edf2-49a9-b34f-e77f73245e72 # å“‡å¡å¡
    - 30b6a32b-33df-471f-be42-eaecf9fa487f # æ²æ²ç‘¤
    - 5e3af964-9129-42c5-a8ed-90e363c8b39e # æå¤©å¤©
    - fa0ff7fd-10d1-4a3c-897e-32d36c6ccb28 # æ±ŸèŠ¯ğŸ’
    - 7734d06e-36c7-4a15-9ec0-f2c4f992f8d3 # æ…ˆæ…ˆğŸ¥„â¤ï¸ğŸ¶
    - 3112db4a-8a1c-42fe-affa-00e0dd1e513b # Jasmine.*ä½³æ€æ˜ğŸ¯
    - 63988abe-8570-40cc-974c-c3a0d0244e40 # å°å­«ğ“¢ğ“¾ğ“·ğŸ¤
    - 75299eb1-935d-4765-9725-8837c2adc191 # å°è¢ç«ğŸ¦‹ğŸ¤
    - d337236b-5ebe-4327-af95-ee9435268afe # ğŸŒ¼å…œè‰ğŸŒ¼
    - 9d7ef4d9-c6ce-409e-b2d8-945a63ec737c # éœ²å¨œğŸŒ™Luna
    - cbab1779-2a8f-43a0-b6e5-13e9233bfe07 # EraserğŸ¤¡çš®çš®
    - 9ff1d605-edf2-49a9-b34f-e77f73245e72 # å“‡å¡å¡
    - aef781e7-a306-46cc-b71d-c8a4764cb018 # å°å®‰_Annn
    - aba3742f-78a4-472b-b741-f355d40edd78 # ç¹ç±³èŒ¶
    - 99304123-c5d3-4caf-9703-5c2e915641ee # èŠ¯èªâ˜•ğŸ¶
    - 23df4032-6dee-4958-b22e-8d78210b9c2a # å°é»‘å¤§è‡‰éŸ³æ¨‚penny
    - a6caf9e3-9ad3-4177-8158-312dd2e6b19b # é¦™çµ²
    - 9d12c1df-c79e-494b-a21b-46a3d4d883fd # é¡é ­
    - b9bae46f-ed2b-4c3c-8c5e-825418d2a78f # -æ­ªæ­ª-
    - 0338e6c9-aa3a-4453-915e-020997870527 # ğŸ§¸å°ç†Šä¸å–æ°´ğŸ¥›
    - 859e487a-9b59-4a99-80a9-d4484d10f6f9 # My.å°è¿·ç³Šè•¾è•¾â˜ºï¸â˜»
    - 71eff6e9-6662-4e68-a62f-05263b698f5a # å°æ¡ƒæ°£ğŸ‘Eva
    - ae912238-e86b-4409-a236-18681cf0f5b3 # èŠéº»å§‘å¨˜ğŸ–¤
    - 055031e3-e8f5-4b6e-b493-ab5e671dc15d # å°èŠ±ğ–¡¼.ğ–¤£ğ–¥§
    - 75b3088f-1a22-4256-b530-c41272e7af8e # å¯æ‘Ÿä»¥â„‚ğ•™ğ•ğ• ğ•–ğŸ’«
    - eef3fd3e-ac7b-49c9-bb1f-c3e60a5c7bb7 # BonnieğŸ§å¹«é‚¦å¦®
    - 58a1766f-7702-4dd9-9503-b449a90fed04 # yumiË 
    - 4f9420ad-2bdc-4228-93bd-7e02ee039758 # æŠ±èµ°å¯§å¯§
    - 7bb90150-d286-4944-9a1c-f9ab7c32e1ac # oè‰¾è–‡o

    recommend_ids_for_female:
    - 5150cc3c-baa5-48a3-86b4-f3494b9a414e # BANJI
    - 69c26d00-79b3-4ce6-9d8a-81df95e292a2 # á´¡ÊœÉªá´›á´‡æ‡·ç‰¹
    - 5265b2c9-5046-4950-8b31-69969ae0c230 # ğ“¡Â·ä¸¸
    - 6443a434-4e3c-47c9-b59a-6f408a51e144 # æ´›Â·å…‹
    - 7a14c76f-576c-4002-befb-8cad59fcb057 # å°å¯†ç¾ŠğŸğŸ¤âœ¨
    - b5784c30-0e78-43c5-8bcc-149967db7910 # é…¥é…¥ğŸª
    - 7e3c319d-a589-4953-8e96-1d24a0e22b51 # è‰¾è¿ªå ¤å‚‘â™«
    - 27911e82-9d35-4e3e-866d-3dce5c739afe # å¥¶å­å»Ÿå»Ÿå…¬
    - 220e89ed-330e-4b7b-a6e2-11a61636aa77 # å†·å†·å¿ƒä¸Šäºº
    - b9ab581c-34c2-4a40-b213-de5b170883c0 # GUIğŸ¢
    - 494a617a-9793-4d8c-9750-8fe42368b164 # VCå°å§œ
    - 30e5bf5b-ddb1-41d7-9de7-6054db3b5453 # æ¤°å£³soul
    - 98087126-d226-4d5c-a487-451538883df5 # Ê€Éªá´„á´‹Êà½¼
    - f448dc62-08d2-4954-84ce-96959c1a4a1d # ä¸Šå¿ƒğŸ™
    - 2bae0757-04e8-4701-8a35-01d602b93cc7 # ğŸ¼ğŸ¸å½ˆå”±MarkğŸ¸ğŸ¤
    - 56f880a8-a75d-4eb0-8372-89078bdd998f # å–µå‰
    - f7df5f78-8817-47b4-924f-035b12fa042b # æ£‹é£›
    - 75bf28dc-8537-4894-ab20-5a1a9ddac834 # ç±³å‹’å…ˆç”Ÿ
    - e1eb9635-13cb-4765-bf0c-6a4d3865c9ee # ç§‹å…ˆç”Ÿâ™’ï¸
    - eef3e10b-d897-436a-9ed0-3c4100ebae48 # Vçˆ¾æ£®

  - id: chat
    recommend_ids_for_male:
    - d045f83a-13bf-4fcc-8e92-8b1c6d414c5f # Lana.CCğŸ°ğŸ“
    - f2832bcf-10fa-402d-a971-4f7250876ff5 # æœˆç’ƒğŸŒ¹
    - cbba63e7-05eb-46f4-81c6-de3ebcef3556 # æ©‹ä¸Šæœ‰ä¸€éš»æœ«æœ«ğŸ
    - 8e1a23d3-6f30-4e78-8564-8ce966647a62 # é€™è£¡æ˜¯æ˜•æ˜•
    - 747246f0-680e-4860-9dae-b3bfb4139418 # å®‰ç„¶ã‚œğ“ªğ“·ğŸ¦‰
    - 8c8b5008-a3ce-4298-97ba-feb2bddf172e # å·å¿ƒè²è²â™¥ï¸
    - 61ef9fa3-7c6b-43d5-8569-12a50e7440ff # å¤©å…²
    - 5b0f9575-cbf6-4ec5-aab9-c61eecf61eab # å¥¶èŒ¶è¦åŠ ç³–
    - 0f7d76e6-ba96-44ae-8bdb-68a67ee5d95f # ğŸŒ™æœˆå…‰ä»™ä»™âœ¨
    - 26c58ec5-5736-44b6-8816-d295c41e1fe4 # ç­±è¶èˆ
    - 652b45d8-5f02-481c-a0d2-a14567f22a19 # æ‹‰ç†Š
    - 54198bef-ee07-426c-90ef-41f7101a7315 # è±ªçˆ½äººå¦»
    - a0d20512-e134-4c72-8826-2f680316da54 # è½‰å•Šè½‰å•Šè½‰âœ¨
    - 91b3779c-d990-49ea-b7fe-fff397241bdc # å“ˆå¨œæ²’æœ‰è‚¥è‚šå­
    - e159354e-ae76-4481-8171-73dd9d06d335 # Kerryé§èŠ®ğŸ’«
    - 3dfc4067-5286-4a03-9df4-be3b94d750af # ğŸŒ¹ğŸŒ¼AliceğŸŒ¼ğŸŒ¹
    - de5a8d5b-76c8-43fb-92fa-803d709b3f3a # FÃ¼è¶
    - 871f7fa9-15dc-4ff8-a1b5-f38cbf883da4 # Yunjuå°å¦‚
    - 262f470a-4514-49af-bb72-9dfbf8d31f03 # ç¥ä»™é­š
    - bda7c412-e218-4999-bd93-6ad60614561d # Myco
    - 75b3088f-1a22-4256-b530-c41272e7af8e # å¯æ‘Ÿä»¥â„‚ğ•™ğ•ğ• ğ•–ğŸ’«
    - 4cdd2e9b-9192-4f1f-bdb0-13301003362e # ğŸŒ¹å¨œå¨œè‹¥èŠ³ğŸŒ¹
    - 64880b32-bd5a-4444-aa21-5a5909af36ef # æ°åŒ—åŒ—ã€†Yuié†¬
    - 71eff6e9-6662-4e68-a62f-05263b698f5a # å°æ¡ƒæ°£ğŸ‘Eva
    - 7ea0226d-1da7-4d29-9649-eec410b5cfd1 # æµ·è‰è—»
    - 055031e3-e8f5-4b6e-b493-ab5e671dc15d # å°èŠ±ğ–¡¼.ğ–¤£ğ–¥§
    - 0426009a-7f93-495f-8845-df5ba908089f # drawdrawå“å“ğŸ¨*ï½¥ã‚œï¾Ÿï½¥*Â·Â·
    - 365d01e0-b425-4d4c-94a3-48e8681911cd # å„å„
    - ae912238-e86b-4409-a236-18681cf0f5b3 # èŠéº»å§‘å¨˜ğŸ–¤
    - 58a1766f-7702-4dd9-9503-b449a90fed04 # yumiË 
    - 8f6b7a86-1694-490d-b9f6-9eb7a49f6550 # Watts_MailerğŸ‰ğŸ‰
    - 7bb90150-d286-4944-9a1c-f9ab7c32e1ac # oè‰¾è–‡o

    recommend_ids_for_female:
    - 6e304d69-0c33-4028-ac9a-47cd39c5729b # æ‰é‚Š
    - eda5b79a-9d8d-429b-bb2c-74205750df2a # âœ¨DALEæˆ´çˆ¾ğŸ’„ğŸ¤âœ¨
    - 27911e82-9d35-4e3e-866d-3dce5c739afe # å¥¶å­å»Ÿå»Ÿå…¬
    - 100ba908-2857-4276-9a75-8b119b5402dd # EricğŸ©
    - e53e410c-5105-4c03-99a4-14a03ebefb57 # å°é¬¼æ ¼æ ¼ğŸ‘»
    - eef3e10b-d897-436a-9ed0-3c4100ebae48 # Vçˆ¾æ£®
    - b5784c30-0e78-43c5-8bcc-149967db7910 # é…¥é…¥ğŸª
    - dcbe4b26-247f-402a-ab66-f08996353e21 # ç¼ºè§’çš„åœ“
    - 368ec191-422a-4803-8c86-0bd80a335a25 # å…”å­æ…¢åŠæ‹
    - e1eb9635-13cb-4765-bf0c-6a4d3865c9ee # ç§‹å…ˆç”Ÿâ™’ï¸
    - 5150cc3c-baa5-48a3-86b4-f3494b9a414e # BANJI
    - 8f6b7a86-1694-490d-b9f6-9eb7a49f6550 # Watts_MailerğŸ‰ğŸ‰

  - id: daily
    recommend_ids_for_male:
    - 4f932b63-55ae-4021-b4bc-e06fb6040e73 # Twinkle_
    - 4a6ba1e3-7d1c-4314-b0e2-e309584bd927 # Waffle:)
    - 35838143-b648-409c-8da6-efa6fe63a2fb # å¥ˆçˆ¾
    - 368ec191-422a-4803-8c86-0bd80a335a25 # å…”å­æ…¢åŠæ‹
    - 859e487a-9b59-4a99-80a9-d4484d10f6f9 # My.å°è¿·ç³Šè•¾è•¾â˜ºï¸â˜»
    - 58a1766f-7702-4dd9-9503-b449a90fed04 # yumiË 
    recommend_ids_for_female:
    - e53e410c-5105-4c03-99a4-14a03ebefb57 # å°é¬¼æ ¼æ ¼ğŸ‘»
    - e1eb9635-13cb-4765-bf0c-6a4d3865c9ee # ç§‹å…ˆç”Ÿâ™’ï¸
    - eef3e10b-d897-436a-9ed0-3c4100ebae48 # Vçˆ¾æ£®
    - 98087126-d226-4d5c-a487-451538883df5 # Ê€Éªá´„á´‹Êà½¼
    - 5150cc3c-baa5-48a3-86b4-f3494b9a414e # BANJI
    - 6e304d69-0c33-4028-ac9a-47cd39c5729b # æ‰é‚Š
    - 27911e82-9d35-4e3e-866d-3dce5c739afe # å¥¶å­å»Ÿå»Ÿå…¬
    - 220e89ed-330e-4b7b-a6e2-11a61636aa77 # å†·å†·å¿ƒä¸Šäºº
    - 7e3c319d-a589-4953-8e96-1d24a0e22b51 # è‰¾è¿ªå ¤å‚‘â™«