# # example
#
# tag_streamer_recommendation_settings:
#   - id: chat
#     recommend_ids_for_male:
#       - 4ccb789d-4059-41cf-9505-b820579c2b48 # èŒƒå°å§
#       - ac021f94-9501-47eb-a7ba-1f626736ec96 # Sandyyyyyyyy
#     recommend_ids_for_female:
#       - cb46a35f-0ae6-487c-aad3-ea3ff5b8c838 # å¾®ç¬‘æ™´å¤©
#       - 6443a434-4e3c-47c9-b59a-6f408a51e144 # æ´›Â·å…‹

tag_streamer_recommendation_settings:
  - id: chat
    recommend_ids_for_male:
    - 5bd69b10-a6b2-4241-b175-0782596fd706 # ç¨€éŸ³
    - b5ec2f6b-cfd0-4305-bdc8-6f7f171a1672 # 08isbear
    - 26c7a01e-08b9-4656-9b44-37c1b559180a # Reneeâ€ ///è‰¾ç³
    - 5684f18a-ca11-4511-a8c7-8fbd411e2ba8 # åªæœƒå”±æ­Œçš„ç¾Šå’©
    - 440f242e-320b-4d65-93df-c2fec7d51da3 # è‹¥æœ‰å¤¢
    - dd83f2ba-c373-4ddb-94a3-529cd6219c1f # 3am.la
    - 767f272b-ac4c-49c8-9eb8-1ceda7836b2e # ç±³è²å©­.KemythiağŸŒ¹
    - 6fe47d40-4397-4480-8536-1b556f19edf6 # RaynağŸ¹ğŸ¤
    - 82bc16e7-ff6a-47a5-9c50-ede1d1c4bf00 # Jasmineä¸¹ä¸¹
    - a6290fe5-3c37-4185-8d63-b66e8647732a # å­Ÿå›NATSUME
    - 72a9058c-6385-4456-863f-a7913fea909e # ç†Šç†ŠğŸ§¸
    - d3c44590-8c9a-4ee1-b005-eb011806c588 # *Universe*
    - d736c541-fefb-4328-908f-4a05310c785e # éœéœğŸ’‹
    - 9e42c09b-6eaa-4713-8928-2de4546de274 # è‰æLiLee
    - 57f9189d-4193-4ed7-872d-95b8983cea62 # æ˜•å¯¶å¨˜å¨˜ğŸ¦ŠğŸ‘‘
    - 6d447b67-563a-44c8-bde2-9bd5809f88b9 # å§œå§œAphroditeğŸ’«
    - a6445265-4580-4751-b86e-cc1c017a78df # é˜¿ç·¹
    - c1cd69a1-0d61-42d8-b8ca-9c8e15633b4f # XiNaâ†»
    - 4ccb789d-4059-41cf-9505-b820579c2b48 # èŒƒå°å§
    - e1795b61-1cea-4fa0-8015-f029a93b6319 # Amberlyn
    - e159354e-ae76-4481-8171-73dd9d06d335 # Kerryé§èŠ®ğŸ’«
    - 4b3866a0-ca9c-484c-9515-d07897f10af0 # å°ç« é­šå…’
    - 9ff1d605-edf2-49a9-b34f-e77f73245e72 # å“‡å¡å¡
    - 70af911e-f54f-4a64-ad88-e5dbf392f592 # åƒå¿«ä¸€é»
    - 30b6a32b-33df-471f-be42-eaecf9fa487f # æ²æ²ç‘¤
    - 2a9b0ff1-581d-4cec-a24a-178a6cb1c665 # å°æ¬£cindy
    - 7160c5eb-6343-4696-834a-33bae98bf91e # ç±³å®£
    - 5e3af964-9129-42c5-a8ed-90e363c8b39e # æå¤©å¤©
    - fa0ff7fd-10d1-4a3c-897e-32d36c6ccb28 # è‰¾ç‘ªEmmağŸ’«
    - de588428-b08b-4bdb-a9e1-c4486e37e60d # â˜€ï¸æš–æš–ğŸŒ™ğŸ¤
    - 9ccc045f-2b42-44a3-9000-6ddc060280f7 # èœè€å¸«ğŸµ
    - 4f9420ad-2bdc-4228-93bd-7e02ee039758 # å¯§å¯§ğŸ­ğŸ’•
    - a056d951-4628-49e2-bb58-30323421d217 # æ°´æœå§å§
    - 7734d06e-36c7-4a15-9ec0-f2c4f992f8d3 # æ…ˆæ…ˆğŸ¥„â¤ï¸ğŸ¶
    - eecc1148-e267-4eb4-a7e2-7e8cb6bb0670 # å°è­·å£«â˜ï¸
    - 19f77cbc-7609-448d-919d-6849d4b3981b # åš•åš•*
    - fc6af966-6e1c-43bd-aceb-eb84a61037f6 # ğŸ†ƒğŸ…²å°å¤¢å¤¢â¤ï¸
    - aabf4dcd-2f2e-4e5c-9308-91b967977cad # ğŸ†ƒğŸ…²ğŸ’™ç¶­å¨œ
    - 65531ba9-d10c-40c4-b802-ee4e42a3ead7 # ç‹ç‹¸è²
    - 3112db4a-8a1c-42fe-affa-00e0dd1e513b # Jasmine.*ä½³æ€æ˜ğŸ¯
    - 63988abe-8570-40cc-974c-c3a0d0244e40 # å°å­«ğ“¢ğ“¾ğ“·ğŸ¤
    - 08e16280-9c47-456a-bb1c-b3b5f0ae06b3 # VivianğŸŒŸæ¶µæ¶µ
    - 7bbb697f-70aa-4bd1-9c95-5c2d6fa4f01a # å”±æ­Œçš„å›æ†¶
    - 216cec86-dd27-48af-b8c7-7ba57c18a667 # Claireæ©é›ªğŸ’•

    recommend_ids_for_female:

  - id: singing
    recommend_ids_for_male:
    recommend_ids_for_female:

  - id: daily
    recommend_ids_for_male:
    recommend_ids_for_female:
