# # example
#
# tag_streamer_recommendation_settings:
#   - id: chat
#     recommend_ids_for_male:
#       - 4ccb789d-4059-41cf-9505-b820579c2b48 # èŒƒå°å§
#       - ac021f94-9501-47eb-a7ba-1f626736ec96 # Sandyyyyyyyy
#     recommend_ids_for_female:
#       - cb46a35f-0ae6-487c-aad3-ea3ff5b8c838 # å¾®ç¬‘æ™´å¤©
#       - 6443a434-4e3c-47c9-b59a-6f408a51e144 # æ´›Â·å…‹

tag_streamer_recommendation_settings:
  - id: singing
    recommend_ids_for_male:
    - 5bd69b10-a6b2-4241-b175-0782596fd706 # ç¨€éŸ³
    - b5ec2f6b-cfd0-4305-bdc8-6f7f171a1672 # 08isbear
    - 26c7a01e-08b9-4656-9b44-37c1b559180a # Reneeâ€ ///è‰¾ç³
    - 5684f18a-ca11-4511-a8c7-8fbd411e2ba8 # åªæœƒå”±æ­Œçš„ç¾Šå’©
    - 440f242e-320b-4d65-93df-c2fec7d51da3 # è‹¥æœ‰å¤¢
    - dd83f2ba-c373-4ddb-94a3-529cd6219c1f # 3am.la
    - 767f272b-ac4c-49c8-9eb8-1ceda7836b2e # ç±³è²å©­.KemythiağŸŒ¹
    - 6fe47d40-4397-4480-8536-1b556f19edf6 # RaynağŸ¹ğŸ¤
    - 82bc16e7-ff6a-47a5-9c50-ede1d1c4bf00 # Jasmineä¸¹ä¸¹
    - a6290fe5-3c37-4185-8d63-b66e8647732a # å­Ÿå›NATSUME
    - 72a9058c-6385-4456-863f-a7913fea909e # ç†Šç†ŠğŸ§¸
    - d3c44590-8c9a-4ee1-b005-eb011806c588 # *Universe*
    - d736c541-fefb-4328-908f-4a05310c785e # éœéœğŸ’‹
    - 9e42c09b-6eaa-4713-8928-2de4546de274 # è‰æLiLee
    - 57f9189d-4193-4ed7-872d-95b8983cea62 # æ˜•å¯¶å¨˜å¨˜ğŸ¦ŠğŸ‘‘
    - 6d447b67-563a-44c8-bde2-9bd5809f88b9 # å§œå§œAphroditeğŸ’«
    - a6445265-4580-4751-b86e-cc1c017a78df # é˜¿ç·¹
    - c1cd69a1-0d61-42d8-b8ca-9c8e15633b4f # XiNaâ†»
    - 4ccb789d-4059-41cf-9505-b820579c2b48 # èŒƒå°å§
    - e1795b61-1cea-4fa0-8015-f029a93b6319 # Amberlyn
    - e159354e-ae76-4481-8171-73dd9d06d335 # Kerryé§èŠ®ğŸ’«
    - 4b3866a0-ca9c-484c-9515-d07897f10af0 # å°ç« é­šå…’
    - 9ff1d605-edf2-49a9-b34f-e77f73245e72 # å“‡å¡å¡
    - 70af911e-f54f-4a64-ad88-e5dbf392f592 # åƒå¿«ä¸€é»
    - 30b6a32b-33df-471f-be42-eaecf9fa487f # æ²æ²ç‘¤
    - 2a9b0ff1-581d-4cec-a24a-178a6cb1c665 # å°æ¬£cindy
    - 7160c5eb-6343-4696-834a-33bae98bf91e # ç±³å®£
    - 5e3af964-9129-42c5-a8ed-90e363c8b39e # æå¤©å¤©
    - fa0ff7fd-10d1-4a3c-897e-32d36c6ccb28 # è‰¾ç‘ªEmmağŸ’«
    - de588428-b08b-4bdb-a9e1-c4486e37e60d # â˜€ï¸æš–æš–ğŸŒ™ğŸ¤
    - 9ccc045f-2b42-44a3-9000-6ddc060280f7 # èœè€å¸«ğŸµ
    - 4f9420ad-2bdc-4228-93bd-7e02ee039758 # å¯§å¯§ğŸ­ğŸ’•
    - a056d951-4628-49e2-bb58-30323421d217 # æ°´æœå§å§
    - 7734d06e-36c7-4a15-9ec0-f2c4f992f8d3 # æ…ˆæ…ˆğŸ¥„â¤ï¸ğŸ¶
    - eecc1148-e267-4eb4-a7e2-7e8cb6bb0670 # å°è­·å£«â˜ï¸
    - 19f77cbc-7609-448d-919d-6849d4b3981b # åš•åš•*
    - fc6af966-6e1c-43bd-aceb-eb84a61037f6 # ğŸ†ƒğŸ…²å°å¤¢å¤¢â¤ï¸
    - aabf4dcd-2f2e-4e5c-9308-91b967977cad # ğŸ†ƒğŸ…²ğŸ’™ç¶­å¨œ
    - 65531ba9-d10c-40c4-b802-ee4e42a3ead7 # ç‹ç‹¸è²
    - 3112db4a-8a1c-42fe-affa-00e0dd1e513b # Jasmine.*ä½³æ€æ˜ğŸ¯
    - 63988abe-8570-40cc-974c-c3a0d0244e40 # å°å­«ğ“¢ğ“¾ğ“·ğŸ¤
    - 08e16280-9c47-456a-bb1c-b3b5f0ae06b3 # VivianğŸŒŸæ¶µæ¶µ
    - 7bbb697f-70aa-4bd1-9c95-5c2d6fa4f01a # å”±æ­Œçš„å›æ†¶
    - 216cec86-dd27-48af-b8c7-7ba57c18a667 # Claireæ©é›ªğŸ’•
    - 9731dad8-b260-4c26-a005-25164a468d03 # é—œç‡ˆ.
    - 74215dc9-3f4e-4659-a796-2cb874baaebf # ğŸ¦©è‹¥æœ‰å¤¢ğŸ€
    - 1dce2cae-52f5-427b-ba02-11fb8091a6db # é­šå¦¹å¦¹
    - d147b8bd-2bd1-4900-8cf3-605c83d23ff7 # å°ç¶¿ç¾Štt
    - 75299eb1-935d-4765-9725-8837c2adc191 # å°è¢ç«ğŸ¦‹ğŸ¤
    - b759e7db-e06b-4ced-b584-f7e5649b6838 # ğŸ†ƒğŸ…²å°å¦ç‰›ğŸ®
    - 08fc8a18-4b44-4db8-865f-742f42ae6957 # å°éœ¸ç‹ğŸ¦–
    - 5561cc38-5a86-4414-ae3a-832b4e656181 # æœªç¹”ã²ã‹ã‚‹

    recommend_ids_for_female:
    - 5150cc3c-baa5-48a3-86b4-f3494b9a414e # BANJI
    - 69c26d00-79b3-4ce6-9d8a-81df95e292a2 # á´¡ÊœÉªá´›á´‡æ‡·ç‰¹
    - 5265b2c9-5046-4950-8b31-69969ae0c230 # ğ“¡Â·ä¸¸
    - f2111e29-1151-45d9-848e-197b341f1add # ç©å…·à² _à² 
    - f3821b6b-a8ff-49f9-860f-4328179a7d32 # luwa
    - 48b5437d-7613-4b01-a284-036e1a6c3d1b # Oleç ´
    - 6443a434-4e3c-47c9-b59a-6f408a51e144 # æ´›Â·å…‹
    - 8a1190db-9fc4-42d6-a8b9-6ac82212410e # á´€sÊœá´‡é˜¿å°„
    - 955ae13c-be83-4e0a-9b9f-4f47c2c1ae66 # ä¸ƒæ˜Ÿè¶…æ·¡_
    - 95145564-d524-4b48-a94f-f649ff099b60 # æªæªæ¡‘å‰äººä¹Ÿ
    - 16953a02-fde7-4f3b-bce2-d252723e2557 # å–œæ­¡å”±æ­Œçš„å°é£›
    - f09db2f9-a13b-45c1-881f-d4150b132b1c # ä¸‹ç­çš„æ™®é€šä¸Šç­æ—Jams
    - cb46a35f-0ae6-487c-aad3-ea3ff5b8c838 # å¾®ç¬‘æ™´å¤©
    - 96949ac0-62ca-469d-b7cf-a40206952060 # å¾·å¾·RyderğŸ·
    - 7a14c76f-576c-4002-befb-8cad59fcb057 # å°å¯†ç¾ŠğŸğŸ¤âœ¨
    - d758ad2c-c302-4fb6-b535-d9e7ab7810f1 # Darren(é”å€«)
    - f810513a-39af-49fe-885e-169b3b41eb83 # ç‘é–€
    - 7d0b5796-93c3-4447-a34e-f28901eed2e7 # VvnğŸ‘»
    - a6265e99-3a0d-467b-8f7b-3dfbabef2054 # å°è¨€â™£ï¸
    - f1e7d3bc-00ad-40fd-bcbc-fd1c00d480ef # å°æŸ’_
    - c67ea0d3-4852-4958-9d26-d91f88c812d7 # å‚¾è½æ¨ºèª
    - b5784c30-0e78-43c5-8bcc-149967db7910 # ğŸ†ƒğŸ…²é…¥é…¥ğŸª
    - adc2a5f4-a97c-4369-af14-568dfad535a5 # ğŸ†ƒğŸ…²è‰¾å€«ğŸ§»
    - 7537eccc-62a3-4bd0-8e8e-d4bada1fa2b4 # ğŸ†ƒğŸ…²èŠ±æ·š
    - 019950e7-f4e0-45e5-87f1-0b3e600aab09 # ğŸ†ƒğŸ…²å°é½Š
    - 35f0b0c2-6e79-4d95-8d78-2ba352e1d506 # ğŸ†ƒğŸ…²ç‚­çƒ¤å¹¸ç¦é˜¿æ°‘
    - 2eaecad7-1fb9-41a3-9460-e43a1dedcc82 # ğŸ†ƒğŸ…²å°çŒ´ğŸŒ¿
    - 11f4a2df-c804-4edd-a5b7-e4af5c5c298e # é™³æ–¯æ©
    - c15101bb-a7a8-4ec9-a9a8-50f4acb00618 # æ»¾æ»¾É¢á´œÉ´ğŸš¯

  - id: chat
    recommend_ids_for_male:
    - d5e6d458-1853-464d-abd6-eff9604a8fb7 # æ­è‰OrliğŸ”†
    - d045f83a-13bf-4fcc-8e92-8b1c6d414c5f # Lana.CCğŸ°ğŸ“
    - f2832bcf-10fa-402d-a971-4f7250876ff5 # æœˆç’ƒğŸŒ¹
    - 992548da-705d-49f0-be12-7b7c06c1f3fc # æŸšå¸ŒYoshiğŸ’•
    - 1c16ba16-a5e3-45e5-9dc3-bfb80bb12b4b # æ™¨æ™¨
    - 67912a65-6ddd-42a9-9643-c33b370c3ccf # è‚‰çµ²RoseğŸŒ¹
    - b3d55407-2cd7-4bfe-b479-dd3c9742e625 # å‡±å¸ŒğŸ¿ï¸
    - 43e3a52d-e2b4-40a8-bc29-0526676b000f # momoå°å­ŸğŸ±
    - c96b5482-25a3-4a54-96f6-5e08c25a64c5 # CCğŸ‹å¯§èŒ
    - cbba63e7-05eb-46f4-81c6-de3ebcef3556 # æ©‹ä¸Šæœ‰ä¸€éš»æœ«æœ«ğŸ
    - 8e1a23d3-6f30-4e78-8564-8ce966647a62 # é€™è£¡æ˜¯æ˜•æ˜•
    - ac021f94-9501-47eb-a7ba-1f626736ec96 # Sandyyyyyyyy
    - 8524faee-b204-4dac-a663-a16c5cbf4726 # hebeç”œ
    - 623188a3-3d65-4221-925d-f2fda7a7f4c9 # ğŸŒºå±±èŒ¶ğŸŒº
    - 021b2d01-c02b-4f70-971e-b33a5601f3eb # èŠ±å¨˜ğ“¯ğ“µğ“¸ğ”€ğ“®ğ“»
    - 747246f0-680e-4860-9dae-b3bfb4139418 # å®‰ç„¶ã‚œğ“ªğ“·ğŸ¦‰
    - b3483f98-5088-48cc-ad07-a1e1c26b4650 # æ³°ä½›çˆº
    - 86a82e91-7d2f-434d-b562-c430a718e1ad # momoå§å§
    - 7cdc6c06-9a1a-459e-8cc0-e1234b87e5fe # ç±³é…ªå§†
    - b590ccae-200a-480d-a92c-7b5a55308614 # æŸ”èªæ™¨æ˜Ÿ
    - 8b120420-66df-4f6b-9005-1b70c9e7a55a # é‚±é‚±Jane
    - 8c60a6e2-78f4-4e1c-9d7e-6ab5f208597b # ä¸€éš»å°ç‹ç‹¸
    - 159ac1df-bc4e-43e1-934b-cdb17006a988 # é¬¼ç­†æ˜¯ä¸€ç¨®è‡
    - 8c8b5008-a3ce-4298-97ba-feb2bddf172e # å·å¿ƒè²è²â™¥ï¸
    - de9d5d3e-f98f-4b21-8c71-2da4ffcb7fe6 # Spriteé›ªç¢§
    - e6c76520-cb20-4fba-be08-d1eae3a44d6d # è²“ç©ºæ˜Ÿç·£
    - 51197710-f3fb-4893-b0cb-59f57ec6d044 # ä¸€é¹¿æœ‰å¦®
    - 4472920e-d66f-4ef8-948f-fa8e04de2b54 # ğŸ†ƒğŸ…²ç¬‘ç¬‘ğŸ˜›
    - b759e7db-e06b-4ced-b584-f7e5649b6838 # ğŸ†ƒğŸ…²å°å¦ç‰›ğŸ®
    - aa78ab87-d4f2-49a1-8f97-29061906cf9d # ğŸ†ƒğŸ…²å‡¡å‡¡ğŸŒ¼
    - d5f7a152-f9ff-4af4-a2b0-0c246e31e8c9 # å¯¶è²å…’ğŸ¤«
    - d0ba6b7a-54c5-4421-b561-0c3ddd69a216 # _.4444x_
    - 5fe54805-f8d8-481a-b5ce-27ef1a338a0a # æŸ”æŸ”å…’ğŸ¼
    - 54241023-ae77-44dd-b770-417d9b507fda # YunCat
    - 61ef9fa3-7c6b-43d5-8569-12a50e7440ff # å¤©å…²
    - aa95e7ea-1695-4237-a3c2-80d9ca2d8dec # ç‰›ç“¶ç“¶
    - ddd430ec-3968-4bf2-9bbc-fc0417f04830 # åŠ è²è²“ã‚µãƒªãƒŠ
    - 5b0f9575-cbf6-4ec5-aab9-c61eecf61eab # å¥¶èŒ¶è¦åŠ ç³–
    - 6b920a17-a5f2-4bd2-a563-b99d1e1d83b2 # Joanne_L
    - 42686e6b-6640-4da1-9cff-7a70228b2cc2 # ä¹™æ ¼
    - d904ce3f-5469-4831-a1ab-becb0947de76 # å­¸å§Š_
    - 7e520c41-8e9c-45b2-90cc-5b6f62d77343 # ç…‰ä¹³å°å–µğŸ“
    - 39300774-31f6-4c31-a4e7-31a3bf9cc20a # å¦å¦å¤©ä½¿
    - b2b24e2e-4829-4117-8cd5-742198e72cb4 # æ˜¯ä½ çš„å°è˜‹æœğ‘¨ğ’‘ğ’‘ğ’ğ’†ğŸ
    - 0b3d40cf-64fb-4aea-ac13-8f16ac2e6352 # ğŸºä¸æƒ³åšå¤¢çš„å­Ÿå…’
    - 1312f946-e891-4a6d-a64c-5f35a8d5c493 # æ˜¥å¤©å‡èŒ
    - dffcdbbd-4c6d-49e5-8993-f3106e4ee54d # summer20
    - 11069e51-f751-493f-8b3c-9d2012033f6b # å’ªå’ªè²“è²“ğŸˆ
    - 0f7d76e6-ba96-44ae-8bdb-68a67ee5d95f # ğŸŒ™æœˆå…‰ä»™ä»™âœ¨
    - e95f097a-2559-4052-8945-4602316b6610 # äºˆå¿
    - 53adb83b-4c6d-422b-b3ec-df9df2dfebf5 # å¿ƒ0å”§æ¹¯
    - 4eccc131-5ec5-4ada-8d1c-9ee6f99fade6 # ç‡šğŸ¬
    - d29b1a40-30a0-4fcb-ab62-6b8b45ce0493 # å¿ƒå¿ƒä¸»æ’­ğŸ’œ
    - f6be4708-8b1c-4f09-aa2a-5a452135bb51 # å°ç±³å¡é†¬
    - cfc46a9a-a33f-4f11-8672-00b75217595e # ç‘¾ç‘¶
    recommend_ids_for_female:
    - a946156f-7d3e-4f13-831c-a24c0e28a8c2 # ç½¡é‘’
    - e1eb9635-13cb-4765-bf0c-6a4d3865c9ee # æ°´ç“¶åº§â™’ï¸
    - 8baaba2a-069f-4349-aa05-c00f7519c66d # å±±å§†_Sam
    - 6e304d69-0c33-4028-ac9a-47cd39c5729b # æ‰é‚Š
    - 35528ac5-32ba-4f61-9bb5-42598e7e34a7 # é˜¿è²å‡ºäº‹äº†ï½é˜¿è²ï½ğŸ·
    - c5444a9b-c83f-4dff-a7f5-017e10e4ed27 # â™›å¹½å¹½â™›
    - 8d3481da-bde9-4fc6-8106-cd73b783c324 # é³³æ¢¨å”é¼ ğŸ
    - 4ed31cb8-bbd6-4dd2-98ec-276b8d7ce042 # é˜¿è£‚æŸ¯p
    - eda5b79a-9d8d-429b-bb2c-74205750df2a # âœ¨DALEæˆ´çˆ¾ğŸ’„ğŸ¤âœ¨
    - 297446d2-7a58-4b15-8963-856bc2013e9e # ä¸¹å°¼DannyLiu
    - a4ded422-f35f-4ea2-a7b2-fe0870de0d69 # èŠ±ç§€æ‰
    - 2d56f6d0-5a9c-418e-ba9e-be4beecd9d8d # ğŸ‘¾MarcoğŸ“·
    - 4ed31cb8-bbd6-4dd2-98ec-276b8d7ce042 # é˜¿è£‚æŸ¯p

  - id: daily
    recommend_ids_for_male:
    - aeab6a8a-760c-48f7-b69a-1b4eca83f3b2 # Stellastella
    - 3072c4dc-9ac4-486f-80ca-6e20ee98d3a9 # æ‡¶æ‡¶ä¸¸
    - 8c99dae6-4d51-482a-96fe-a9a75b1308c2 # å°ç¥¤ç¥¤
    - f5e4445e-1c6b-41f5-afaf-63f6fe6a4cb8 # 77âœ¨
    - d83ede4e-3aa8-41bb-aec7-c10cfefcc744 # åæŸ’
    - d34b579c-af77-4d4a-b7e2-ee8f4f4fdc1d # ğŸ†ƒğŸ…²æº«æ„›ğ“°ğ“®ğ“·ğ“½ğ“µğ“®
    - b359131f-315b-459b-8cbf-66b379cca06a # ğŸ†ƒğŸ…²å¤§é›¨â›ˆï¸
    - abea19f6-97a5-4c03-a9d6-b654cae8db29 # Mollyè‹¡æ²«
    - 4f932b63-55ae-4021-b4bc-e06fb6040e73 # Twinkle_
    - 4a6ba1e3-7d1c-4314-b0e2-e309584bd927 # Waffle:)
    - 7ca076bf-e72f-4676-a038-daed8de108e8 # è‘µè‘µğŸ¤
    - 6253e1a0-c415-4a73-b2e4-39f196c973e7 # æ˜¯é›™é›™å‘€ğŸ¦
    - 100d22d4-5213-4192-b24d-b31082bcb98f # åœ°æ–¹å°å³
    - 35838143-b648-409c-8da6-efa6fe63a2fb # å¥ˆçˆ¾
    - 6b13a28c-4b88-44b2-8432-180661ed5bfd # Chi.é˜¿çªâ™¡
    - 71bd60bd-80f7-4a38-b58b-a6b61171b29c # BowğŸ¤˜
    - 100d22d4-5213-4192-b24d-b31082bcb98f # QunaË™â°™Ë™à¸…
    - eb90f389-6dd0-4876-b2cf-0d1d5741dc26 # æ„›åƒç³–ã®ç³–ğŸ­
    - dee14130-0005-4d9f-9fde-dea65776a295 # å¦®å¯å®‰å¾·&&
    - 09a1e2a7-6e49-4dc3-8428-127cc5a7e90b # ğŸ†ƒğŸ…²é­šè²“ğŸ‹
    recommend_ids_for_female:
    - 1dcea1eb-af52-401f-8146-c3cf0029a691 # ğŸŒ³å¤§æ¨¹ğŸŒ³
    - 8c815bff-5408-4658-b7fa-c56af2ee901a # ä½ æ˜¯ä¸æ˜¯æœ‰é»å‹•å¿ƒ 
    - 9760ca9d-4bda-439d-8cf0-e375f90fa6a9 # ğ“„‚ä¾†è‡ªåœ°ç„çš„è–æ­Œâ€ 
    - 0de271b3-0452-4d34-9313-1bd185e77a18 # å‚‘ç±³Jamie
    - b7007eec-95b0-476e-8230-a5e40ba89756 # å˜¿å…ˆç”Ÿ
