recommend_threshold: 300
recommend_streamer_ids_for_new_male_user:
  - 4ccb789d-4059-41cf-9505-b820579c2b48 # èŒƒå°å§
  - ac021f94-9501-47eb-a7ba-1f626736ec96 # Sandyyyyyyyy
  - 4773f4c4-0272-49e6-a26e-e8317ac3be41 # Michelleçº
  - 767f272b-ac4c-49c8-9eb8-1ceda7836b2e # ç±³è²å©­.KemythiağŸŒ¹
  - 8c60a6e2-78f4-4e1c-9d7e-6ab5f208597b # ä¸€éš»å°ç‹ç‹¸
  - e1addcc3-641e-4dd8-83a7-e7f508298c36 # FiFiğŸ’•
  - e159354e-ae76-4481-8171-73dd9d06d335 # Kerryé§èŠ®ğŸ’«
  - 4b3866a0-ca9c-484c-9515-d07897f10af0 # å°ç« é­šå…’
  - 3112db4a-8a1c-42fe-affa-00e0dd1e513b # Jasmine.*ä½³æ€æ˜ğŸ¯
  - 61ef9fa3-7c6b-43d5-8569-12a50e7440ff # å¤©å…²
  - 5bd69b10-a6b2-4241-b175-0782596fd706 # ç¨€éŸ³
  - 623188a3-3d65-4221-925d-f2fda7a7f4c9 # ğŸŒºå±±èŒ¶ğŸŒº
  - 021b2d01-c02b-4f70-971e-b33a5601f3eb # èŠ±å¨˜
  - 747246f0-680e-4860-9dae-b3bfb4139418 # å®‰ç„¶ã‚œ
  - 5e3af964-9129-42c5-a8ed-90e363c8b39e # æå¤©å¤©
  - fa0ff7fd-10d1-4a3c-897e-32d36c6ccb28 # è‰¾ç‘ªEmmağŸ’«
  - e12ed114-a5a7-4c9f-a06f-31f6cf27b850 # å®‰æ½”è‰å¨œæ™š
  - 39698627-848b-4d01-a131-49473afc8585 # 77âœ¨
  - b64bb4d3-f164-439c-9d29-095ba73237f6 # æ‰“é›·ä¸‹é›¨æ”¶è¡£æœå•¦
  - e914c9d7-fbca-42a2-9fca-767405d1df8e # è‰è‰çš†è¾›è‹¦ğŸ’¦Lily
  - f235f2c2-3f4e-4fbc-94f4-29228c0db6cc # æ·å§
  - 42686e6b-6640-4da1-9cff-7a70228b2cc2 # ä¹™æ ¼
  - 8e1a23d3-6f30-4e78-8564-8ce966647a62 # é€™è£¡æ˜¯æ˜•æ˜•
  - cbba63e7-05eb-46f4-81c6-de3ebcef3556 # æ©‹ä¸Šæœ‰ä¸€éš»æœ«æœ«ğŸ
  - aeab6a8a-760c-48f7-b69a-1b4eca83f3b2 # Stellastella
  - b6db268b-7309-44c0-9b28-b4d9d25ea51b # è¿·å¦¹å¯ç³ç³–
  - 7b42db74-90ad-4d79-b628-ea868878daaf # å¼€å¿ƒæœ+å°è¾£æ¤’
  - 8c8b5008-a3ce-4298-97ba-feb2bddf172e # å·å¿ƒè²è²â™¥ï¸
  - 46d6a400-5aa3-4070-93d9-68cdcf496864 # æ¼ æ¼ æ˜¯æˆ‘
  - be6a1107-282f-4705-9105-0fe145f130e1 # æ°´æ°´ğŸ¿ï¸
  - d34b579c-af77-4d4a-b7e2-ee8f4f4fdc1d # ğŸ†ƒğŸ…²æº«æ„›ğ“°ğ“®ğ“·ğ“½ğ“µğ“®
  - fc6af966-6e1c-43bd-aceb-eb84a61037f6 # ğŸ†ƒğŸ…²å°å¤¢å¤¢â¤ï¸
  - a6290fe5-3c37-4185-8d63-b66e8647732a # å­Ÿå›NATSUME
  - c44f7032-3ded-45c8-9baa-3a07f2fe3f56 # Lulu~~~~
  - 72a9058c-6385-4456-863f-a7913fea909e # ç†Šç†ŠğŸ§¸
  - 9e42c09b-6eaa-4713-8928-2de4546de274 # è‰æLiLee
  - dd83f2ba-c373-4ddb-94a3-529cd6219c1f # 3am.la
  - 4a6ba1e3-7d1c-4314-b0e2-e309584bd927 # Waffle
  - d045f83a-13bf-4fcc-8e92-8b1c6d414c5f # Lana.CCğŸ°ğŸ“
  - 5b0f9575-cbf6-4ec5-aab9-c61eecf61eab # å¥¶èŒ¶è¦åŠ ç³–
  - 43c9e114-fbe5-4908-857d-fcec71cb84ca # æ³¢æ–¯ğŸŠ
  - aa95e7ea-1695-4237-a3c2-80d9ca2d8dec # ç‰›ç“¶ç“¶
  - 9c5b0fd2-2d9b-43b7-8fca-87146549187c # å’»å’»Ù©(*Â´ï¸¶`*)Û¶
  - b5ec2f6b-cfd0-4305-bdc8-6f7f171a1672 # 08isbear
  - 8baba137-1ae2-4387-b00a-0ca7d5db83e8 # æ˜€éœ
  - 898f94f2-fbaa-4438-8ff8-4b73e2fd5c0c # ğŸ¦‹ğ•ƒğ•šğ•’å¨®
  - e1addcc3-641e-4dd8-83a7-e7f508298c36 # FifiğŸ’•
  - c1cd69a1-0d61-42d8-b8ca-9c8e15633b4f # XiNaâ†»
  - 6253e1a0-c415-4a73-b2e4-39f196c973e7 # çŸ­é«®å¦–ç²¾é›™é›™
  - d736c541-fefb-4328-908f-4a05310c785e # éœéœğŸ’‹
  - 86a82e91-7d2f-434d-b562-c430a718e1ad # momoå§å§
  - aabf4dcd-2f2e-4e5c-9308-91b967977cad # ğŸ†ƒğŸ…²ğŸ’™ç¶­å¨œ
  - d39a66e8-1062-488f-a388-18019ddcaaca # Little Crystal
  - 26c7a01e-08b9-4656-9b44-37c1b559180a # Reneeâ€ ///è‰¾ç³
  - d3d5f4dc-60e3-444b-ae0a-8ce1b631a7e0 # â™¡Anniâ™¡
  - 9ff1d605-edf2-49a9-b34f-e77f73245e72 # å“‡å¡å¡
  - 871f7fa9-15dc-4ff8-a1b5-f38cbf883da4 # Yunjuå°å¦‚
  - 334c12bc-7c95-4fb9-8e28-ae0e9a66ce82 # å®‰ç–AnjiuğŸ¤
  - 159ac1df-bc4e-43e1-934b-cdb17006a988 # é¬¼ç­†æ˜¯ä¸€ç¨®è‡
  - 5059aaef-4a71-49d5-b61c-70d5f8f363ff # ğ’Ÿğ’¶ğ“ƒä¸¹
  - 4472920e-d66f-4ef8-948f-fa8e04de2b54 # ğŸ†ƒğŸ…²ç¬‘ç¬‘ğŸ˜›
  - 7734d06e-36c7-4a15-9ec0-f2c4f992f8d3 # YuuuğŸ¶
  - 05e886b2-9f71-4b3d-a337-cb5e537cad6f # Naaaaaa
  - 1b34aba9-c6d4-4cbb-bcfd-7e710326bcbe # oè–”è–‡o
  - d3c44590-8c9a-4ee1-b005-eb011806c588 # *Universe*
  - 4f932b63-55ae-4021-b4bc-e06fb6040e73 # Twinkle_
  - dae178f1-7899-4912-8e70-7b4639b712de # æœ¨æœ¨â˜¾ï¸
  - 21b42ba1-30e2-45af-b60b-def944c0d4e7 # é˜¿æ‹‰è•¾ğŸŒ¸
  - d5f7a152-f9ff-4af4-a2b0-0c246e31e8c9 # å¯¶è²å…’ğŸ¤«
  - fc9a7077-6145-4186-a068-5a998b5eeef5 # è‡ºå…­ç”²å¥¶å§¬
  - de9d5d3e-f98f-4b21-8c71-2da4ffcb7fe6 # Spriteé›ªç¢§
  - de588428-b08b-4bdb-a9e1-c4486e37e60d # â˜€ï¸æš–æš–ğŸŒ™ğŸ¤
  - bcd05130-9730-4196-9469-be4138e3f51b # Leelah
  - 19f77cbc-7609-448d-919d-6849d4b3981b # åš•åš•*
  - 3f8c7833-6ed0-4192-bb76-5fa71e1416bc # éœ²éœ²å¦®
  - 352fc452-5236-4467-9064-62dbf1528f4f # äº¦è‹’
  - 6b13a28c-4b88-44b2-8432-180661ed5bfd # Chi.é˜¿çªâ™¡
  - 63988abe-8570-40cc-974c-c3a0d0244e40 # psvsun
  - be65197d-98cd-4a1b-a409-d4aca5534555 # æé¾â“€â“
  - ed34e0b7-592b-44ab-b1c4-525070ceff49 # å¯æ’¥
  - 6fe47d40-4397-4480-8536-1b556f19edf6 # RaynağŸ¹ğŸ¤
  - e1795b61-1cea-4fa0-8015-f029a93b6319 # Amberlyn
  - 28bea058-af19-4929-8c56-193a68b2a0dc # Soniaç´¢å°¼é›…
  - 3003f127-bf55-4759-b710-fcc51b04e1d9 # G.A.O
  - c33fd588-9f9b-4f32-b234-972f1d2a6b31 # å–®çœ¼çš®å–®å–®
  - 6fb2fdce-d084-480d-8a37-a52648a932f3 # á´´áµ‰áµƒÊ³ç†Šè²ğŸ¼
  - ac58c614-15bf-485f-bf0e-36ebb51f079a # èœœæ¡ƒå£å‘³åˆ©å£é…’
  - de588428-b08b-4bdb-a9e1-c4486e37e60d # â˜€ï¸æš–æš–ğŸŒ™ğŸ¤
  - 7cdc6c06-9a1a-459e-8cc0-e1234b87e5fe # ç±³é…ªå§†
  - b8dae53d-81b1-4cb5-9b03-1ccffe56bb39 # çæƒœç¾åœ¨çš„è¼•èˆé£›æš
  - b590ccae-200a-480d-a92c-7b5a55308614 # æŸ”èªæ™¨æ˜Ÿ
  - de9d5d3e-f98f-4b21-8c71-2da4ffcb7fe6 # Spriteé›ªç¢§
  - 718e6309-9490-4192-a66a-f576d1f4449d # å¤¢å¤¢ğŸŒ™
  - 52292063-8040-4440-be1e-43cb185c8a9c # ğŸ†ƒğŸ…²JCKâœ¨
  - 34775d6f-7fdb-4523-9286-5d3f631cff10 # ğŸ†ƒğŸ…²å“å–¬
  - aa78ab87-d4f2-49a1-8f97-29061906cf9d # ğŸ†ƒğŸ…²å‡¡å‡¡ğŸŒ¼
  - 60134d86-e6f2-4f07-855f-5c25c28798b2 # é™³é™³ğŸ–¤
  - d5f7a152-f9ff-4af4-a2b0-0c246e31e8c9 # å¯¶è²å…’ğŸ¤«
  - abea19f6-97a5-4c03-a9d6-b654cae8db29 # Mollyè‹¡æ²«
  - 95a0853e-e60c-4bd6-add9-4a04eaa910e2 # Duerreç‘ªå…’
  - d0ba6b7a-54c5-4421-b561-0c3ddd69a216 # ğµğ‘œğ‘šğ‘–
  - 73bcf532-4592-4320-a865-9f4b1f7bbd6e # å“å‘€å‘€ğŸŒ¸
  - 100d22d4-5213-4192-b24d-b31082bcb98f # åœ°æ–¹å°å³
  - b3d55407-2cd7-4bfe-b479-dd3c9742e625 # å‡±å¸ŒğŸ¿ï¸
  - d5e6d458-1853-464d-abd6-eff9604a8fb7 # æ­è‰OrliğŸ”†
  - c96b5482-25a3-4a54-96f6-5e08c25a64c5 # CCğŸ‹å¯§èŒ
  - a5fa6d00-e94b-42d9-8097-33aedbff7b69 # Dingdong
  - 6b13a28c-4b88-44b2-8432-180661ed5bfd # Chi.é˜¿çªâ™¡
  - 63988abe-8570-40cc-974c-c3a0d0244e40 #å°å­«ğ“¢ğ“¾ğ“·ğŸ¤
  - 6b920a17-a5f2-4bd2-a563-b99d1e1d83b2 # Joanne_L
  - 37f04a2e-b8de-4b13-ac09-17dee0375b6c # ğŸå°è˜‹æœ
  - 75cdfdfb-8515-433b-91cb-8861c529b13d # ğŸ€âˆèŠƒèŠƒâ•¯ï¼ŠÂ°
  - 8b120420-66df-4f6b-9005-1b70c9e7a55a # é‚±é‚±Jane
  - 4622fd03-acbd-49ad-9a31-6b665f5174c1 # å¹¸é‹ğŸŒŸ
  - 6fb2fdce-d084-480d-8a37-a52648a932f3 # á´´áµ‰áµƒÊ³ç†Šè²ğŸ¼
  - d43716fd-3134-4c1c-8d08-8a13b1485e28 # å°é‚¦å¦®ğŸ’•
  - 5dae7887-004d-4b8c-80ce-9e24cb0d7419 # å®‰èˆçµ²
  - 8c99dae6-4d51-482a-96fe-a9a75b1308c2 # å°ç¥¤ç¥¤
  - 73d0cfe7-bd58-474b-b83b-eb5543207198 # ğŸŒ¹Magumiè²è²ğŸŒ¹
  - 1e3ceec9-08e6-483e-ae61-c7caf62880db # NN...
  - 7160c5eb-6343-4696-834a-33bae98bf91e # ç±³å®£
  - 3c60a53c-61e7-4596-a5c8-2bacd616d205 # å“å°ç´«
  - 74823cbc-6382-411b-88c6-8d2dc6b2dbfe # Jessicaâ¤ï¸Ng
  - 30f9402d-c726-4138-aedf-27eb66582605 # Qå¨œ
  - 56cef208-d817-4cd4-8b21-e0416228cc3d # Juicyy
  - 0632d4e2-55b5-4b79-a45c-b65def5670df # YYLIN
  - c7a5d8df-e5dc-4eef-8398-15fda8ef43ee # Amber.
  - a056d951-4628-49e2-bb58-30323421d217 # æ°´æœå§å§
  - 16b390be-78d0-4446-acca-5081254ff5ab # å›¡ä»”
  - d83ede4e-3aa8-41bb-aec7-c10cfefcc744 # åæŸ’
  - eecc1148-e267-4eb4-a7e2-7e8cb6bb0670 # å°è­·å£«â˜ï¸
  - 12307a9a-921b-4a71-bb03-8946c0e91fbd # çš®å¡è›™
  - 49e571ea-df13-43b2-bee0-9d91612ddaba # å®‰æ˜Ÿ
  - 6a8740b0-5081-470c-89aa-f4a5c8264222 # å…æ™´å…’
  - de907770-b34b-4e8e-b17b-ab35e5d5bb19 # èˆèˆéšŠé•·
  - 8ce1c777-edce-471c-8108-216a44723caf # é–ƒäº®äº®ğŸ‘»â¤ï¸
  - 506e0121-7d53-4eb1-9c09-ab5f7dd9f677 # Annieè‹¡å®¸ğŸŒ±
  - 204dab39-1d4a-4fe6-83b0-82f337dc4f5a # éœéœï¼å¾®å…‰
  - 992548da-705d-49f0-be12-7b7c06c1f3fc # Yoshiowo
  - b8172c7-198a-4adf-b066-6e0d1d0544f9 # æ¨‚æ™´â™ª
  - dcd92d2a-e438-43b5-9f06-0282f86ec986 # ç´ç´ç´ç´
  - 7bbb697f-70aa-4bd1-9c95-5c2d6fa4f01a # å”±æ­Œçš„å›æ†¶
  - 216cec86-dd27-48af-b8c7-7ba57c18a667 # Claireæ©é›ªğŸ’•
  - 08e16280-9c47-456a-bb1c-b3b5f0ae06b3 # VivianğŸŒŸæ¶µæ¶µ
  - 67912a65-6ddd-42a9-9643-c33b370c3ccf # è‚‰çµ²RoseğŸŒ¹
  - 74215dc9-3f4e-4659-a796-2cb874baaebf # ğŸ¦©è‹¥æœ‰å¤¢ğŸ€
  - d904ce3f-5469-4831-a1ab-becb0947de76 # å­¸å§Š_
  - 9731dad8-b260-4c26-a005-25164a468d03 # é—œç‡ˆ.
  - 7e520c41-8e9c-45b2-90cc-5b6f62d77343 # ç…‰ä¹³å°å–µğŸ“
  - 39300774-31f6-4c31-a4e7-31a3bf9cc20a # å¦å¦å¤©ä½¿
  - b2b24e2e-4829-4117-8cd5-742198e72cb4 # æ˜¯ä½ çš„å°è˜‹æœğ‘¨ğ’‘ğ’‘ğ’ğ’†ğŸ
  - 7e5310d7-2642-449c-85f0-3649fc906e43 # QunaË™â°™Ë™à¸…
  - fa1c8631-4a2d-4b76-b5af-6b2878faf446 # å¥¶ç²‰elsa
  - 1dce2cae-52f5-427b-ba02-11fb8091a6db # é­šå¦¹å¦¹
  - eb90f389-6dd0-4876-b2cf-0d1d5741dc26 # æ„›åƒç³–ã®ç³–ğŸ­
  - d147b8bd-2bd1-4900-8cf3-605c83d23ff7 # å°ç¶¿ç¾Štt
  - 0b3d40cf-64fb-4aea-ac13-8f16ac2e6352 # ğŸºä¸æƒ³åšå¤¢çš„å­Ÿå…’
  - 1312f946-e891-4a6d-a64c-5f35a8d5c493 # æ˜¥å¤©å‡èŒ
  - dffcdbbd-4c6d-49e5-8993-f3106e4ee54d # summer20
  - 11069e51-f751-493f-8b3c-9d2012033f6b # å’ªå’ªè²“è²“ğŸˆ
  - dee14130-0005-4d9f-9fde-dea65776a295 # å¦®å¯å®‰å¾·&&
  - e95f097a-2559-4052-8945-4602316b6610 # äºˆå¿
  - 75299eb1-935d-4765-9725-8837c2adc191 # å°è¢ç«ğŸ¦‹ğŸ¤
  - 0f7d76e6-ba96-44ae-8bdb-68a67ee5d95f # ğŸŒ™æœˆå…‰ä»™ä»™âœ¨
  - 5561cc38-5a86-4414-ae3a-832b4e656181 # æœªç¹”ã²ã‹ã‚‹
  - 08fc8a18-4b44-4db8-865f-742f42ae6957 # å°éœ¸ç‹ğŸ¦–
  - 53adb83b-4c6d-422b-b3ec-df9df2dfebf5 # å¿ƒ0å”§æ¹¯
  - 4f9420ad-2bdc-4228-93bd-7e02ee039758 # å¯§å¯§ğŸ­ğŸ’•
  - b759e7db-e06b-4ced-b584-f7e5649b6838 # ğŸ†ƒğŸ…²å°å¦ç‰›ğŸ®
  - 09a1e2a7-6e49-4dc3-8428-127cc5a7e90b # ğŸ†ƒğŸ…²é­šè²“ğŸ‹
  - eeab4472-7121-4f35-8d14-417914798967 # ğŸ†ƒğŸ…²ç«¹ç«¹à¹‘âƒ™âƒ˜Â´à¼¥`à¹‘âƒ™âƒ˜
  - 4eccc131-5ec5-4ada-8d1c-9ee6f99fade6 # ç‡šğŸ¬
  - d29b1a40-30a0-4fcb-ab62-6b8b45ce0493 # å¿ƒå¿ƒä¸»æ’­ğŸ’œ
  - f6be4708-8b1c-4f09-aa2a-5a452135bb51 # å°ç±³å¡é†¬
  - cfc46a9a-a33f-4f11-8672-00b75217595e # ç‘¾ç‘¶
  - e61cfd0f-14c4-4b54-9255-ca70a0fe46aa # â¤ï¸å°å…¬ä¸»

recommend_streamer_ids_for_new_female_user:
  - cb46a35f-0ae6-487c-aad3-ea3ff5b8c838 # å¾®ç¬‘æ™´å¤©
  - 6443a434-4e3c-47c9-b59a-6f408a51e144 # æ´›Â·å…‹
  - 955ae13c-be83-4e0a-9b9f-4f47c2c1ae66 # ä¸ƒæ˜Ÿè¶…æ·¡_
  - 96949ac0-62ca-469d-b7cf-a40206952060 # å¾·å¾·RyderğŸ·
  - 5265b2c9-5046-4950-8b31-69969ae0c230 # ğ“¡Â·ä¸¸
  - 5150cc3c-baa5-48a3-86b4-f3494b9a414e # BANJI
  - 6e304d69-0c33-4028-ac9a-47cd39c5729b # æ‰é‚Š
  - cb63a180-152d-4b59-aba3-002019d5e05d # å°ç‘R.A.E
  - 4c2f1478-9ec6-4dfc-82e6-09d6f3667167 # è«­ç©ğŸ§yoyo
  - 55dec144-8209-4747-9e4b-faa1fbcbde71 # æ·ºæ†¶å¢¨æ®¤
  - 11f4a2df-c804-4edd-a5b7-e4af5c5c298e # é™³æ–¯æ©
  - 40c13437-f27f-4e6c-8c82-69945151ba46 # æ±Ÿå¤©èƒ¤TinChiang
  - 8a1190db-9fc4-42d6-a8b9-6ac82212410e # á´€sÊœá´‡é˜¿å°„
  - cef35c7b-d8f6-4929-a112-7e2927c3cb08 # 10011101
  - a1bdb220-71af-4b95-9afc-b50cdddf2563 # å•Ÿç¨‹
  - f09db2f9-a13b-45c1-881f-d4150b132b1c # ä¸‹ç­çš„æ™®é€šä¸Šç­æ—Jams
  - 7a14c76f-576c-4002-befb-8cad59fcb057 # å°å¯†ç¾ŠğŸğŸ¤âœ¨
  - 8baaba2a-069f-4349-aa05-c00f7519c66d # å±±å§†_Sam
  - d92916b3-e58d-4174-8926-6785ded4f33c # æ™šå®‰é›»å°
  - f020fcd6-538c-40e6-82d5-fe8b05867303 # é¦™æ°´å°å“¥
  - cfdf9ccc-55a7-4a9f-a4fa-a4bcd091bd28 # æ±Ÿå¾®é¢¨çš„æ—…è¡Œ
  - 69c26d00-79b3-4ce6-9d8a-81df95e292a2 # á´¡ÊœÉªá´›á´‡æ‡·ç‰¹
  - e1eb9635-13cb-4765-bf0c-6a4d3865c9ee # æ°´ç“¶åº§â™’ï¸
  - a946156f-7d3e-4f13-831c-a24c0e28a8c2 # ç½¡é‘’
  - f2111e29-1151-45d9-848e-197b341f1add # ç©å…·à² _à² 
  - eda5b79a-9d8d-429b-bb2c-74205750df2a # âœ¨DALEæˆ´çˆ¾ğŸ’„ğŸ¤âœ¨
  - ed6a3bda-9ed4-4c3e-8faf-e8696d662d28 # AllenTalk
  - 3314850e-ce3a-4a64-9997-9fa3ba955269 # ä½›ç³»å°å“¥å“¥Leo
  - b5784c30-0e78-43c5-8bcc-149967db7910 # ğŸ†ƒğŸ…²é…¥é…¥ğŸª
  - adc2a5f4-a97c-4369-af14-568dfad535a5 # ğŸ†ƒğŸ…²è‰¾å€«ğŸ§»
  - 1c7bfc8a-7567-4b6b-bad9-ca3f8f11b4fe # é»‘æ ¼çˆ¾Hegel
  - c67ea0d3-4852-4958-9d26-d91f88c812d7 # å‚¾è½æ¨ºèª
  - 8371906d-b910-4bb3-8245-f1cbda3d06fe # è²å¡”VETA
  - 992287e4-b11f-4df1-8221-e9f4730f4684 # ğŸ­BJå¯µç‰©ç•«å¸«ğŸ™ï¸
  - 297446d2-7a58-4b15-8963-856bc2013e9e # ä¸¹å°¼DannyLiu
  - a2cc8374-f39c-4716-98cc-e322b40be194 # æœ¨ä½æœ¨å‘Š
  - 16953a02-fde7-4f3b-bce2-d252723e2557 # å–œæ­¡å”±æ­Œçš„å°é£›
  - ce6f6fbb-6aeb-4896-b2dd-be85b32170e9 # ç•ªèŒ„å”å”ğŸ…
  - d758ad2c-c302-4fb6-b535-d9e7ab7810f1 # Darren(é”å€«)
  - f810513a-39af-49fe-885e-169b3b41eb83 # ç‘é–€
  - 75bf28dc-8537-4894-ab20-5a1a9ddac834 # ç±³å‹’å…ˆç”Ÿ
  - a36ede75-81f3-4a97-b73b-bf39094675a7 # ğŸ…ƒğŸ„²èŠÂ·_Â·
  - 35528ac5-32ba-4f61-9bb5-42598e7e34a7 # é˜¿è²å‡ºäº‹äº†ï½é˜¿è²ï½ğŸ·
  - 2eaecad7-1fb9-41a3-9460-e43a1dedcc82 # ğŸ†ƒğŸ…²å°çŒ´ğŸŒ¿
  - c5444a9b-c83f-4dff-a7f5-017e10e4ed27 # â™›å¹½å¹½â™›
  - 8d3481da-bde9-4fc6-8106-cd73b783c324 # é³³æ¢¨å”é¼ ğŸ
  - f3821b6b-a8ff-49f9-860f-4328179a7d32 # luwa
  - 740e3047-c95f-4a18-b1a5-11a6807f0ccf # å‘¨åŠ›å®‡LynnğŸ¤ğŸ¸
  - eeafd2d2-8070-4619-a6dd-a28c40657649 # ç¾²å’Œç„šå¿ƒ
  - 8659cb10-1d82-4486-8f25-957d78d7c2a7 # å°å¤œğŸ·
  - 019950e7-f4e0-45e5-87f1-0b3e600aab09 # ğŸ†ƒğŸ…²å°é½Š
  - 7d0b5796-93c3-4447-a34e-f28901eed2e7 # VvnğŸ‘»
  - f1e7d3bc-00ad-40fd-bcbc-fd1c00d480ef # å°æŸ’_
  - a187dbbd-79c4-4d6c-8106-32a77cac133b # å°é˜¿è¶…
  - f98a4188-f980-4051-8b2f-810603c55d63 # è±¬é ­çš®ğŸ·
  - 35f0b0c2-6e79-4d95-8d78-2ba352e1d506 # ğŸ†ƒğŸ…²ç‚­çƒ¤å¹¸ç¦é˜¿æ°‘
  - 952f8479-a9e7-4e9a-ac20-b8237a5a83e7 # è‹¥æœ‰å¤¢çš„é€¸é¢¨999999999
  - 1dcea1eb-af52-401f-8146-c3cf0029a691 # ğŸŒ³å¤§æ¨¹ğŸŒ³
  - 8c815bff-5408-4658-b7fa-c56af2ee901a # ä½ æ˜¯ä¸æ˜¯æœ‰é»å‹•å¿ƒ
  - c15101bb-a7a8-4ec9-a9a8-50f4acb00618 # æ»¾æ»¾É¢á´œÉ´ğŸš¯
  - 3d61c0ac-dcf4-4313-9f09-b81e75d112d8 # é»ƒæŸéŸ¶
  - 0de271b3-0452-4d34-9313-1bd185e77a18 # å‚‘ç±³Jamie
  - b7007eec-95b0-476e-8230-a5e40ba89756 # å˜¿å…ˆç”Ÿ
  - 2d56f6d0-5a9c-418e-ba9e-be4beecd9d8d # ğŸ‘¾MarcoğŸ“·
  - 4ed31cb8-bbd6-4dd2-98ec-276b8d7ce042 # é˜¿è£‚æŸ¯p