recommend_threshold: 300
recommend_streamer_ids_for_new_male_user:
  - 4ccb789d-4059-41cf-9505-b820579c2b48 # èŒƒå°å§
  - ac021f94-9501-47eb-a7ba-1f626736ec96 # Sandyyyyyyyy
  - 4773f4c4-0272-49e6-a26e-e8317ac3be41 # Michelleçº
  - 767f272b-ac4c-49c8-9eb8-1ceda7836b2e # ç±³è²å©­.KemythiağŸŒ¹
  - 8c60a6e2-78f4-4e1c-9d7e-6ab5f208597b # ä¸€éš»å°ç‹ç‹¸
  - dc76e1f6-4755-4b17-b4ad-6922f9fb1c8e # Chichiç­±æ·‡
  - e1addcc3-641e-4dd8-83a7-e7f508298c36 # FiFiğŸ’•
  - e159354e-ae76-4481-8171-73dd9d06d335 # Kerryé§èŠ®ğŸ’«
  - 4b3866a0-ca9c-484c-9515-d07897f10af0 # å°ç« é­šå…’
  - 3112db4a-8a1c-42fe-affa-00e0dd1e513b # Jasmine.*ä½³æ€æ˜ğŸ¯
  - 61ef9fa3-7c6b-43d5-8569-12a50e7440ff # å¤©å…²
  - 5bd69b10-a6b2-4241-b175-0782596fd706 # ç¨€éŸ³
  - 623188a3-3d65-4221-925d-f2fda7a7f4c9 # ğŸŒºå±±èŒ¶ğŸŒº
  - a082a35f-2f72-4743-887f-b2f4f3fda0c6 # å¿ƒä¹‹è²_å°å°JENNY
  - 021b2d01-c02b-4f70-971e-b33a5601f3eb # èŠ±å¨˜
  - 747246f0-680e-4860-9dae-b3bfb4139418 # å®‰ç„¶ã‚œ
  - 5e3af964-9129-42c5-a8ed-90e363c8b39e # æå¤©å¤©
  - fa0ff7fd-10d1-4a3c-897e-32d36c6ccb28 # è‰¾ç‘ªEmmağŸ’«
  - e12ed114-a5a7-4c9f-a06f-31f6cf27b850 # å®‰æ½”è‰å¨œæ™š
  - 39698627-848b-4d01-a131-49473afc8585 # 77âœ¨
  - b64bb4d3-f164-439c-9d29-095ba73237f6 # æ‰“é›·ä¸‹é›¨æ”¶è¡£æœå•¦
  - e914c9d7-fbca-42a2-9fca-767405d1df8e # è‰è‰çš†è¾›è‹¦ğŸ’¦Lily
  - f235f2c2-3f4e-4fbc-94f4-29228c0db6cc # æ·å§
  - 42686e6b-6640-4da1-9cff-7a70228b2cc2 # ä¹™æ ¼
  - 8e1a23d3-6f30-4e78-8564-8ce966647a62 # é€™è£¡æ˜¯æ˜•æ˜•
  - cbba63e7-05eb-46f4-81c6-de3ebcef3556 # æ©‹ä¸Šæœ‰ä¸€éš»æœ«æœ«ğŸ
  - aeab6a8a-760c-48f7-b69a-1b4eca83f3b2 # Stellastella
  - b6db268b-7309-44c0-9b28-b4d9d25ea51b # è¿·å¦¹å¯ç³ç³–
  - 7b42db74-90ad-4d79-b628-ea868878daaf # å¼€å¿ƒæœ+å°è¾£æ¤’
  - e1310362-09e8-4701-a05e-ddccb0c5899f # ç¾æ¨‚æ«»æ¡ƒ
  - a0661afe-72fe-4d59-ac49-01ba9e75f666 # Celiaæš–å¿ƒé›»å°â¤ï¸
  - 8c8b5008-a3ce-4298-97ba-feb2bddf172e # å·å¿ƒè²è²â™¥ï¸
  - 46d6a400-5aa3-4070-93d9-68cdcf496864 # æ¼ æ¼ æ˜¯æˆ‘
  - be6a1107-282f-4705-9105-0fe145f130e1 # æ°´æ°´ğŸ¿ï¸
  - aa52a37b-a8a3-404f-b1e5-5c23b8781074 # ğŸ†ƒğŸ…²ä¸¸ä¸¸ğŸ¦¢
  - d34b579c-af77-4d4a-b7e2-ee8f4f4fdc1d # ğŸ†ƒğŸ…²æº«æ„›ğ“°ğ“®ğ“·ğ“½ğ“µğ“®
  - fc6af966-6e1c-43bd-aceb-eb84a61037f6 # ğŸ†ƒğŸ…²å°å¤¢å¤¢â¤ï¸
  - 9415b426-6f48-4a70-bced-3b51f3ac1aec # ğŸ†ƒğŸ…²ç‘›çº“â˜€ï¸
  - a6290fe5-3c37-4185-8d63-b66e8647732a # å­Ÿå›NATSUME
  - e399f3b5-c9f8-4817-b3b8-5143f0ec81de # å¾®å…‰ğŸ’«
  - c44f7032-3ded-45c8-9baa-3a07f2fe3f56 # Lulu~~~~
  - 72a9058c-6385-4456-863f-a7913fea909e # ç†Šç†ŠğŸ§¸
  - 9e42c09b-6eaa-4713-8928-2de4546de274 # è‰æLiLee
  - dd83f2ba-c373-4ddb-94a3-529cd6219c1f # 3am.la
  - 4a6ba1e3-7d1c-4314-b0e2-e309584bd927 # Waffle:
  - d045f83a-13bf-4fcc-8e92-8b1c6d414c5f # Lana.CCğŸ°ğŸ“
  - 5b0f9575-cbf6-4ec5-aab9-c61eecf61eab # å¥¶èŒ¶è¦åŠ ç³–
  - 43c9e114-fbe5-4908-857d-fcec71cb84ca # æ³¢æ–¯ğŸŠ
  - aa95e7ea-1695-4237-a3c2-80d9ca2d8dec # ç‰›ç“¶ç“¶
  - 9c5b0fd2-2d9b-43b7-8fca-87146549187c # å’»å’»Ù©(*Â´ï¸¶`*)Û¶
  - b5ec2f6b-cfd0-4305-bdc8-6f7f171a1672 # 08isbear
  - 8baba137-1ae2-4387-b00a-0ca7d5db83e8 # æ˜€éœ
  - 898f94f2-fbaa-4438-8ff8-4b73e2fd5c0c # ğŸ¦‹ğ•ƒğ•šğ•’å¨®
  - e1addcc3-641e-4dd8-83a7-e7f508298c36 # FifiğŸ’•
  - c1cd69a1-0d61-42d8-b8ca-9c8e15633b4f # XiNaâ†»
  - 6253e1a0-c415-4a73-b2e4-39f196c973e7 # çŸ­é«®å¦–ç²¾é›™é›™
  - d736c541-fefb-4328-908f-4a05310c785e # éœéœğŸ’‹
  - 35d1c04b-aac9-46bd-9e92-76594fa6629f # ğŸ‘’ç±³ç¾…ğŸ¡
  - 86a82e91-7d2f-434d-b562-c430a718e1ad # momoå§å§
  - aabf4dcd-2f2e-4e5c-9308-91b967977cad # ğŸ†ƒğŸ…²ğŸ’™ç¶­å¨œ
  - f8e87d80-4b72-479b-8603-adbb1c580ebd # ğŸ†ƒğŸ…²æ·‡æ·‡ğŸ¥
  - c9dfcd90-6bcc-482b-853e-7fd17071a38e # ğŸ†ƒğŸ…²âœ¨å’˜å¨˜å¨˜â£ï¸
  - d39a66e8-1062-488f-a388-18019ddcaaca # Little Crystal
  - d31cc760-226a-4e36-a8f2-79afb4cf3ee3 # å°èŒç“œ.ğŸ­
  - 7edcbba6-9b57-4878-a2c4-36f45aa7dcd2 # Zhen_09
  - 48606856-9924-462a-8daf-217bb97e3ddc # Miss.Luoæ´›å°å§
  - 26c7a01e-08b9-4656-9b44-37c1b559180a # Reneeâ€ ///è‰¾ç³
  - d3d5f4dc-60e3-444b-ae0a-8ce1b631a7e0 # â™¡Anniâ™¡
  - 9ff1d605-edf2-49a9-b34f-e77f73245e72 # å“‡å¡å¡
  - 871f7fa9-15dc-4ff8-a1b5-f38cbf883da4 # Yunjuå°å¦‚
  - 334c12bc-7c95-4fb9-8e28-ae0e9a66ce82 # å®‰ç–AnjiuğŸ¤
  - b384359d-64db-4d0e-ae69-1a332c3c6c35 # ç³¯ç³¯åº•åŠ 
  - f8d3bad5-2699-4067-9416-6900f51caadc # æ²«æ²«ğŸ§
  - 159ac1df-bc4e-43e1-934b-cdb17006a988 # é¬¼ç­†æ˜¯ä¸€ç¨®è‡
  - 5059aaef-4a71-49d5-b61c-70d5f8f363ff # ğ’Ÿğ’¶ğ“ƒä¸¹
  - 4472920e-d66f-4ef8-948f-fa8e04de2b54 # ğŸ†ƒğŸ…²ç¬‘ç¬‘ğŸ˜›
  - c1af8b95-cbc4-4df6-a575-0ab76d648b52 # KimyğŸ»
  - 7734d06e-36c7-4a15-9ec0-f2c4f992f8d3 # YuuuğŸ¶
  - 05e886b2-9f71-4b3d-a337-cb5e537cad6f # Naaaaaa
  - 1b34aba9-c6d4-4cbb-bcfd-7e710326bcbe # oè–”è–‡o
  - d3c44590-8c9a-4ee1-b005-eb011806c588 # *Universe*
  - 4f932b63-55ae-4021-b4bc-e06fb6040e73 # Twinkle_
  - dae178f1-7899-4912-8e70-7b4639b712de # æœ¨æœ¨â˜¾ï¸
recommend_streamer_ids_for_new_female_user:
  - cb46a35f-0ae6-487c-aad3-ea3ff5b8c838 # å¾®ç¬‘æ™´å¤©
  - 6443a434-4e3c-47c9-b59a-6f408a51e144 # æ´›Â·å…‹
  - b9a75dc0-1763-4ecf-b739-e20767b85b04 # ç‹å“ˆå“ˆ
  - 955ae13c-be83-4e0a-9b9f-4f47c2c1ae66 # ä¸ƒæ˜Ÿè¶…æ·¡_
  - 6a1e7e31-29ae-4d5f-af91-f4d2b2601e9d # é˜¿ç™½Coral
  - 96949ac0-62ca-469d-b7cf-a40206952060 # å¾·å¾·RyderğŸ·
  - 5265b2c9-5046-4950-8b31-69969ae0c230 # ğ“¡Â·ä¸¸
  - 5150cc3c-baa5-48a3-86b4-f3494b9a414e # BANJI
  - 6e304d69-0c33-4028-ac9a-47cd39c5729b # æ‰é‚Š
  - cb63a180-152d-4b59-aba3-002019d5e05d # å°ç‘R.A.E
  - 4c2f1478-9ec6-4dfc-82e6-09d6f3667167 # è«­ç©ğŸ§yoyo
  - 55dec144-8209-4747-9e4b-faa1fbcbde71 # æ·ºæ†¶å¢¨æ®¤
  - 11f4a2df-c804-4edd-a5b7-e4af5c5c298e # é™³æ–¯æ©
  - 40c13437-f27f-4e6c-8c82-69945151ba46 # æ±Ÿå¤©èƒ¤TinChiang
  - 8a1190db-9fc4-42d6-a8b9-6ac82212410e # á´€sÊœá´‡é˜¿å°„
  - cef35c7b-d8f6-4929-a112-7e2927c3cb08 # 10011101
  - a1bdb220-71af-4b95-9afc-b50cdddf2563 # å•Ÿç¨‹
  - f09db2f9-a13b-45c1-881f-d4150b132b1c # ä¸‹ç­çš„æ™®é€šä¸Šç­æ—Jams
  - 7a14c76f-576c-4002-befb-8cad59fcb057 # å°å¯†ç¾ŠğŸğŸ¤âœ¨
  - 8baaba2a-069f-4349-aa05-c00f7519c66d # å±±å§†_Sam
  - d92916b3-e58d-4174-8926-6785ded4f33c # æ™šå®‰é›»å°
  - f020fcd6-538c-40e6-82d5-fe8b05867303 # é¦™æ°´å°å“¥
  - cfdf9ccc-55a7-4a9f-a4fa-a4bcd091bd28 # æ±Ÿå¾®é¢¨çš„æ—…è¡Œ
  - 69c26d00-79b3-4ce6-9d8a-81df95e292a2 # á´¡ÊœÉªá´›á´‡æ‡·ç‰¹
  - e1eb9635-13cb-4765-bf0c-6a4d3865c9ee # æ°´ç“¶åº§â™’ï¸
  - 220e89ed-330e-4b7b-a6e2-11a61636aa77 # å†·å†·å¿ƒä¸Šäºº
  - d2f8dc92-3822-4153-afaf-6cbdb165cc00 # å°æƒ…æ­ŒH.KğŸ¾ï¸
  - a946156f-7d3e-4f13-831c-a24c0e28a8c2 # ç½¡é‘’
  - f2111e29-1151-45d9-848e-197b341f1add # ç©å…·à² _à² 
  - eda5b79a-9d8d-429b-bb2c-74205750df2a # âœ¨DALEæˆ´çˆ¾ğŸ’„ğŸ¤âœ¨
  - ed6a3bda-9ed4-4c3e-8faf-e8696d662d28 # AllenTalk
  - 3314850e-ce3a-4a64-9997-9fa3ba955269 # ä½›ç³»å°å“¥å“¥Leo