recommend_threshold: 300
recommend_streamer_ids_for_new_male_user:
  - 4ccb789d-4059-41cf-9505-b820579c2b48 # èŒƒå°å§
  - 767f272b-ac4c-49c8-9eb8-1ceda7836b2e # ç±³è²å©­.KemythiağŸŒ¹
  - e159354e-ae76-4481-8171-73dd9d06d335 # Kerryé§èŠ®ğŸ’«
  - 3112db4a-8a1c-42fe-affa-00e0dd1e513b # Jasmine.*ä½³æ€æ˜ğŸ¯
  - 61ef9fa3-7c6b-43d5-8569-12a50e7440ff # å¤©å…²
  - 5bd69b10-a6b2-4241-b175-0782596fd706 # ç¨€éŸ³
  - 021b2d01-c02b-4f70-971e-b33a5601f3eb # èŠ±å¨˜ğ“¯ğ“µğ“¸ğ”€ğ“®ğ“»ğŸ•Šï¸
  - 747246f0-680e-4860-9dae-b3bfb4139418 # å®‰ç„¶ã‚œğ“ªğ“·ğŸ¦‰
  - 5e3af964-9129-42c5-a8ed-90e363c8b39e # æå¤©å¤©
  - fa0ff7fd-10d1-4a3c-897e-32d36c6ccb28 # è‰¾ç‘ªEmmağŸ’«
  - 39698627-848b-4d01-a131-49473afc8585 # 77âœ¨
  - 8e1a23d3-6f30-4e78-8564-8ce966647a62 # é€™è£¡æ˜¯æ˜•æ˜•
  - cbba63e7-05eb-46f4-81c6-de3ebcef3556 # æ©‹ä¸Šæœ‰ä¸€éš»æœ«æœ«ğŸ
  - b6db268b-7309-44c0-9b28-b4d9d25ea51b # è¿·å¦¹å¯ç³ç³–
  - 8c8b5008-a3ce-4298-97ba-feb2bddf172e # å·å¿ƒè²è²â™¥ï¸
  - 9e42c09b-6eaa-4713-8928-2de4546de274 # è‰æLiLee
  - dd83f2ba-c373-4ddb-94a3-529cd6219c1f # 3am.la
  - 4a6ba1e3-7d1c-4314-b0e2-e309584bd927 # Waffle
  - d045f83a-13bf-4fcc-8e92-8b1c6d414c5f # Lana.CCğŸ°ğŸ“
  - 5b0f9575-cbf6-4ec5-aab9-c61eecf61eab # å¥¶èŒ¶è¦åŠ ç³–
  - 43c9e114-fbe5-4908-857d-fcec71cb84ca # æ³¢æ–¯ğŸŠ
  - 9c5b0fd2-2d9b-43b7-8fca-87146549187c # å’»å’»Ù©(*Â´ï¸¶`*)Û¶
  - b5ec2f6b-cfd0-4305-bdc8-6f7f171a1672 # 08isbear
  - 26c7a01e-08b9-4656-9b44-37c1b559180a # ğ—¶ğ—¥ğ—²ğ—»ğ—²â€ è‰¾ç³
  - 9ff1d605-edf2-49a9-b34f-e77f73245e72 # å“‡å¡å¡
  - 871f7fa9-15dc-4ff8-a1b5-f38cbf883da4 # Yunjuå°å¦‚
  - 7734d06e-36c7-4a15-9ec0-f2c4f992f8d3 # æ…ˆæ…ˆğŸ¥„â¤ï¸ğŸ¶
  - 4f932b63-55ae-4021-b4bc-e06fb6040e73 # Twinkle_
  - 19f77cbc-7609-448d-919d-6849d4b3981b # åš•åš•*
  - 3f8c7833-6ed0-4192-bb76-5fa71e1416bc # éœ²éœ²å¦®
  - 3003f127-bf55-4759-b710-fcc51b04e1d9 # G.A.O
  - c33fd588-9f9b-4f32-b234-972f1d2a6b31 # å–®çœ¼çš®å–®å–®
  - 63988abe-8570-40cc-974c-c3a0d0244e40 #å°å­«ğ“¢ğ“¾ğ“·ğŸ¤
  - 4622fd03-acbd-49ad-9a31-6b665f5174c1 # å¹¸é‹ğŸŒŸ
  - 5dae7887-004d-4b8c-80ce-9e24cb0d7419 # å®‰èˆçµ²
  - 74823cbc-6382-411b-88c6-8d2dc6b2dbfe # Jessicaâ¤ï¸Ng
  - 74215dc9-3f4e-4659-a796-2cb874baaebf # ğŸ¦©è‹¥æœ‰å¤¢ğŸ€
  - 39300774-31f6-4c31-a4e7-31a3bf9cc20a # å¦å¦å¤©ä½¿
  - eb90f389-6dd0-4876-b2cf-0d1d5741dc26 # æ„›åƒç³–ã®ç³–ğŸ­
  - 0b3d40cf-64fb-4aea-ac13-8f16ac2e6352 # ğŸºä¸æƒ³åšå¤¢çš„å­Ÿå…’
  - e95f097a-2559-4052-8945-4602316b6610 # äºˆå¿
  - 75299eb1-935d-4765-9725-8837c2adc191 # å°è¢ç«ğŸ¦‹ğŸ¤
  - 0f7d76e6-ba96-44ae-8bdb-68a67ee5d95f # ğŸŒ™æœˆå…‰ä»™ä»™âœ¨
  - 8159d9fb-7116-41c7-9f9d-2e0ed0ffb405 # ğŸŒ™rabbitğŸŒ™
  - 88385832-bff8-4721-9209-b345bbecd4cf # å·§é”ğŸ§€ä¸€å¡Šèµ·å¸
  - 3d910a8e-cd03-4cde-81fb-5efb9a992554 # ğŸ¦•å§œå§œğŸ¦•
  - 56d436fe-1343-4503-9bd8-674f38a087e3 # é»èŠ½ğŸ­
  - 65531ba9-d10c-40c4-b802-ee4e42a3ead7 # ç‹ç‹¸è²
  - f61caf82-ba24-4254-8dff-428eafdb74fd # çå¥¶å¾®å¾®ğŸŒ¸
  - e37df05a-0fe2-46cf-bf7f-a8c6b63f79e0 # ğ¶ğ‘™ğ‘ğ‘–ğ‘Ÿğ‘’âœ°å…‹èŠå…’ğŸ’
  - 00322d87-8cd1-4c96-ba3f-d430461921e9 # é™½å…‰å°å…¬ä¸»ğŸ‘¸
  - 585fc765-d16c-4fcd-868b-acc15b1108f7 # è…«æ‹‹æ‹‹
  - b17d7b2e-761c-47e5-8989-5f01e1681d94 # è±( *ê’³Â´ * )âƒ•â†
  - 96bfcd32-6ea9-4075-b933-60fdb261f009 # å¤§é–‹å¿ƒ
  - 54198bef-ee07-426c-90ef-41f7101a7315 # è±ªçˆ½äººå¦»
  - b17d7b2e-761c-47e5-8989-5f01e1681d94 # è±( *ê’³Â´ * )âƒ•â†
  - a0d20512-e134-4c72-8826-2f680316da54 # è½‰å•Šè½‰å•Šè½‰âœ¨
  - 652b45d8-5f02-481c-a0d2-a14567f22a19 # æ‹‰ç†Š
  - cbab1779-2a8f-43a0-b6e5-13e9233bfe07 # EraserğŸ¤¡çš®çš®
  - 91b3779c-d990-49ea-b7fe-fff397241bdc # å“ˆå¨œæ²’æœ‰è‚¥è‚šå­
  - d14ea65f-9de6-4f9e-966a-c4dcc7a34344 # è²è²ï¼šï¼‰
  - 3072c4dc-9ac4-486f-80ca-6e20ee98d3a9 # æ‡¶æ‡¶ä¸¸
  - 9d7ef4d9-c6ce-409e-b2d8-945a63ec737c # éœ²å¨œğŸŒ™Luna
  - ffcae4c9-6b37-45be-8850-b32b9799c23a # å‘†ã„¦é¦¨é¦¨
  - 94d466a9-85f1-41e5-8e50-ec4b498fea30 # é™½å…‰çš„summer
  - e159354e-ae76-4481-8171-73dd9d06d335 # Kerryé§èŠ®ğŸ’«
  - 9ff1d605-edf2-49a9-b34f-e77f73245e72 # å“‡å¡å¡
  - 1814af5b-9321-4a1c-9d73-298ab45c01f0 # æ˜¯æ·¨å¦ å–ğŸŒˆ
  - 6165f09f-511f-4b5a-a5de-5197e17cdbb1 # ç™½ç™½á´®á´®á´¬á´µ
  - 3dfc4067-5286-4a03-9df4-be3b94d750af # ğŸŒ¹ğŸŒ¼AliceğŸŒ¼ğŸŒ¹
  - 601a9f94-8527-4737-909d-70b0a9bfe800 # æ½”å…’ba
  - 055031e3-e8f5-4b6e-b493-ab5e671dc15d # å°èŠ±ğ–¡¼.ğ–¤£ğ–¥§
  - ae17cd1f-3d2b-42bf-a168-f2a12b032007 # å§Šçš„æº«æŸ”é¤µç‹—äº†ğŸ¶
  - de5a8d5b-76c8-43fb-92fa-803d709b3f3a # FÃ¼è¶
  - 859e487a-9b59-4a99-80a9-d4484d10f6f9 # My.å°è¿·ç³Šè•¾è•¾â˜ºï¸â˜»
  - 0e66fd9f-3856-45b4-be4a-4f2e80f48092 # æ³¢éœ¸å¥¶èŒ¶å¾®å¾®
  - b7e1af38-effc-4c46-a3d3-4b7e5b5033f2 # è‹­è‹­â¤ï¸
  - 4ad60391-a403-40f8-9e76-df47182db0ba # âœ¨â­ï¸æ„›èœœè‰äºâ­ï¸âœ¨
  - aef781e7-a306-46cc-b71d-c8a4764cb018 # å°å®‰_Annn
  - ad0bc96c-1ac6-4be9-8bf4-319fe9963a80 # äºå­@Ako
  - 262f470a-4514-49af-bb72-9dfbf8d31f03 # ç¥ä»™é­š
  - bda7c412-e218-4999-bd93-6ad60614561d # Myco
  - aba3742f-78a4-472b-b741-f355d40edd78 # ç¹ç±³èŒ¶
  - bd39f803-4689-4db8-b370-a310cd4329f2 # æƒ³åˆ°å’ªå’ªè²“è²“
  - 17c6f9df-6151-4220-9e5c-1049204640e4 # æ„›åƒé¬¼00
  - 44d2293c-d2e9-411a-82b5-9bf46993790b # nanağŸ’œğŸ’œ
  - 75b3088f-1a22-4256-b530-c41272e7af8e # å¯æ‘Ÿä»¥â„‚ğ•™ğ•ğ• ğ•–ğŸ’«
  - 165e6090-37dc-4903-b026-a2514c99fa7a # æ‚ æ‚ æ„›åƒç³–
  - 4f9420ad-2bdc-4228-93bd-7e02ee039758 # æŠ±èµ°å¯§å¯§
  - a0d187e1-3fbc-4ba6-b0c5-98fc7ea2df04 # ğŸ£é­šå…’é­šå…’è·¯ä¸Šèµ°ğŸŸğŸŸ
  - fb7aa786-4b4e-42ab-b2e6-3e0397f3a953 # æ±äº¬ã®æ³¢å¦
  - d471cdf0-54a1-4df3-8322-9efea7e12ad1 # æ¯”å®‰ğŸ¤
  - 81f9f32a-8ecd-4a41-8fa6-f0f87a77dcd6 # èŒ‰è‰èèğŸŒ¹
  - 30b6a32b-33df-471f-be42-eaecf9fa487f # ç™½æ²ğŸ
  - a066a03b-8b45-4112-b68c-e44f2d7c9824 # é›²ã„¦é£„é£„â˜ï¸
  - 2e1e5025-63fa-4d87-a955-272fe620cb3e # ç‘œğŸ¥€
  - 029cf38c-d8ab-48f0-a76c-5714a1721df4 # Lilyè€ç‹ç‹
  - 159d2798-0415-40ec-a501-9138100e70a5 # æœ¨é ­å…’
  - 440d07cc-a8a5-481c-a93b-5d7c6be2ad9f # é€¸ç·£
  - dbccf583-f3af-4e3e-9b92-af83c66d59d5 # æ‘³æ‘³å“©æ‘³
  - 64880b32-bd5a-4444-aa21-5a5909af36ef # æ°åŒ—åŒ—ã€†Yuié†¬
  - 71eff6e9-6662-4e68-a62f-05263b698f5a # å°æ¡ƒæ°£ğŸ‘Eva
  - 69dde179-5348-473b-a2fb-7ec567ca3090 # Rebeccayu
  - 99304123-c5d3-4caf-9703-5c2e915641ee # èŠ¯èªâ˜•ğŸ¶
  - d9402c8c-bdf5-462c-a4f9-731ebddc3592 # Eä¾ğŸŒ»
  - a66fc7b1-9885-4624-b5ea-6efcba324f57 # å°è¿·é¹¿ğŸ¦ŒğŸŒ·
  - 82a56008-bb85-4f0b-acef-f54df9b13ccd # ç±³åˆ©å…’ğŸ¤
  - 7ea113d8-9f08-4935-8702-2cd0f7bb423c # ğŸ«§ä¹çˆºğŸ«§
  - 2426ad3b-925c-4ef1-a9cd-7466034fdf6d # ğŸ‚ç’ç‹ï½¡o
  - 1343732d-6fad-4a81-8b45-11371f83ab1f # ğŸ§¸å”¯è–°ğŸ§¸
  - a6caf9e3-9ad3-4177-8158-312dd2e6b19b # é¦™çµ²
  - 9d12c1df-c79e-494b-a21b-46a3d4d883fd # é¡é ­
  - cb368bc1-f308-4a01-91c2-f1c2057f611a # WEMO
  - 955aa556-61a4-4d7e-b966-d91c435a7a73 # áµ•ÌˆHaru áµ•Ìˆ
  - 23df4032-6dee-4958-b22e-8d78210b9c2a # å°é»‘å¤§è‡‰éŸ³æ¨‚penny
  - 7ea0226d-1da7-4d29-9649-eec410b5cfd1 # æµ·è‰è—»
  - f4c24d2f-fd4f-46e0-8b5e-9d2cc1349f37 # æ·‡æ·‡çš„piano-barğŸ¹
  - 1b53bb99-bfd3-4c80-9e69-a81c3cb66d14 # Bellaå°è²

recommend_streamer_ids_for_new_female_user:
  - 6443a434-4e3c-47c9-b59a-6f408a51e144 # æ´›Â·å…‹
  - 5265b2c9-5046-4950-8b31-69969ae0c230 # ğ“¡Â·ä¸¸
  - 5150cc3c-baa5-48a3-86b4-f3494b9a414e # BANJI
  - 6e304d69-0c33-4028-ac9a-47cd39c5729b # æ‰é‚Š
  - cef35c7b-d8f6-4929-a112-7e2927c3cb08 # 10011101
  - 7a14c76f-576c-4002-befb-8cad59fcb057 # å°å¯†ç¾ŠğŸğŸ¤âœ¨
  - 69c26d00-79b3-4ce6-9d8a-81df95e292a2 # á´¡ÊœÉªá´›á´‡æ‡·ç‰¹
  - a946156f-7d3e-4f13-831c-a24c0e28a8c2 # ç½¡é‘’
  - eda5b79a-9d8d-429b-bb2c-74205750df2a # âœ¨DALEæˆ´çˆ¾ğŸ’„ğŸ¤âœ¨
  - b5784c30-0e78-43c5-8bcc-149967db7910 # é…¥é…¥ğŸª
  - 297446d2-7a58-4b15-8963-856bc2013e9e # ä¸¹å°¼DannyLiu
  - 75bf28dc-8537-4894-ab20-5a1a9ddac834 # ç±³å‹’å…ˆç”Ÿ
  - 3d61c0ac-dcf4-4313-9f09-b81e75d112d8 # é»ƒæŸéŸ¶
  - 2755b593-8009-41df-8e38-0a2cd3b592db # é€é‡æ©ŸğŸï¸
  - 05b27ac2-2b1b-48d7-bcb5-a3f1ef01bba9 # è€é™½ğŸ”†
  - 0e8fd624-0429-456e-9a6d-a86ab2b1d258 # æ³°ç‘Terry
  - 1cd50ea6-447f-4b70-9a84-4496453cd5a7 # è²“å’ªå¯æ„›
  - 7e3c319d-a589-4953-8e96-1d24a0e22b51 # è‰¾è¿ªå ¤å‚‘â™«
  - cef35c7b-d8f6-4929-a112-7e2927c3cb08 # 10011101
  - 08c0f375-689f-4b93-bd28-9e75bf17b152 # lok_coversong
  - d0031321-da54-445b-b62b-b9dcb71de005 # æ™šå®‰ğŸŒ™
  - 68a03e48-e25e-43a7-aa69-0f2add80f0f4 # oliverobey
  - 27911e82-9d35-4e3e-866d-3dce5c739afe # å¥¶å­å»Ÿå»Ÿå…¬
  - 220e89ed-330e-4b7b-a6e2-11a61636aa77 # å†·å†·å¿ƒä¸Šäºº
  - 506e737c-f712-453c-956d-9cdbdfa7872a # Carolç³–ç³–
  - b9ab581c-34c2-4a40-b213-de5b170883c0 # GUIğŸ¢
  - 428ac2eb-b72a-459e-87fe-5aec46ef3ff3 # æ™ƒå”
  - 100ba908-2857-4276-9a75-8b119b5402dd # EricğŸ©
  - 2336656b-6cd4-48e3-a871-8d03e4df4bbd # å‚·éš¨æ™‚é–“æ…¢æ…¢æ·¡å»
  - 37ac75e8-95b1-4cf9-8349-8ccecce14f74 # KË™ğƒ·Ë™
  - 7a2840f8-0534-4398-8d6e-a7282cae8333 # æ·¡æ·¡çš„ç°ç°
  - 96d3c5e1-35f8-47f8-9776-d73492c25c67 # Jameså å§†é…¥
  - 2e1e5025-63fa-4d87-a955-272fe620cb3e # ç‘œğŸ¥€
  - 029cf38c-d8ab-48f0-a76c-5714a1721df4 # Lilyè€ç‹ç‹
  - 159d2798-0415-40ec-a501-9138100e70a5 # æœ¨é ­å…’
  - aba5805e-5937-42de-84c2-113f642fabfe # é€¼é€¼æ¬¸
  - 440d07cc-a8a5-481c-a93b-5d7c6be2ad9f # é€¸ç·£
  - 494a617a-9793-4d8c-9750-8fe42368b164 # VCå°å§œ
  - 30e5bf5b-ddb1-41d7-9de7-6054db3b5453 # æ¤°å£³ğ‘ºğ’ğ’–ğ’ğŸ¥¥
  - 6455ef6e-55a2-4244-b6ad-ee5ed61ad70b # å¢¨æ˜æ£‹å¦™ğŸˆ
  - b93cc519-b66f-4614-ade7-4a49e35a1957 # å¯¦æ¬£
  - e53e410c-5105-4c03-99a4-14a03ebefb57 # å°é¬¼æ ¼æ ¼ğŸ‘»
  - 98087126-d226-4d5c-a487-451538883df5 # Ê€Éªá´„á´‹Êà½¼
  - f448dc62-08d2-4954-84ce-96959c1a4a1d # ä¸Šå¿ƒğŸ™
  - eef3e10b-d897-436a-9ed0-3c4100ebae48 # Vçˆ¾æ£®
  - 4bffb287-a084-448c-8c0f-8bebf5f006b2 # æˆ‘æ˜¯å“ˆå£«å¥‡
  - e9786b8c-9410-4668-af3b-c914ab4def98 # ä¹ä¸€å…­
  - c7ea4091-1680-47e6-a7e0-a14fbc6bee1c # KTğŸ©
  - 559c3db3-2f6a-4c21-8d69-061a5de00a31 # yellowğŸ’¡
  - b9d1700b-d3a4-4738-9047-45a85dc0abb3 # å®‰å®‰éœéœæ·¡æ·¡
  - 2bae0757-04e8-4701-8a35-01d602b93cc7 # ğŸ¼ğŸ¸å½ˆå”±MarkğŸ¸ğŸ¤
  - 56f880a8-a75d-4eb0-8372-89078bdd998f # å–µå‰