recommend_threshold: 300
recommend_streamer_ids_for_new_male_user:
  - 4ccb789d-4059-41cf-9505-b820579c2b48 # èŒƒå°å§
  - ac021f94-9501-47eb-a7ba-1f626736ec96 # Sandyyyyyyyy
  - 4773f4c4-0272-49e6-a26e-e8317ac3be41 # Michelleçº
  - d14d0d92-904d-4c2d-9739-b1fdd3932460 # å¤©ç±Ÿå‚»çâ¤ï¸
  - 767f272b-ac4c-49c8-9eb8-1ceda7836b2e # ç±³è²å©­.KemythiağŸŒ¹
  - 8c60a6e2-78f4-4e1c-9d7e-6ab5f208597b # ä¸€éš»å°ç‹ç‹¸
  - dc76e1f6-4755-4b17-b4ad-6922f9fb1c8e # Chichiç­±æ·‡
  - 3c70e312-bc7e-47cf-8c64-0b2e9a31c977 # è²è²æ¯”
  - 2589c116-fafd-4839-a7df-e049130e391a # ç™‚ç™’å¥³è²_èœ»èœ“Valen
recommend_streamer_ids_for_new_female_user:
  - cb46a35f-0ae6-487c-aad3-ea3ff5b8c838 # å¾®ç¬‘æ™´å¤©
  - 1d64b4da-33af-4ccb-b637-e2fef18683f0 # å£«è»’ğŸ¤
  - 6443a434-4e3c-47c9-b59a-6f408a51e144 # æ´›Â·å…‹
  - 75bf28dc-8537-4894-ab20-5a1a9ddac834 # ç±³å‹’å…ˆç”Ÿ
  - b9a75dc0-1763-4ecf-b739-e20767b85b04 # ç‹å“ˆå“ˆ
  - 955ae13c-be83-4e0a-9b9f-4f47c2c1ae66 # ä¸ƒæ˜Ÿè¶…æ·¡_
  - 6a1e7e31-29ae-4d5f-af91-f4d2b2601e9d # é˜¿ç™½Coral
  - 4e6f7c43-0add-4820-8936-6caddbb4fa74 # é›è±¬ç‰›ç‰›ç¾Š
  - 96949ac0-62ca-469d-b7cf-a40206952060 # å¾·å¾·RyderğŸ·