recommend_threshold: 300
recommend_streamer_ids_for_new_male_user:
  - 4ccb789d-4059-41cf-9505-b820579c2b48 # èŒƒå°å§
  - ac021f94-9501-47eb-a7ba-1f626736ec96 # Sandyyyyyyyy
  - 4773f4c4-0272-49e6-a26e-e8317ac3be41 # Michelleçº
  - 767f272b-ac4c-49c8-9eb8-1ceda7836b2e # ç±³è²å©­.KemythiağŸŒ¹
  - 8c60a6e2-78f4-4e1c-9d7e-6ab5f208597b # ä¸€éš»å°ç‹ç‹¸
  - dc76e1f6-4755-4b17-b4ad-6922f9fb1c8e # Chichiç­±æ·‡
  - 3c70e312-bc7e-47cf-8c64-0b2e9a31c977 # è²è²æ¯”
  - 2589c116-fafd-4839-a7df-e049130e391a # ç™‚ç™’å¥³è²_èœ»èœ“Valen
  - e1addcc3-641e-4dd8-83a7-e7f508298c36 # FiFiğŸ’•
  - e159354e-ae76-4481-8171-73dd9d06d335 # Kerryé§èŠ®ğŸ’«
  - 4b3866a0-ca9c-484c-9515-d07897f10af0 # å°ç« é­šå…’
  - 3112db4a-8a1c-42fe-affa-00e0dd1e513b # Jasmine.*ä½³æ€æ˜ğŸ¯
  - 61ef9fa3-7c6b-43d5-8569-12a50e7440ff # å¤©å…²
  - 5bd69b10-a6b2-4241-b175-0782596fd706 # ç¨€éŸ³
  - 623188a3-3d65-4221-925d-f2fda7a7f4c9 # ğŸŒºå±±èŒ¶ğŸŒº
  - a082a35f-2f72-4743-887f-b2f4f3fda0c6 # å¿ƒä¹‹è²_å°å°JENNY
  - 021b2d01-c02b-4f70-971e-b33a5601f3eb # èŠ±å¨˜
  - 747246f0-680e-4860-9dae-b3bfb4139418 # å®‰ç„¶ã‚œ
  - 5e3af964-9129-42c5-a8ed-90e363c8b39e # æå¤©å¤©
  - fa0ff7fd-10d1-4a3c-897e-32d36c6ccb28 # è‰¾ç‘ªEmmağŸ’«
  - e12ed114-a5a7-4c9f-a06f-31f6cf27b850 # å®‰æ½”è‰å¨œæ™š
  - 39698627-848b-4d01-a131-49473afc8585 # 77âœ¨
  - ad10575b-6e8f-4f35-ad76-7ed9913a62d9 # å¤œè²“å­kikid
  - 4cbde9fd-4273-438f-a9d0-96839de41905 # ğŸ’œå…«åˆ†ç³–å»å†°âš—ï¸Â·Ì«âš—ï¸
  - 2bd10fc4-50dc-4144-9350-83c6d8379aa4 # Josanneç–å§—
  - c96b5482-25a3-4a54-96f6-5e08c25a64c5 # CCğŸ‹å¯§èŒ
  - 5c1e3912-3d6d-42b2-91b3-128156f74013 # Uniæ‚ å¦®â¸œ(*ËŠá—œË‹*)â¸
  - 9fa5c3e2-49e9-4cbe-b499-660aa4afad8e # å¾å¨œShena
  - fc9a7077-6145-4186-a068-5a998b5eeef5 # è‡ºå…­ç”²å¥¶å§¬
  - 2159bab4-6e2b-41df-b298-d62cf85d4ca1 # LoatheRT
  - b64bb4d3-f164-439c-9d29-095ba73237f6 # æ‰“é›·ä¸‹é›¨æ”¶è¡£æœå•¦
  - e914c9d7-fbca-42a2-9fca-767405d1df8e # è‰è‰çš†è¾›è‹¦ğŸ’¦Lily
  - f235f2c2-3f4e-4fbc-94f4-29228c0db6cc # æ·å§
  - 06b21d23-3682-4131-971b-d16cd58920ea # Jou_
  - 42686e6b-6640-4da1-9cff-7a70228b2cc2 # ä¹™æ ¼
  - e0fcf33a-494a-4dc4-a29b-5b04d6bb8afb # é¾èˆŒè˜­æ—¥å‡º
  - 8e1a23d3-6f30-4e78-8564-8ce966647a62 # é€™è£¡æ˜¯æ˜•æ˜•
  - cbba63e7-05eb-46f4-81c6-de3ebcef3556 # æ©‹ä¸Šæœ‰ä¸€éš»æœ«æœ«ğŸ
  - aeab6a8a-760c-48f7-b69a-1b4eca83f3b2 # Stellastella
  - b6db268b-7309-44c0-9b28-b4d9d25ea51b # è¿·å¦¹å¯ç³ç³–
  - 7b42db74-90ad-4d79-b628-ea868878daaf # å¼€å¿ƒæœ+å°è¾£æ¤’
recommend_streamer_ids_for_new_female_user:
  - cb46a35f-0ae6-487c-aad3-ea3ff5b8c838 # å¾®ç¬‘æ™´å¤©
  - 6443a434-4e3c-47c9-b59a-6f408a51e144 # æ´›Â·å…‹
  - b9a75dc0-1763-4ecf-b739-e20767b85b04 # ç‹å“ˆå“ˆ
  - 955ae13c-be83-4e0a-9b9f-4f47c2c1ae66 # ä¸ƒæ˜Ÿè¶…æ·¡_
  - 6a1e7e31-29ae-4d5f-af91-f4d2b2601e9d # é˜¿ç™½Coral
  - 96949ac0-62ca-469d-b7cf-a40206952060 # å¾·å¾·RyderğŸ·
  - 1e681ef1-c0a8-4c5f-8e7a-7f20e45c2b83 # JOKERç§‹å¤©é–‹çš„æ¥“
  - 4f487a33-5646-4da2-ad23-2ffa3afe0bee # Twiceçš„å°¼å§‘
  - 5265b2c9-5046-4950-8b31-69969ae0c230 # ğ“¡Â·ä¸¸
  - ff068cc8-14c7-4505-bd8b-37f0c9503acb # å½ˆå”±å°‘å¹´ğŸ¸å–†
  - 50afc790-ca90-479b-91b9-91cb92e85cb9 # â­ï¸é–‹æ©Ÿç©å®¶ğŸŒ™
  - 5426e3a3-fc90-448d-a0c5-3fc6294c0bf9 # ğŸŒ§ï¸é›¨ä¸­ç´äººğŸ¹Rain
  - abf3b68a-bbb2-4f23-891b-5bcfef8975d0 # å¥§æ¨‚åŠ 
  - 5150cc3c-baa5-48a3-86b4-f3494b9a414e # BANJI
  - 6e304d69-0c33-4028-ac9a-47cd39c5729b # æ‰é‚Š
  - cb63a180-152d-4b59-aba3-002019d5e05d # å°ç‘R.A.E
  - f31c3e10-f820-4025-9241-3d2986a42ee3 # å¤æ¥“
  - 4c2f1478-9ec6-4dfc-82e6-09d6f3667167 # è«­ç©ğŸ§yoyo
  - 55dec144-8209-4747-9e4b-faa1fbcbde71 # æ·ºæ†¶å¢¨æ®¤