recommend_threshold: 300
recommend_streamer_ids_for_new_male_user:
  - 767f272b-ac4c-49c8-9eb8-1ceda7836b2e # ç±³è²å©­.KemythiağŸŒ¹
  - 3112db4a-8a1c-42fe-affa-00e0dd1e513b # Jasmine.*ä½³æ€æ˜ğŸ¯
  - 61ef9fa3-7c6b-43d5-8569-12a50e7440ff # å¤©å…²
  - 5bd69b10-a6b2-4241-b175-0782596fd706 # ç¨€éŸ³
  - 747246f0-680e-4860-9dae-b3bfb4139418 # å®‰ç„¶ã‚œğ“ªğ“·ğŸ¦‰
  - 5e3af964-9129-42c5-a8ed-90e363c8b39e # æå¤©å¤©
  - fa0ff7fd-10d1-4a3c-897e-32d36c6ccb28 # æ±ŸèŠ¯ğŸ’
  - 8c8b5008-a3ce-4298-97ba-feb2bddf172e # å·å¿ƒè²è²â™¥ï¸
  - 9e42c09b-6eaa-4713-8928-2de4546de274 # è‰æLiLee
  - 4a6ba1e3-7d1c-4314-b0e2-e309584bd927 # Waffle
  - d045f83a-13bf-4fcc-8e92-8b1c6d414c5f # Lana.CCğŸ°ğŸ“
  - 5b0f9575-cbf6-4ec5-aab9-c61eecf61eab # å¥¶èŒ¶è¦åŠ ç³–
  - b5ec2f6b-cfd0-4305-bdc8-6f7f171a1672 # 08isbear
  - 26c7a01e-08b9-4656-9b44-37c1b559180a # ğ—¶ğ—¥ğ—²ğ—»ğ—²â€ è‰¾ç³
  - 9ff1d605-edf2-49a9-b34f-e77f73245e72 # å“‡å¡å¡
  - 871f7fa9-15dc-4ff8-a1b5-f38cbf883da4 # Yunjuå°å¦‚
  - 7734d06e-36c7-4a15-9ec0-f2c4f992f8d3 # æ…ˆæ…ˆğŸ¥„â¤ï¸ğŸ¶
  - 63988abe-8570-40cc-974c-c3a0d0244e40 #å°å­«ğ“¢ğ“¾ğ“·ğŸ¤
  - d337236b-5ebe-4327-af95-ee9435268afe #ğŸŒ¼å…œè‰ğŸŒ¼
  - 368ec191-422a-4803-8c86-0bd80a335a25 #å…”å­æ…¢åŠæ‹
  - eb90f389-6dd0-4876-b2cf-0d1d5741dc26 # æ„›åƒç³–ã®ç³–ğŸ­
  - 54198bef-ee07-426c-90ef-41f7101a7315 # è±ªçˆ½äººå¦»
  - cbab1779-2a8f-43a0-b6e5-13e9233bfe07 # EraserğŸ¤¡çš®çš®
  - 91b3779c-d990-49ea-b7fe-fff397241bdc # å“ˆå¨œæ²’æœ‰è‚¥è‚šå­
  - 9d7ef4d9-c6ce-409e-b2d8-945a63ec737c # éœ²å¨œğŸŒ™Luna
  - 9ff1d605-edf2-49a9-b34f-e77f73245e72 # å“‡å¡å¡
  - 3dfc4067-5286-4a03-9df4-be3b94d750af # ğŸŒ¹ğŸŒ¼AliceğŸŒ¼ğŸŒ¹
  - 055031e3-e8f5-4b6e-b493-ab5e671dc15d # å°èŠ±ğ–¡¼.ğ–¤£ğ–¥§
  - 859e487a-9b59-4a99-80a9-d4484d10f6f9 # My.å°è¿·ç³Šè•¾è•¾â˜ºï¸â˜»
  - aef781e7-a306-46cc-b71d-c8a4764cb018 # å°å®‰_Annn
  - bda7c412-e218-4999-bd93-6ad60614561d # Myco
  - 75b3088f-1a22-4256-b530-c41272e7af8e # å¯æ‘Ÿä»¥â„‚ğ•™ğ•ğ• ğ•–ğŸ’«
  - d471cdf0-54a1-4df3-8322-9efea7e12ad1 # æ¯”å®‰ğŸ¤
  - 30b6a32b-33df-471f-be42-eaecf9fa487f # ç™½æ²ğŸ
  - 71eff6e9-6662-4e68-a62f-05263b698f5a # å°æ¡ƒæ°£ğŸ‘Eva
  - 99304123-c5d3-4caf-9703-5c2e915641ee # èŠ¯èªâ˜•ğŸ¶
  - 9d12c1df-c79e-494b-a21b-46a3d4d883fd # é¡é ­
  - 23df4032-6dee-4958-b22e-8d78210b9c2a # å°é»‘å¤§è‡‰éŸ³æ¨‚penny
  - 6b920a17-a5f2-4bd2-a563-b99d1e1d83b2 # Joanne_L
  - ac58c614-15bf-485f-bf0e-36ebb51f079a # èœœæ¡ƒå£å‘³åˆ©å£é…’
  - 0338e6c9-aa3a-4453-915e-020997870527 # ğŸ§¸å°ç†Šä¸å–æ°´ğŸ¥›
  - 0426009a-7f93-495f-8845-df5ba908089f # drawdrawå“å“ğŸ¨*ï½¥ã‚œï¾Ÿï½¥*Â·Â·
  - 365d01e0-b425-4d4c-94a3-48e8681911cd # å„å„
  - bf07658b-e66a-4dd8-b50f-b2e9688f3c33 # ä¸åƒç³–çš„è²“
  - 63988abe-8570-40cc-974c-c3a0d0244e40 # å°å­«ğ“¢ğ“¾ğ“·ğŸ¤
  - 58a1766f-7702-4dd9-9503-b449a90fed04 # yumiË 
  - 255477a9-e4d3-411e-a614-8dfbadbaaa65 # ä¸€æ¢å°èŒ„å­
  - 8f6b7a86-1694-490d-b9f6-9eb7a49f6550 # Watts_MailerğŸ‰ğŸ‰
  - 7bb90150-d286-4944-9a1c-f9ab7c32e1ac # oè‰¾è–‡o

recommend_streamer_ids_for_new_female_user:
  - 5265b2c9-5046-4950-8b31-69969ae0c230 # ğ“¡Â·ä¸¸
  - 5150cc3c-baa5-48a3-86b4-f3494b9a414e # BANJI
  - 6e304d69-0c33-4028-ac9a-47cd39c5729b # æ‰é‚Š
  - 7a14c76f-576c-4002-befb-8cad59fcb057 # å°å¯†ç¾ŠğŸğŸ¤âœ¨
  - a946156f-7d3e-4f13-831c-a24c0e28a8c2 # ç½¡é‘’
  - eda5b79a-9d8d-429b-bb2c-74205750df2a # âœ¨DALEæˆ´çˆ¾ğŸ’„ğŸ¤âœ¨
  - b5784c30-0e78-43c5-8bcc-149967db7910 # é…¥é…¥ğŸª
  - 75bf28dc-8537-4894-ab20-5a1a9ddac834 # ç±³å‹’å…ˆç”Ÿ
  - 7e3c319d-a589-4953-8e96-1d24a0e22b51 # è‰¾è¿ªå ¤å‚‘â™«
  - 27911e82-9d35-4e3e-866d-3dce5c739afe # å¥¶å­å»Ÿå»Ÿå…¬
  - 220e89ed-330e-4b7b-a6e2-11a61636aa77 # å†·å†·å¿ƒä¸Šäºº
  - b9ab581c-34c2-4a40-b213-de5b170883c0 # GUIğŸ¢
  - 494a617a-9793-4d8c-9750-8fe42368b164 # VCå°å§œ
  - 30e5bf5b-ddb1-41d7-9de7-6054db3b5453 # æ¤°å£³ğ‘ºğ’ğ’–ğ’ğŸ¥¥
  - e53e410c-5105-4c03-99a4-14a03ebefb57 # å°é¬¼æ ¼æ ¼ğŸ‘»
  - 98087126-d226-4d5c-a487-451538883df5 # Ê€Éªá´„á´‹Êà½¼
  - f448dc62-08d2-4954-84ce-96959c1a4a1d # ä¸Šå¿ƒğŸ™
  - eef3e10b-d897-436a-9ed0-3c4100ebae48 # Vçˆ¾æ£®
  - 2bae0757-04e8-4701-8a35-01d602b93cc7 # ğŸ¼ğŸ¸å½ˆå”±MarkğŸ¸ğŸ¤
  - 56f880a8-a75d-4eb0-8372-89078bdd998f # å–µå‰
  - 3d12c69b-dcf4-4f48-a2fd-78208e865b73 # ğŸ¶å°å¤©ğŸ¶ï¼ˆéŸ“ä¸åŠ©ï¼‰
  - e1eb9635-13cb-4765-bf0c-6a4d3865c9ee # ç§‹å…ˆç”Ÿâ™’ï¸
  - 63988abe-8570-40cc-974c-c3a0d0244e40 # å°å­«ğ“¢ğ“¾ğ“·ğŸ¤
  - b5ec2f6b-cfd0-4305-bdc8-6f7f171a1672 # 08isbear
  - 7a14c76f-576c-4002-befb-8cad59fcb057 # å°å¯†ç¾ŠğŸğŸ¤âœ¨
  - 1dcea1eb-af52-401f-8146-c3cf0029a691 # ğŸŒ³å¤§æ¨¹ğŸŒ³