default_min: 
  backend: 
    k8sprod-goapi-main: 9
    k8sprod-gocells-main: 10
    k8sprod-golives-main: 5
    k8sprod-goplatform-main: 24
    k8sprod-gotrade-main: 4
    k8sprod-worker-main: 40
    k8sprod-gousersearch-main: 2
    k8sprod-concert-trade-main: 20
    k8sprod-concert-stream-tw-main: 2
    k8sprod-revprox-main: 18
    k8sprod-revprox-tw-main: 18
    k8sprod-revprox-id-main: 18
    k8sprod-revprox-jp-main: 18
    k8sprod-revprox-sg-main: 18
    k8sprod-revprox-ph-main: 18
    k8sprod-data-middleware-main: 12
  frontend: 
    admin-v2-17app-services: 2
    baobaofu-17app-services: 2
    event-web-17app-services: 4
    live17-17app-services: 10
    skyeye-v2-17app-services: 2
    skyeyewall-17app-services: 2
    webapp-17app-services: 4
settings: 
  backend: 
    fileName: "scheduled_scaling.yaml"
    namespace: "k8sprod"
  frontend: 
    fileName: "scheduled_scaling_frontend.yaml"
    namespace: "default"