endpoint: "https://rs-calc-prod.ml17.live"
token: <SECRET_TAG>CiQAOHuFgPyrXK0QNAyQmGfvjEbAFUUJaHEqFVBBnYm1I63P83sSTACdNR9AKwJFx98RNFCxLwdD/pzFJ3kjcbOLgLspEo+BaJ71JQsPg8btXbTR/unwvnn4lYw+6ldKN6B5X0ypPy2WsCmrFtTUk0ylpVs=</SECRET_TAG>