# mysql config
# preUsername => Add prefix string to username
# defaultHostgroup => Set to the default_hostgroup row in the mysql_users table (ProxySQL)
# destHostgroupR => Set user read permission to the destination_hostgroup row in the mysql_query_rules table (ProxySQL)
# destHostgroupW => Set user read permission to the destination_hostgroup row in the mysql_query_rules table (ProxySQL)

# mongo config
# preUsername => Add prefix string to username

mysql:
  prod:
    preUsername: ""
    defaultHostgroup: 10
    destHostgroupR: 11
    destHostgroupW: 10

  pre-prod:
    preUsername: "pre-"
    defaultHostgroup: 20
    destHostgroupR: 21
    destHostgroupW: 20

  uat:
    preUsername: "uat-"
    defaultHostgroup: 10
    destHostgroupR: 11
    destHostgroupW: 10
mongo:
  prod:
    preUsername: ""

  pre-prod:
    preUsername: "pre-"

  uat:
    preUsername: "uat-"