max: 10	# 0 means disable feature
animations: ["yeti"]
big_brother_prefix: "big_brother"
check_interval: 1m00s
monsters:
- id: monster_1
  hit_consume: 10
  duration: 60s
  stream_alive_threshold: 10m00s
  appear_durations:
  - start_time: 00h00m00s
    end_time: 2h00m00s
  - start_time: 12h00m00s
    end_time: 14h30m00s
  - start_time: 17h00m00s
    end_time: 24h00m00s
  share_ratio: 50 # percentage
  profit_ratio: 24 # percentage
  bonus: 2000
- id: monster_2
  hit_consume: 10
  duration: 60s
  stream_alive_threshold: 10m00s
  appear_durations:
  - start_time: 00h00m00s
    end_time: 2h00m00s
  - start_time: 12h00m00s
    end_time: 14h30m00s
  - start_time: 17h00m00s
    end_time: 24h00m00s
  share_ratio: 50 # percentage
  profit_ratio: 24 # percentage
  bonus: 3000
