endpoint: "http://rs-calc-stag.ml17.live"
token: <SECRET_TAG>CiQAmBGjTft2EyKZUmEtP0ILDUB5GYTbuz24ICLGb7OodVuGNRcSTAClekYIiLq2pskHt+c0ZQr1dtC9zvwN2v4HYPmjjQ7L/gM1SzVn6sIAPgxtyojPPM0O8owGZNpAJOjdPkgM0l72dWZzVlR76cGbonw=</SECRET_TAG>
