notify: "<@U03PP5RTMHA>"
maxClusterEventTime: 1
redis:
  pre-prod-aggrgateway-cache:
    subscriptionID: "CiQA6Z7kBYemeQ40Rxw8oJTmxsbdS3QZ6cp8OmAAZ9Sa/Ro0f7sSMADcvEq6korGUeWzxgfHnV8+BAR7E4AgcTeTa5lzhCyJITT5iMTzdQgUq5NNqCO94g=="
    id: "CiQA6Z7kBcSRBiPDnyL3Vwo+uBrB11X1HCy1S6Kc8X2Ltb5u+xcSMADcvEq6TE03IbcZ5aXsBMTkNHIPpqF28njg0xdCkSYbIxa1ZxP13CBR5reZt+3eqg=="
    usuallySpec: 
      memoryLimitInGb: 1
      throughput: 25000
    stressTestSpec: 
      memoryLimitInGb: 20
      throughput: 1000
  pre-prod-dm-cache:
    subscriptionID: "CiQA6Z7kBbo0tTter5VXLTGVS6T2MGDntRkmIVbz0H7VrmZBAxQSMADcvEq6G38bCj9C0XxBje962KwiiFJM9TJWothDe0VAoHz6cvZkiYfjmarFyTm/8Q=="
    id: "CiQA6Z7kBSOIDdqQuoC3WRkjWyaMUY89FHYY9n+LAHDy5Db0G08SMQDcvEq6SbSpm6CofjZEPaqNXRNz4SkmFmbzBA9Iyb6/DmRvK1xVNe14VSkxANv5l9k="
    usuallySpec: 
      memoryLimitInGb: 1
      throughput: 25000
    stressTestSpec: 
      memoryLimitInGb: 100
      throughput: 40000
  pre-prod-eventory-cache:
    subscriptionID: "CiQA6Z7kBSspjKZUxqUqhYAzhTyh6zHixfJ60C6Bpb2Uu5Rzxe4SMADcvEq6AUl2b+rJb/kBzoYrewPDrdTnP4vlG7Hj44Fk9ixE9dPK9qYPXvTYbP6RPg=="
    id: "CiQA6Z7kBfyGuWDoLc/WjA87JltDaOFlKoCorMV+wmIXbzoRxfYSMQDcvEq6BLDDfjr+62Ob3KyGa2ZjR6HfkpxwVTHOjqSEVw6fHM9ZWISnQ4dCkd/T3qQ="
    usuallySpec: 
      memoryLimitInGb: 1
      throughput: 25000
    stressTestSpec: 
      memoryLimitInGb: 2
      throughput: 120000
  pre-prod-eventory-persist:
    subscriptionID: "CiQA6Z7kBXW6Xf/ECpQF9/4d+HnIe3ph33aOm+4p6bKPM9ZCcdoSMADcvEq6eZVBn9OV4e3rJ2yaR8z2xa51Csk2t512mRM5Ni1xjUL1k9qbbMyhh7MLmg=="
    id: "CiQA6Z7kBWiV8fYIDAhjwgKvJ1+rb3uSzVmnobGjLdWXN3PzDeUSMQDcvEq61MlBxhbk+yDRBLoLuhg0swVEJwYoqiHmVtcVMDhtUIQqhMdDAHSlb0NeTfE="
    usuallySpec: 
      memoryLimitInGb: 20
      throughput: 10000
    stressTestSpec: 
      memoryLimitInGb: 10
      throughput: 50000
  pre-prod-user-info-cache:
    subscriptionID: "CiQA6Z7kBYiHi+NsqGXMtkRk00/8Vmx69u5odLqN4vSsA9WPkjcSMADcvEq6T7pUcw1h0I4nyrATYumCEzfjpLmK6LywXHIDf2IWcPKTK2E30vNc2rLrLg=="
    id: "CiQA6Z7kBSuiEovYAQtBNnoK+XfXcSd0+N68MYfz2FQZOh44i1USMADcvEq6GaeylbyOpHNUD8PxQ+N+XWGDYZh9yZwlCXPfoWx9qawmzQc3eCamOsRs5A=="
    usuallySpec: 
      memoryLimitInGb: 1.5
      throughput: 50000
    stressTestSpec: 
      memoryLimitInGb: 10
      throughput: 50000
  gcp-pre-production-persist:
    subscriptionID: "CiQA6Z7kBRcbCgjERzYEx5zm9czDDjMJ/G14xM5ZONOLmMUjbqQSMADcvEq62y2ipdU3jAslkHXRFbAnQv5sXcMkxhQxYHpEDvBTmV70D1YLlA1hKyEDGA=="
    id: "CiQA6Z7kBV0Q0uO5jK7uDa2IRFzeOHBQ/joEHPjhpXahYqT1eOQSMQDcvEq6nNwrruztsWfovALJBO6iu8NNPhHns3m1VrIbPWzsLMppzwg8QSWP5C3amEE="
    usuallySpec: 
      memoryLimitInGb: 100
      throughput: 25000
    stressTestSpec: 
      memoryLimitInGb: 300
      throughput: 700000
  gcp-pre-production-cache:
    subscriptionID: "CiQA6Z7kBUkR41DrhkSVt5O9SOulC5l1P6VyKHv4rjx/20Eyz2QSMADcvEq6KanwpOPtrKxYjvNT/U/TeZ4npOsE3CX2XyC9A39qMbYD8Y0lw7elMQI3yg=="
    id: "CiQA6Z7kBfihM5p+ex2kmoRs6qJDpnthJys+oxoRKMx3L/Wu3UUSMQDcvEq6PY9VAPEmE2pDOpnlJwwuv0DfbBYTvbN2rfk3yuDU8nkIcLARe1hEPF0vrCU="
    usuallySpec: 
      memoryLimitInGb: 50
      throughput: 25000
    stressTestSpec: 
      memoryLimitInGb: 120
      throughput: 2000000
mongo: 
  default:
    env: "pre-prod"
    usuallySettings:
      instanceSizeName: "M40"
    stressTestSettings:
      instanceSizeName: "M50"
  user:
    env: "pre-prod"
    usuallySettings:
      instanceSizeName: "M30"
    stressTestSettings:
      instanceSizeName: "M50"
  point:
    env: "pre-prod"
    usuallySettings:
      instanceSizeName: "M30"
    stressTestSettings:
      instanceSizeName: "M50"
  stream:
    env: "pre-prod"
    usuallySettings:
      instanceSizeName: "M30"
    stressTestSettings:
      instanceSizeName: "M40"
  eventory:
    env: "pre-prod"
    usuallySettings:
      instanceSizeName: "M30"
    stressTestSettings:
      instanceSizeName: "M40"
  groupcall:
    env: "pre-prod"
    usuallySettings:
      instanceSizeName: "M30"
    stressTestSettings:
      instanceSizeName: "M40"
