# Slack bot (deployment) config
#
# Author: CM Chung
# this file is deployment (alfred) for wave project
# Every service belongs to a type (go, nodejs, webapp, or spinnaker)
# Every type has its own settings like Jenkins endpoints which base on environments
type:
  wave-web:       "webapp"
  wave-dashboard: "webapp"
  wave:           "go"
  wave-slackbot:  "go"
groups:
  backend:
    wave:           "go"
    wave-slackbot:  "go"
  frontend:
    wave-web:       "webapp"
    wave-dashboard: "webapp"
settings:
  go:
    k8sprod:
      endpoint: 'Wave/job/prod-backend-deploy/buildWithParameters?token=gz6E0latrZOse6awWP1ynWmQ6y9ug27yh2T98Nyi'
    k8ssta:
      endpoint: 'Wave/job/stag-backend-deploy/buildWithParameters?token=nKnqqUm2y0JlW8wek4Ae0HD1xUpUBD04T15AjmwT'
  webapp:
    prod:
      endpoint: 'Wave/job/prod-web-deploy/buildWithParameters?token=tHhPGFznbWbLcpeQZioZzewJnUPT42UmNRnDRUyh'
    sta:
      endpoint: 'Wave/job/stag-web-deploy/buildWithParameters?token=uceacpKX7Xk37tHAmrWCPpPGEUEK4dvndRMQYdMz'
