iconInfos:

  - startTime: 2021-05-01 00:00:00 (GMT+0800)
    endTime: 2022-05-30 23:40:00 (GMT+0800)
    liveIcon:
      activeImg: 
      disabledImg: 
    exploreIcon:
      activeImg: 
      disabledImg: 
    followIcon:
      activeImg:  
      disabledImg:  
    videoIcon:
      activeImg:  
      disabledImg:  
    feedIcon:
      activeImg: 
      disabledImg: 
    profileIcon:
      activeImg: 
      disabledImg: 
    navigationBarBackgroundImg: 
    notificationsIconImg: https://cdn.17app.co/2fdc4bb4-b7e1-478a-9178-96433c84b27f.png
    leaderboardIconImg: https://cdn.17app.co/2c356ba7-7e78-4de1-bb76-308072e66228.png

  - startTime: 2021-05-01 00:00:00 (GMT+0800)
    endTime: 2021-05-30 23:40:00 (GMT+0800)
    liveIcon:
      activeImg: https://cdn.17app.co/0ac5932d-ec6f-43a4-9087-837ba8fc28d5.png
      disabledImg: https://cdn.17app.co/64b1ac03-ca6c-48a7-bae3-75347c59a708.png
    exploreIcon:
      activeImg: https://cdn.17app.co/fe4c458b-826e-4224-841a-8e1a0cbfb2a2.png
      disabledImg: https://cdn.17app.co/577faf99-7f4d-448c-b7c2-2f1071bd41b7.png
    followIcon:
      activeImg:  https://cdn.17app.co/0ac5932d-ec6f-43a4-9087-837ba8fc28d5.png
      disabledImg:  https://cdn.17app.co/1936009c-02da-48e1-8ecf-8c9a8469b18e.png
    videoIcon:
      activeImg:  https://cdn.17app.co/0ac5932d-ec6f-43a4-9087-837ba8fc28d5.png
      disabledImg:  https://cdn.17app.co/1936009c-02da-48e1-8ecf-8c9a8469b18e.png
    feedIcon:
      activeImg: https://cdn.17app.co/0ac5932d-ec6f-43a4-9087-837ba8fc28d5.png
      disabledImg: https://cdn.17app.co/1936009c-02da-48e1-8ecf-8c9a8469b18e.png
    profileIcon:
      activeImg: https://cdn.17app.co/f9a3800f-83bf-450a-aa1b-55e09bceb304.png
      disabledImg: https://cdn.17app.co/e3bf173e-a8cb-4616-9441-c3f537e41a3c.png
    navigationBarBackgroundImg: https://cdn.17app.co/cc49be76-6f59-48e4-a8cc-72b0eee16e4f.png
    notificationsIconImg: https://cdn.17app.co/b2251e04-0568-463e-a6f1-ea9d466e4621.png
    leaderboardIconImg: https://cdn.17app.co/4ad76eb2-e4be-44ac-8d0c-81b9aaee484b.png
