iconInfos:
  - startTime: 2021-12-02 17:50:00 (GMT+0800)
    endTime: 2021-12-10 23:59:00 (GMT+0800)
    liveIcon:
      activeImg: https://cdn.17app.co/a30e2638-e2a3-41c3-b7cb-7da2705ab67e.png
      disabledImg: https://cdn.17app.co/02b32d47-7409-4e74-bd23-b36ab8bed6dd.png
    exploreIcon:
      activeImg: https://cdn.17app.co/79adeeb6-9ba8-46a0-81c8-70dfd01792b4.png
      disabledImg: https://cdn.17app.co/c313f980-1d7a-42cc-9843-b70cf42cf37d.png
    followIcon:
      activeImg:
      disabledImg:
    videoIcon:
      activeImg:
      disabledImg:
    feedIcon:
      activeImg: https://cdn.17app.co/78be5206-f9dc-4025-9d2b-071cebb2cead.png
      disabledImg: https://cdn.17app.co/fb8a3c89-835d-49e1-ae56-70b454540be7.png
    profileIcon:
      activeImg: https://cdn.17app.co/b63134ed-d29b-4e74-8511-8c7cf8468340.png
      disabledImg: https://cdn.17app.co/8c71f00c-d52b-46a6-a94e-b34193fb7e33.png
    navigationBarBackgroundImg:
    notificationsIconImg: https://cdn.17app.co/05a6d7f2-ed38-442b-be28-797e2e70741d.png
    leaderboardIconImg: https://cdn.17app.co/fb58a447-d5ce-4ad5-b6a5-e1cd396d00c2.png
#    navigationBarBackgroundImg: https://cdn.17app.co/cc49be76-6f59-48e4-a8cc-72b0eee16e4f.png
#    notificationsIconImg: https://cdn.17app.co/b2251e04-0568-463e-a6f1-ea9d466e4621.png
#    leaderboardIconImg: https://cdn.17app.co/4ad76eb2-e4be-44ac-8d0c-81b9aaee484b.png
