
enableContractApplication: true
hourlyWageWhiteListUserIDs:
  - "7e5ecd7c-5d3c-43dc-bab9-fb052f63d928" #uat2k01
  - "a7d07395-8a5f-4c0e-8791-70a24c0c8c63" #jamestw2
applyCriteria:
  streamerLevel: 80
  applyAfterRejectionPeriodDays: 0
