# birthdayCountdownDays: show incoming birthday icon in the range from birthday-n to birthday-1 day
# birthdayAfterDays: show after-birthday icon in the range from birthday+1 to birthday+n day
# enableQueryACL: set to true to use ACL for authorization on queries
# enableMutationACL: set to true to use ACL for authorization on mutations
# enableBQ: set to true to get follower information from BigQuery

birthdayCountdownDays: 3
birthdayAfterDays: 1
nearOutdatedDays:
  TW: 7
  JP: 60
  US: 60
enableQueryACL: false
enableMutationACL: false
enableBQ: true
extendContractExcludeRegions: ["JP", "US"]
renewContractIncludeRegions: ["JP", "US", "TW"]
enableConcurrentGetStats: true
concurrentWorkerSize: 1
enableSlackContractNotif: false
maxTemplateSize: 200
renewContract:
  TW: 7
  JP: 60
  US: 60
extendContract:
  TW: 7
validDayByMinimumStreamingTimeEffectiveTime: "2021-02-01T00:00:00+00:00"

useLocalcache: true
enableValidateContractDateAndOperation: true
enableQueryRevenuesV2: true
