enable: true
leaderboardCount: 31 # index bug in superstar
settleThreshold: 01m30s
hourLeaderboardDurations:
- startTime: 11h05m00s
  endTime: 15h05m00s
- startTime: 19h05m00s
  endTime: 23h05m00s
hotSetting: # Position is 1 based indexing
  maxRankInHot: 10 # Indicate how many top x stars should be put on hot
  # newStarsHotPos: [3]
  # superStarsHotPos: [1, 4]
systemRedenvelopeID: "redenvelope_no_superstar_HK"
pkStarRedenvelopeID: "redenvelope_pk_leaderboard_HK"
enableFilterHotStreamForNewStar: true
new_stars:
- id: 0
  redenvelopeReward: 12
- id: 1
  redenvelopeReward: 6
- id: 2
  redenvelopeReward: 6

super_stars:
- id: 0
  redenvelopeReward: 12
- id: 1
  redenvelopeReward: 6
- id: 2
  redenvelopeReward: 6
- id: 3
  redenvelopeReward: 6
- id: 4
  redenvelopeReward: 6

pk_stars:
# - id: 0
#   redenvelopeReward: 5
# - id: 1
#   redenvelopeReward: 3
# - id: 2
#   redenvelopeReward: 2
