enable: false
leaderboardCount: 31 # index bug in superstar
settleThreshold: 01m30s
hourLeaderboardDurations:  # To be removed
- start_time: 12h00m00s
  end_time: 18h05m00s
hotSetting: # Position is 1 based indexing
  maxRankInHot: 10 # Indicate how many top x stars should be put on hot
  newStarsHotPos: [3]
  superStarsHotPos: [1, 4]
systemRedenvelopeID: "redenvelope_no_superstar"
enableFilterHotStreamForNewStar: true
new_stars:
- id: 0
  redenvelopeReward: 12
- id: 1
  redenvelopeReward: 6
- id: 2
  redenvelopeReward: 6
- id: 3
  redenvelopeReward: 6
- id: 4
  redenvelopeReward: 6
- id: 5
  redenvelopeReward: 6
- id: 6
  redenvelopeReward: 6
- id: 7
  redenvelopeReward: 6
- id: 8
  redenvelopeReward: 6        
- id: 9
  redenvelopeReward: 6          
super_stars:
- id: 0
  redenvelopeReward: 12
- id: 1
  redenvelopeReward: 6
- id: 2
  redenvelopeReward: 6
- id: 3
  redenvelopeReward: 6
- id: 4
  redenvelopeReward: 6
- id: 5
  redenvelopeReward: 6
- id: 6
  redenvelopeReward: 6
- id: 7
  redenvelopeReward: 6
- id: 8
  redenvelopeReward: 6        
- id: 9
  redenvelopeReward: 6
