type:
  alfred:       "go"
  revprox:      "go"
  goapi:        "go"
  cronjob:      "go"
  notif:        "go"
  slackbot:     "go"
  shield:       "go"
  skyeye:       "go"
  mktevent:     "go"
  event-server: "go"
  worker:       "go"
  exchange:     "go"
  data-middleware: "go"
  admin:        "nodejs"
  event-web:    "webapp"
  webapp:       "webapp"
  skyeyewall:   "webapp"
  17live:       "webapp"
  dummy:        "dummy"
settings:
  webapp:
    rc:
      endpoint: 'k8s-webapp-deployment/buildWithParameters?token=uceacpKX7Xk37tHAmrWCPpPGEUEK4dvndRMQYdMz&ENV=rc'
    sta:
      endpoint: 'k8s-webapp-deployment/buildWithParameters?token=uceacpKX7Xk37tHAmrWCPpPGEUEK4dvndRMQYdMz&ENV=sta'
    prod:
      endpoint: 'k8s-webapp-deployment/buildWithParameters?token=uceacpKX7Xk37tHAmrWCPpPGEUEK4dvndRMQYdMz&ENV=prod'
  go:
    k8sstaqa:
      endpoint: 'k8sstaqa-deployment-goapi/buildWithParameters?token=egxVYNaBdHqKWMnJV72EQsG7xtX2UYiYHsLNUWVe'
    k8ssta:
      endpoint: 'k8ssta-deployment-goapi/buildWithParameters?token=qLnZFhgbtDwYHq3bpqdsfHkXqEbMS7VAuTshkBrQ'
    k8sprod:
      endpoint: 'k8sprod-deployment-goapi/buildWithParameters?token=WPZgd7ag4Q7ksL3nSqLW2QVq6aaDK5apguCvR23M'
  nodejs:
    dev:
      endpoint: 'dev-deployment-nodejs/buildWithParameters?token=GaFJ9yVbWusyzqs9babWxJGTJUukHFxLRLULZdYH'
    prod:
      endpoint: 'prod-deployment-nodejs/buildWithParameters?token=A5GLMFgZsE7jeBySpcaj7aqHBvd2ZDHVHe24mTMD'
    k8ssta:
      endpoint: 'k8ssta-deployment-nodejs/buildWithParameters?token=ZQuygxVpytYgnanavuVkEdQsccQKr36RyLWNhgjY'
    k8sprod:
      endpoint: 'k8sprod-deployment-nodejs/buildWithParameters?token=MdfMrjx5egcQKAQMdEHP92hNACQvPemnvTWRT3fe'
