# region_mode are defined as following
# - 1: ALL
# - 2: INCLUDE
# - 3: EXCLUDE
# theme are defined as following
# - 1: normal
# - 2: chinese new year 2018
# - 3: system reward
# type are definded as following
# - 1: normal
# - 2: custom
# - 3: system
# - 4: recommend
region_mode: 3
regions: []
countdown_time: 60 # deprecated
event_time: 10 # for display in notice only
creation_by_streamer: false
custom_min_point: 1000
custom_max_point: 99999999
recommend_ios_support_version: 3.0.0
recommend_android_support_version: 2.3.10
handleUnfinishedBufferMins: 10
handleUnfinishedMaxDays: 5
whiteListUserIDs:
 - "d1cd5a6a-3346-4263-85ef-c9f3a600de39"  # ryanmachi
 - "5cbbcca2-b412-4872-8555-4c0f1aeed6ff"  # finn
 - "2fdb9f0f-cdc3-4eb4-a8af-ff1c261a2369"  # 趣你的娛樂
 - "ad9a4ee5-e7eb-47f0-8ef4-727b286aa48f"  # David's Angels
 - "1064096b-6585-4dc3-aa85-218cb2e2a8fa"  # 77歡樂城
 - "cef2923e-cc43-4577-a33e-ef89e619a12a"  # 決戰17聲展台
 - "4408d847-42dc-4ad5-8447-978aede1f0f4"  #電玩者們
 - "3f699c11-4156-45f5-43f3-d516d2a3b9f5"  #姐說了算
 - "c0a3ae3a-9bc8-4e5f-89c9-3ffda0226e81" #17動起來
 - "0684f899-6f7c-4bba-a37b-efc5927dbbd4" #搶手主打星
 - "10121330-1f48-4266-56a4-d3d297421e52" #球神問卜
 - "92fe1b07-b836-4068-8a72-c8abcff352ad" #爆料17追
 - "fa0c2a70-9774-4562-bdf1-b787949fe7db" #流行翎距離
 - "f759c3fa-fb59-42cd-614c-ffc9d6bf3117" #P城酒吧
 - "20ab9b50-8d51-41a1-96fc-8012d2f3c122" #17耍星機
 - "9327c27e-72c3-4063-9408-8d6ac8751b6c" #17鏈戀車
 - "ab97d952-6baf-439b-7d29-4dba7051a868" #海祭18樂
 - "cecbc933-7478-4d33-944b-db8b642f2b1f" #台灣好
 - "23bb2414-778f-4894-9c71-6aa4e9f1e244" #女神KTV
 - "e75f30cb-4160-4a65-aec3-757d250626c7" #17698一起遛酒吧
 - "69831671-dc24-4bff-5b5a-71c64f54f7f5" #WOTD猛龍過江職業技擊爭霸賽
 - "4cbcce6a-df9d-48be-780a-f04216268690" #金光布袋戲
 - "e0d68bc2-03c1-4a38-a149-ee65d0089036" #當我們喇在一起
 - "2dddf9dc-58ba-4a78-954b-93cb79c4ae12" #5team甜心日記
 - "e3a69570-6384-4161-4404-06d7f0680894" #17演唱會
 - "5a656cfc-cdef-477b-ba46-56d43585039c" #Cool Japan TV
 - "97851fd4-13be-47cd-a6f1-ddd8ceb36fd5" #17media
 - "25587e1b-9942-4166-ba92-de889bd9789f" #虛擬主播小Q
 - "ca8f67cd-e4db-40b8-aa0e-a3f45041a429" #17originals
redenvelopes:
- id: redenvelope_no_superstar
  img_URL: http://cdn.17app.co/a30cf4a7-9867-4a4c-9acc-a808ed14f3c5.png
  name_token: redenvelope_system_bonus
  point: 666
  min_point: 666
  max_point: 666
  announceable: false
  announce_threshold: -171717
  countdown_time: 150
  event_time: 10
  fee: 350
  theme: 3
  type: 3
  is_offline: false
  region_mode: 2
  regions: ["TW"]
  package_list:
    - amount: 1
      point: 89
    - amount: 1
      point: 44
    - amount: 1
      point: 33
    - amount: 9
      point: 5
    - amount: 35
      point: 3
- id: redenvelope_no_superstar_HK
  img_URL: http://cdn.17app.co/a30cf4a7-9867-4a4c-9acc-a808ed14f3c5.png
  name_token: redenvelope_system_bonus
  point: 288
  min_point: 288
  max_point: 288
  announceable: false
  announce_threshold: -171717
  countdown_time: 150
  event_time: 10
  fee: 0
  theme: 3
  type: 3
  is_offline: false
  region_mode: 2
  regions: ["HK"]
  package_list:
    - amount: 1
      point: 89
    - amount: 1
      point: 16
    - amount: 1
      point: 10
    - amount: 2
      point: 8
    - amount: 3
      point: 7
    - amount: 5
      point: 6
    - amount: 8
      point: 4
    - amount: 15
      point: 2
    - amount: 44
      point: 1
- id: redenvelope_no_recommend
  img_URL: http://cdn.17app.co/8d27f90a-3419-4bc4-af6a-3b6a462e5aad.png
  name_token: red_envelope_promote_name
  point: 5000
  announceable: false
  announce_threshold: -171717
  countdown_time: 30
  event_time: 10
  fee: 250
  theme: 1
  type: 4
  is_offline: false
  region_mode: 2
  regions: ["TW", "US"]
  package_list:
    - amount: 1
      point: 500
    - amount: 1
      point: 325
    - amount: 1
      point: 250
    - amount: 2
      point: 175
    - amount: 3
      point: 125
    - amount: 5
      point: 100
    - amount: 8
      point: 75
    - amount: 15
      point: 50
    - amount: 44
      point: 25
- id: redenvelope_no_custom
  img_URL: http://cdn.17app.co/203fb9b5-9d97-4b15-bcdf-2dcb2cc76b1a.png
  name_token: redenvelope_customize_name
  point: 0 # unchangeable
  min_point: 1000
  max_point: 9999999
  announceable: true
  announce_threshold: 8888
  countdown_time: 60
  event_time: 10
  fee: 50 # workaround, it is percentage * 10
  theme: 1
  type: 2
  is_offline: false
  region_mode: 2
  regions: ["TW", "US"]
  package_list:
    - amount: 1
      point: 100 # workaround, it is percentage * 10
    - amount: 1
      point: 65
    - amount: 1
      point: 50
    - amount: 2
      point: 35
    - amount: 3
      point: 25
    - amount: 5
      point: 20
    - amount: 8
      point: 15
    - amount: 15
      point: 10
    - amount: 44
      point: 5
- id: cny_redenvelope_no_1
  img_URL: https://assets-17app.akamaized.net/a8290204-959b-4314-8b7d-696e106cdbeb.png
  name_token: cny_redenvelope_no_1
  point: 1888888
  announceable: true
  announce_threshold: -171717
  countdown_time: 60
  event_time: 10
  fee: 94444
  theme: 2
  type: 1
  is_offline: false
  region_mode: 2
  regions: ["TW", "HK", "SG", "MY"]
  package_list:
    - amount: 1
      point: 18888
    - amount: 1
      point: 12000
    - amount: 1
      point: 7473
    - amount: 146
      point: 5373
    - amount: 199
      point: 3375
    - amount: 200
      point: 1500
- id: cny_redenvelope_no_2
  img_URL: https://assets-17app.akamaized.net/996ffb48-e66f-41c6-b607-86d7af1a95f5.png
  name_token: cny_redenvelope_no_2
  point: 188888
  announceable: true
  announce_threshold: -171717
  countdown_time: 30
  event_time: 10
  fee: 9444
  theme: 2
  type: 1
  is_offline: false
  region_mode: 2
  regions: ["TW", "HK", "SG", "MY"]
  package_list:
    - amount: 1
      point: 2020
    - amount: 1
      point: 1486
    - amount: 1
      point: 1218
    - amount: 130
      point: 650
    - amount: 170
      point: 400
    - amount: 101
      point: 220
- id: cny_redenvelope_no_3
  img_URL: https://assets-17app.akamaized.net/5311de07-9e11-4383-b431-faab98f716cd.png
  name_token: cny_redenvelope_no_3
  point: 18888
  announceable: true
  announce_threshold: -171717
  countdown_time: 30
  event_time: 10
  fee: 944
  theme: 2
  type: 1
  is_offline: false
  region_mode: 2
  regions: ["TW", "HK", "SG", "MY"]
  package_list:
    - amount: 1
      point: 500
    - amount: 1
      point: 304
    - amount: 1
      point: 188
    - amount: 32
      point: 136
    - amount: 126
      point: 100
- id: cny_redenvelope_no_4
  img_URL: https://assets-17app.akamaized.net/130b370b-d38f-4c7a-b021-2b4e0329bd3e.png
  name_token: cny_redenvelope_no_4
  point: 1888
  announceable: false
  announce_threshold: -171717
  countdown_time: 30
  event_time: 10
  fee: 94
  theme: 2
  type: 1
  is_offline: false
  region_mode: 2
  regions: ["TW", "HK", "SG", "MY"]
  package_list:
    - amount: 1
      point: 199
    - amount: 1
      point: 158
    - amount: 1
      point: 137
    - amount: 13
      point: 100
- id: redenvelope_no_1
  img_URL: http://cdn.17app.co/fb3bd824-1f79-4e9d-bc7d-9fcc7c3dc4f1.png
  name_token: redenvelope_name_no_1
  point: 888888
  announceable: true
  announce_threshold: -171717
  countdown_time: 60
  event_time: 10
  fee: 44444
  theme: 1
  type: 1
  is_offline: false
  region_mode: 3
  regions: []
  package_list:
    - amount: 1
      point: 8888
    - amount: 1
      point: 6000
    - amount: 1
      point: 3932
    - amount: 145
      point: 2688
    - amount: 153
      point: 1688
    - amount: 200
      point: 888
- id: redenvelope_no_2
  img_URL: http://cdn.17app.co/970fe736-1bb5-4bd2-9041-a0f14e057278.png
  name_token: redenvelope_name_no_2
  point: 88888
  announceable: true
  announce_threshold: -171717
  countdown_time: 30
  event_time: 10
  fee: 4444
  theme: 1
  type: 1
  is_offline: false
  region_mode: 3
  regions: []
  package_list:
    - amount: 1
      point: 1010
    - amount: 1
      point: 743
    - amount: 1
      point: 616
    - amount: 151
      point: 325
    - amount: 165
      point: 200
- id: redenvelope_no_3
  img_URL: http://cdn.17app.co/7d0fd036-3869-42a7-9168-057388f9e232.png
  name_token: redenvelope_name_no_3
  point: 8888
  announceable: true
  announce_threshold: -171717
  countdown_time: 30
  event_time: 10
  fee: 444
  theme: 1
  type: 1
  is_offline: false
  region_mode: 3
  regions: []
  package_list:
    - amount: 1
      point: 241
    - amount: 1
      point: 140
    - amount: 1
      point: 99
    - amount: 32
      point: 77
    - amount: 110
      point: 50
- id: redenvelope_no_4
  img_URL: http://cdn.17app.co/a30cf4a7-9867-4a4c-9acc-a808ed14f3c5.png
  name_token: redenvelope_name_no_4
  point: 888
  announceable: false
  announce_threshold: -171717
  countdown_time: 30
  event_time: 10
  fee: 44
  theme: 1
  type: 1
  is_offline: false
  region_mode: 3
  regions: []
  package_list:
    - amount: 1
      point: 102
    - amount: 1
      point: 74
    - amount: 1
      point: 68
    - amount: 12
      point: 50
